<span style = "font-family: Verdana; font-size: 20px">

#### **Data Exploration and Cleaning**
</span>

In [80]:
import pandas as pd
import numpy as np

In [81]:
data = pd.read_csv("data/modified/nonempty_pokemon.csv", keep_default_na=False, dtype = {'ID': str})

In [82]:
combats = pd.read_csv("data/raw_data/combats.csv" #, dtype = {'First_pokemon': str, 'Second_pokemon': str, 'Winner': str}
                      )

<span style = "font-family: Verdana; font-size: 20px">

#### **I. Pokémon dataset**
</span>

In [83]:
def describe_feature(data, feat):
    print(f"- Type: {data.loc[:, feat].dtype}")
    print(f"- First rows:\n{data.loc[:, feat].head(5)}")
    print(f"- Last rows:\n{data.loc[:, feat].tail(5)}")
    print(f"- Number of missing values: {data.loc[:, feat].isna().sum()}")
    print(data.loc[:, feat].dtype)
    print(f"- Number of distinct values: {data.loc[:, feat].nunique()}")
    with pd.option_context('display.max_rows', None):
        print(f"- Unique value counts:\n{data.loc[:, feat].value_counts()}")
    if data.loc[:, feat].dtype in ['int64', 'float64']:
        print(data.describe()[feat])
    else:
        print(f"- Unique values: {data.loc[:, feat].unique()}")


def remove_first_last_letter(series, char):
    series = pd.Series([sublist[1:-1] if len(sublist) >= 3 else sublist 
                      for sublist in series])
    return series.str[1:-1].str.split(f"\'{char} \'")

def get_first_element(series):
    def process_list_first(lst):
        return lst[0]
    
    return series.apply(process_list_first)

def get_second_element(series):
    def process_list_second(lst):
        if len(lst) >= 2:
            return lst[1]
        elif len(lst) == 1:
            return 'None'
    
    return series.apply(process_list_second)

In [84]:
print("Pokémon dataset")
print(f"Number of rows: {data.shape[0]}, number of columns: {data.shape[1]}")
print(f"Column names: {data.columns}")
print(f"Number of missing values: {data.isna().sum().sum()}")

Pokémon dataset
Number of rows: 800, number of columns: 48
Column names: Index(['ID', 'Name', 'Type 1', 'Type 2', 'Abilities', 'HiddenAbility',
       'Generation', 'Hp', 'Attack', 'Defense', 'SpecialAttack',
       'SpecialDefense', 'Speed', 'TotalStats', 'Weight', 'Height',
       'GenderProbM', 'Category', 'CatchRate', 'EggCycles', 'EggGroup',
       'LevelingRate', 'BaseFriendship', 'IsLegendary', 'IsMythical',
       'IsUltraBeast', 'HasMega', 'EvoStage', 'TotalEvoStages', 'PreevoName',
       'DamageFromNormal', 'DamageFromFighting', 'DamageFromFlying',
       'DamageFromPoison', 'DamageFromGround', 'DamageFromRock',
       'DamageFromBug', 'DamageFromGhost', 'DamageFromSteel', 'DamageFromFire',
       'DamageFromWater', 'DamageFromGrass', 'DamageFromElectric',
       'DamageFromPsychic', 'DamageFromIce', 'DamageFromDragon',
       'DamageFromDark', 'DamageFromFairy'],
      dtype='object')
Number of missing values: 0

In [85]:
pd.options.display.max_columns = None
data.head(5)

,ID,Name,Type 1,Type 2,Abilities,HiddenAbility,Generation,Hp,Attack,Defense,SpecialAttack,SpecialDefense,Speed,TotalStats,Weight,Height,GenderProbM,Category,CatchRate,EggCycles,EggGroup,LevelingRate,BaseFriendship,IsLegendary,IsMythical,IsUltraBeast,HasMega,EvoStage,TotalEvoStages,PreevoName,DamageFromNormal,DamageFromFighting,DamageFromFlying,DamageFromPoison,DamageFromGround,DamageFromRock,DamageFromBug,DamageFromGhost,DamageFromSteel,DamageFromFire,DamageFromWater,DamageFromGrass,DamageFromElectric,DamageFromPsychic,DamageFromIce,DamageFromDragon,DamageFromDark,DamageFromFairy
0,1,Bulbasaur,Grass,Poison,['Overgrow'],['Chlorophyll'],I,45.0,49.0,49.0,65.0,65.0,45.0,318.0,6.9,0.7,0.875,Seed Pokémon,45,20,['Monster' 'Grass'],Medium Slow,70,0,0,0,0,1,3,No Preevolution,1.0,0.5,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,0.5,0.25,0.5,2.0,2.0,1.0,1.0,0.5
1,2,Ivysaur,Grass,Poison,['Overgrow'],['Chlorophyll'],I,60.0,62.0,63.0,80.0,80.0,60.0,405.0,13.0,1.0,0.875,Seed Pokémon,45,20,['Monster' 'Grass'],Medium Slow,70,0,0,0,0,2,3,Bulbasaur,1.0,0.5,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,0.5,0.25,0.5,2.0,2.0,1.0,1.0,0.5
2,3,Venusaur,Grass,Poison,['Overgrow'],['Chlorophyll'],I,80.0,82.0,83.0,100.0,100.0,80.0,625.0,100.0,2.0,0.875,Seed Pokémon,45,20,['Monster' 'Grass'],Medium Slow,70,0,0,0,1,3,3,Ivysaur,1.0,0.5,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,0.5,0.25,0.5,2.0,2.0,1.0,1.0,0.5
3,4,Mega Venusaur,Grass,Poison,['Thick Fat'],[],I,80.0,100.0,123.0,122.0,120.0,80.0,625.0,155.5,2.4,0.875,Seed Pokémon,45,20,['Monster' 'Grass'],Medium Slow,70,0,0,0,1,3,3,Venusaur,1.0,0.5,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,0.25,0.5,2.0,1.0,1.0,1.0,0.5
4,5,Charmander,Fire,None,['Blaze'],['Solar Power'],I,39.0,52.0,43.0,60.0,50.0,65.0,309.0,8.5,0.6,0.875,Lizard Pokémon,45,20,['Monster' 'Dragon'],Medium Slow,70,0,0,0,0,1,3,No Preevolution,1.0,1.0,1.0,1.0,2.0,2.0,0.5,1.0,0.5,0.5,2.0,0.50,1.0,1.0,0.5,1.0,1.0,0.5

<span style = "font-family: Verdana; font-size: 20px">

##### **ID**
</span>

In [86]:
describe_feature(data, 'ID')

- Type: object
- First rows:
0    1
1    2
2    3
3    4
4    5
Name: ID, dtype: object
- Last rows:
795    796
796    797
797    798
798    799
799    800
Name: ID, dtype: object
- Number of missing values: 0
object
- Number of distinct values: 800
- Unique value counts:
ID
1      1
538    1
528    1
529    1
530    1
531    1
532    1
533    1
534    1
535    1
536    1
537    1
539    1
2      1
540    1
541    1
542    1
543    1
544    1
545    1
546    1
547    1
548    1
549    1
527    1
526    1
525    1
524    1
503    1
504    1
505    1
506    1
507    1
508    1
509    1
510    1
511    1
512    1
513    1
514    1
515    1
516    1
517    1
518    1
519    1
520    1
521    1
522    1
523    1
550    1
551    1
552    1
577    1
579    1
580    1
581    1
582    1
583    1
584    1
585    1
586    1
587    1
588    1
589    1
590    1
591    1
592    1
593    1
594    1
595    1
596    1
597    1
598    1
599    1
578    1
576    1
553    1
575    1
554    1
555    1
556    1
557    1
558    1
559    1
560    1
561    1
562    1
563    1
564    1
565    1
566    1
567    1
568    1
569    1
570    1
571    1
572    1
573    1
574    1
502    1
501    1
500    1
426    1
428    1
429    1
430    1
431    1
432    1
433    1
434    1
435    1
436    1
437    1
438    1
439    1
440    1
441    1
442    1
443    1
444    1
445    1
446    1
447    1
448    1
427    1
425    1
450    1
424    1
403    1
404    1
405    1
406    1
407    1
408    1
409    1
410    1
411    1
412    1
413    1
414    1
415    1
416    1
417    1
418    1
419    1
420    1
421    1
422    1
423    1
449    1
451    1
499    1
476    1
478    1
479    1
480    1
481    1
482    1
483    1
484    1
485    1
486    1
487    1
488    1
489    1
490    1
491    1
492    1
493    1
494    1
495    1
496    1
497    1
498    1
477    1
475    1
452    1
474    1
453    1
454    1
455    1
456    1
457    1
458    1
459    1
460    1
461    1
462    1
463    1
464    1
465    1
466    1
467    1
468    1
469    1
470    1
471    1
472    1
473    1
600    1
601    1
602    1
727    1
729    1
730    1
731    1
732    1
733    1
734    1
735    1
736    1
737    1
738    1
739    1
740    1
741    1
742    1
743    1
744    1
745    1
746    1
747    1
748    1
749    1
728    1
726    1
751    1
725    1
704    1
705    1
706    1
707    1
708    1
709    1
710    1
711    1
712    1
713    1
714    1
715    1
716    1
717    1
718    1
719    1
720    1
721    1
722    1
723    1
724    1
750    1
752    1
702    1
777    1
779    1
780    1
781    1
782    1
783    1
784    1
785    1
786    1
787    1
788    1
789    1
790    1
791    1
792    1
793    1
794    1
795    1
796    1
797    1
798    1
799    1
778    1
776    1
753    1
775    1
754    1
755    1
756    1
757    1
758    1
759    1
760    1
761    1
762    1
763    1
764    1
765    1
766    1
767    1
768    1
769    1
770    1
771    1
772    1
773    1
774    1
703    1
701    1
603    1
627    1
629    1
630    1
631    1
632    1
633    1
634    1
635    1
636    1
637    1
638    1
639    1
640    1
641    1
642    1
643    1
644    1
645    1
646    1
647    1
648    1
649    1
628    1
626    1
651    1
625    1
604    1
605    1
606    1
607    1
608    1
609    1
610    1
611    1
612    1
613    1
614    1
615    1
616    1
617    1
618    1
619    1
620    1
621    1
622    1
623    1
624    1
650    1
652    1
700    1
677    1
679    1
680    1
681    1
682    1
683    1
684    1
685    1
686    1
687    1
688    1
689    1
690    1
691    1
692    1
693    1
694    1
695    1
696    1
697    1
698    1
699    1
678    1
676    1
653    1
675    1
654    1
655    1
656    1
657    1
658    1
659    1
660    1
661    1
662    1
663    1
664    1
665    1
666    1
667    1
668    1
669    1
670    1
671    1
672    1
673    1
674    1
402    1
401    1
400    1
126    1
128    1
129    1
130    1
131    1
132    1
133    1
134    1
135    1
136    1
137    1
138    1
139    1
140    1
141    1
142    1
143    1
144    1
145    1
146    1
147    1
148    1
127    1
125    1
150    1
124    1
103    1
104    1
105    1
106    1
107    1
108    1
109    1
110    1
111    1
112    1
113    1
114    1
115    1
116    1
117    1
118    1
119    1
120    1
121    1
122    1
123    1
149    1
151    1
101    1
176    1
178    1
179    1
180    1
181    1
182    1
183    1
184    1
185    1
186    1
187    1
188    1
189    1
190    1
191    1
192    1
193    1
194    1
195    1
196    1
197    1
198    1
177    1
175    1
152    1
174    1
153    1
154    1
155    1
156    1
157    1
158    1
159    1
160    1
161    1
162    1
163    1
164    1
165    1
166    1
167    1
168    1
169    1
170    1
171    1
172    1
173    1
102    1
100    1
200    1
26     1
28     1
29     1
30     1
31     1
32     1
33     1
34     1
35     1
36     1
37     1
38     1
39     1
40     1
41     1
42     1
43     1
44     1
45     1
46     1
47     1
48     1
27     1
25     1
50     1
24     1
3      1
4      1
5      1
6      1
7      1
8      1
9      1
10     1
11     1
12     1
13     1
14     1
15     1
16     1
17     1
18     1
19     1
20     1
21     1
22     1
23     1
49     1
51     1
99     1
76     1
78     1
79     1
80     1
81     1
82     1
83     1
84     1
85     1
86     1
87     1
88     1
89     1
90     1
91     1
92     1
93     1
94     1
95     1
96     1
97     1
98     1
77     1
75     1
52     1
74     1
53     1
54     1
55     1
56     1
57     1
58     1
59     1
60     1
61     1
62     1
63     1
64     1
65     1
66     1
67     1
68     1
69     1
70     1
71     1
72     1
73     1
199    1
201    1
399    1
326    1
328    1
329    1
330    1
331    1
332    1
333    1
334    1
335    1
336    1
337    1
338    1
339    1
340    1
341    1
342    1
343    1
344    1
345    1
346    1
347    1
348    1
327    1
325    1
350    1
324    1
303    1
304    1
305    1
306    1
307    1
308    1
309    1
310    1
311    1
312    1
313    1
314    1
315    1
316    1
317    1
318    1
319    1
320    1
321    1
322    1
323    1
349    1
351    1
301    1
376    1
378    1
379    1
380    1
381    1
382    1
383    1
384    1
385    1
386    1
387    1
388    1
389    1
390    1
391    1
392    1
393    1
394    1
395    1
396    1
397    1
398    1
377    1
375    1
352    1
374    1
353    1
354    1
355    1
356    1
357    1
358    1
359    1
360    1
361    1
362    1
363    1
364    1
365    1
366    1
367    1
368    1
369    1
370    1
371    1
372    1
373    1
302    1
300    1
202    1
226    1
228    1
229    1
230    1
231    1
232    1
233    1
234    1
235    1
236    1
237    1
238    1
239    1
240    1
241    1
242    1
243    1
244    1
245    1
246    1
247    1
248    1
227    1
225    1
250    1
224    1
203    1
204    1
205    1
206    1
207    1
208    1
209    1
210    1
211    1
212    1
213    1
214    1
215    1
216    1
217    1
218    1
219    1
220    1
221    1
222    1
223    1
249    1
251    1
299    1
276    1
278    1
279    1
280    1
281    1
282    1
283    1
284    1
285    1
286    1
287    1
288    1
289    1
290    1
291    1
292    1
293    1
294    1
295    1
296    1
297    1
298    1
277    1
275    1
252    1
274    1
253    1
254    1
255    1
256    1
257    1
258    1
259    1
260    1
261    1
262    1
263    1
264    1
265    1
266    1
267    1
268    1
269    1
270    1
271    1
272    1
273    1
800    1
Name: count, dtype: int64
- Unique values: ['1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12' '13' '14' '15' '16'
 '17' '18' '19' '20' '21' '22' '23' '24' '25' '26' '27' '28' '29' '30'
 '31' '32' '33' '34' '35' '36' '37' '38' '39' '40' '41' '42' '43' '44'
 '45' '46' '47' '48' '49' '50' '51' '52' '53' '54' '55' '56' '57' '58'
 '59' '60' '61' '62' '63' '64' '65' '66' '67' '68' '69' '70' '71' '72'
 '73' '74' '75' '76' '77' '78' '79' '80' '81' '82' '83' '84' '85' '86'
 '87' '88' '89' '90' '91' '92' '93' '94' '95' '96' '97' '98' '99' '100'
 '101' '102' '103' '104' '105' '106' '107' '108' '109' '110' '111' '112'
 '113' '114' '115' '116' '117' '118' '119' '120' '121' '122' '123' '124'
 '125' '126' '127' '128' '129' '130' '131' '132' '133' '134' '135' '136'
 '137' '138' '139' '140' '141' '142' '143' '144' '145' '146' '147' '148'
 '149' '150' '151' '152' '153' '154' '155' '156' '157' '158' '159' '160'
 '161' '162' '163' '164' '165' '166' '167' '168' '169' '170' '171' '172'
 '173' '174' '175' '176' '177' '178' '179' '180' '181' '182' '183' '184'
 '185' '186' '187' '188' '189' '190' '191' '192' '193' '194' '195' '196'
 '197' '198' '199' '200' '201' '202' '203' '204' '205' '206' '207' '208'
 '209' '210' '211' '212' '213' '214' '215' '216' '217' '218' '219' '220'
 '221' '222' '223' '224' '225' '226' '227' '228' '229' '230' '231' '232'
 '233' '234' '235' '236' '237' '238' '239' '240' '241' '242' '243' '244'
 '245' '246' '247' '248' '249' '250' '251' '252' '253' '254' '255' '256'
 '257' '258' '259' '260' '261' '262' '263' '264' '265' '266' '267' '268'
 '269' '270' '271' '272' '273' '274' '275' '276' '277' '278' '279' '280'
 '281' '282' '283' '284' '285' '286' '287' '288' '289' '290' '291' '292'
 '293' '294' '295' '296' '297' '298' '299' '300' '301' '302' '303' '304'
 '305' '306' '307' '308' '309' '310' '311' '312' '313' '314' '315' '316'
 '317' '318' '319' '320' '321' '322' '323' '324' '325' '326' '327' '328'
 '329' '330' '331' '332' '333' '334' '335' '336' '337' '338' '339' '340'
 '341' '342' '343' '344' '345' '346' '347' '348' '349' '350' '351' '352'
 '353' '354' '355' '356' '357' '358' '359' '360' '361' '362' '363' '364'
 '365' '366' '367' '368' '369' '370' '371' '372' '373' '374' '375' '376'
 '377' '378' '379' '380' '381' '382' '383' '384' '385' '386' '387' '388'
 '389' '390' '391' '392' '393' '394' '395' '396' '397' '398' '399' '400'
 '401' '402' '403' '404' '405' '406' '407' '408' '409' '410' '411' '412'
 '413' '414' '415' '416' '417' '418' '419' '420' '421' '422' '423' '424'
 '425' '426' '427' '428' '429' '430' '431' '432' '433' '434' '435' '436'
 '437' '438' '439' '440' '441' '442' '443' '444' '445' '446' '447' '448'
 '449' '450' '451' '452' '453' '454' '455' '456' '457' '458' '459' '460'
 '461' '462' '463' '464' '465' '466' '467' '468' '469' '470' '471' '472'
 '473' '474' '475' '476' '477' '478' '479' '480' '481' '482' '483' '484'
 '485' '486' '487' '488' '489' '490' '491' '492' '493' '494' '495' '496'
 '497' '498' '499' '500' '501' '502' '503' '504' '505' '506' '507' '508'
 '509' '510' '511' '512' '513' '514' '515' '516' '517' '518' '519' '520'
 '521' '522' '523' '524' '525' '526' '527' '528' '529' '530' '531' '532'
 '533' '534' '535' '536' '537' '538' '539' '540' '541' '542' '543' '544'
 '545' '546' '547' '548' '549' '550' '551' '552' '553' '554' '555' '556'
 '557' '558' '559' '560' '561' '562' '563' '564' '565' '566' '567' '568'
 '569' '570' '571' '572' '573' '574' '575' '576' '577' '578' '579' '580'
 '581' '582' '583' '584' '585' '586' '587' '588' '589' '590' '591' '592'
 '593' '594' '595' '596' '597' '598' '599' '600' '601' '602' '603' '604'
 '605' '606' '607' '608' '609' '610' '611' '612' '613' '614' '615' '616'
 '617' '618' '619' '620' '621' '622' '623' '624' '625' '626' '627' '628'
 '629' '630' '631' '632' '633' '634' '635' '636' '637' '638' '639' '640'
 '641' '642' '643' '644' '645' '646' '647' '648' '649' '650' '651' '652'
 '653' '654' '655' '656' '657' '658' '659' '660' '661' '662' '663' '664'
 '665' '666' '667' '668' '669' '670' '671' '672' '673' '674' '675' '676'
 '677' '678' '679' '680' '681' '682' '683' '684' '685' '686' '687' '688'
 '689' '690' '691' '692' '693' '694' '695' '696' '697' '698' '699' '700'
 '701' '702' '703' '704' '705' '706' '707' '708' '709' '710' '711' '712'
 '713' '714' '715' '716' '717' '718' '719' '720' '721' '722' '723' '724'
 '725' '726' '727' '728' '729' '730' '731' '732' '733' '734' '735' '736'
 '737' '738' '739' '740' '741' '742' '743' '744' '745' '746' '747' '748'
 '749' '750' '751' '752' '753' '754' '755' '756' '757' '758' '759' '760'
 '761' '762' '763' '764' '765' '766' '767' '768' '769' '770' '771' '772'
 '773' '774' '775' '776' '777' '778' '779' '780' '781' '782' '783' '784'
 '785' '786' '787' '788' '789' '790' '791' '792' '793' '794' '795' '796'
 '797' '798' '799' '800']

<span style = "font-family: Verdana; font-size: 20px">

Mỗi Pokémon có một số ID riêng biệt duy nhất, các dạng tiến hoá cũng được xem như một Pokémon riêng biệt với số ID riêng.

<span style = "font-family: Verdana; font-size: 20px">

##### **Name**
</span>

In [87]:
describe_feature(data, 'Name')

- Type: object
- First rows:
0        Bulbasaur
1          Ivysaur
2         Venusaur
3    Mega Venusaur
4       Charmander
Name: Name, dtype: object
- Last rows:
795           Diancie
796      Mega Diancie
797    Hoopa Confined
798     Hoopa Unbound
799         Volcanion
Name: Name, dtype: object
- Number of missing values: 0
object
- Number of distinct values: 800
- Unique value counts:
Name
Bulbasaur                    1
Uxie                         1
Mega Gallade                 1
Probopass                    1
Dusknoir                     1
Froslass                     1
Rotom                        1
Heat Rotom                   1
Wash Rotom                   1
Frost Rotom                  1
Fan Rotom                    1
Mow Rotom                    1
Mesprit                      1
Ivysaur                      1
Azelf                        1
Dialga                       1
Palkia                       1
Heatran                      1
Regigigas                    1
Giratina Altered Forme       1
Giratina Origin Forme        1
Cresselia                    1
Phione                       1
Manaphy                      1
Gallade                      1
Porygon-Z                    1
Mamoswine                    1
Gliscor                      1
Drapion                      1
Croagunk                     1
Toxicroak                    1
Carnivine                    1
Finneon                      1
Lumineon                     1
Mantyke                      1
Snover                       1
Abomasnow                    1
Mega Abomasnow               1
Weavile                      1
Magnezone                    1
Lickilicky                   1
Rhyperior                    1
Tangrowth                    1
Electivire                   1
Magmortar                    1
Togekiss                     1
Yanmega                      1
Leafeon                      1
Glaceon                      1
Darkrai                      1
Shaymin Land Forme           1
Shaymin Sky Forme            1
Munna                        1
Pidove                       1
Tranquill                    1
Unfezant                     1
Blitzle                      1
Zebstrika                    1
Roggenrola                   1
Boldore                      1
Gigalith                     1
Woobat                       1
Swoobat                      1
Drilbur                      1
Excadrill                    1
Audino                       1
Mega Audino                  1
Timburr                      1
Gurdurr                      1
Conkeldurr                   1
Tympole                      1
Palpitoad                    1
Seismitoad                   1
Throh                        1
Musharna                     1
Simipour                     1
Arceus                       1
Panpour                      1
Victini                      1
Snivy                        1
Servine                      1
Serperior                    1
Tepig                        1
Pignite                      1
Emboar                       1
Oshawott                     1
Dewott                       1
Samurott                     1
Patrat                       1
Watchog                      1
Lillipup                     1
Herdier                      1
Stoutland                    1
Purrloin                     1
Liepard                      1
Pansage                      1
Simisage                     1
Pansear                      1
Simisear                     1
Skorupi                      1
Hippowdon                    1
Hippopotas                   1
Rayquaza                     1
Jirachi                      1
Deoxys Normal Forme          1
DeoxysAttack Forme           1
Deoxys Defense Forme         1
Deoxys Speed Forme           1
Turtwig                      1
Grotle                       1
Torterra                     1
Chimchar                     1
Monferno                     1
Infernape                    1
Piplup                       1
Prinplup                     1
Empoleon                     1
Starly                       1
Staravia                     1
Staraptor                    1
Bidoof                       1
Bibarel                      1
Kricketot                    1
Kricketune                   1
Mega Rayquaza                1
Primal Groudon               1
Luxio                        1
Groudon                      1
Huntail                      1
Gorebyss                     1
Relicanth                    1
Luvdisc                      1
Bagon                        1
Shelgon                      1
Salamence                    1
Mega Salamence               1
Beldum                       1
Metang                       1
Metagross                    1
Mega Metagross               1
Regirock                     1
Regice                       1
Registeel                    1
Latias                       1
Mega Latias                  1
Latios                       1
Mega Latios                  1
Kyogre                       1
Primal Kyogre                1
Shinx                        1
Luxray                       1
Mega Lucario                 1
Lopunny                      1
Mismagius                    1
Honchkrow                    1
Glameow                      1
Purugly                      1
Chingling                    1
Stunky                       1
Skuntank                     1
Bronzor                      1
Bronzong                     1
Bonsly                       1
Mime Jr.                     1
Happiny                      1
Chatot                       1
Spiritomb                    1
Gible                        1
Gabite                       1
Garchomp                     1
Mega Garchomp                1
Munchlax                     1
Riolu                        1
Lucario                      1
Mega Lopunny                 1
Buneary                      1
Budew                        1
Drifblim                     1
Roserade                     1
Cranidos                     1
Rampardos                    1
Shieldon                     1
Bastiodon                    1
Burmy                        1
Wormadam Plant Cloak         1
Wormadam Sandy Cloak         1
Wormadam Trash Cloak         1
Mothim                       1
Combee                       1
Vespiquen                    1
Pachirisu                    1
Buizel                       1
Floatzel                     1
Cherubi                      1
Cherrim                      1
Shellos                      1
Gastrodon                    1
Ambipom                      1
Drifloon                     1
Sawk                         1
Sewaddle                     1
Swadloon                     1
Greninja                     1
Diggersby                    1
Fletchling                   1
Fletchinder                  1
Talonflame                   1
Scatterbug                   1
Spewpa                       1
Vivillon                     1
Litleo                       1
Pyroar                       1
Flabébé                      1
Floette                      1
Florges                      1
Skiddo                       1
Gogoat                       1
Pancham                      1
Pangoro                      1
Furfrou                      1
Espurr                       1
Meowstic Male                1
Meowstic Female              1
Honedge                      1
Bunnelby                     1
Frogadier                    1
Aegislash Blade Forme        1
Froakie                      1
Tornadus Therian Forme       1
Thundurus Incarnate Forme    1
Thundurus Therian Forme      1
Reshiram                     1
Zekrom                       1
Landorus Incarnate Forme     1
Landorus Therian Forme       1
Kyurem                       1
Kyurem Black Kyurem          1
Kyurem White Kyurem          1
Keldeo Ordinary Forme        1
Keldeo Resolute Forme        1
Meloetta Aria Forme          1
Meloetta Pirouette Forme     1
Genesect                     1
Chespin                      1
Quilladin                    1
Chesnaught                   1
Fennekin                     1
Braixen                      1
Delphox                      1
Doublade                     1
Aegislash Shield Forme       1
Virizion                     1
Goodra                       1
Phantump                     1
Trevenant                    1
Pumpkaboo Average Size       1
Pumpkaboo Small Size         1
Pumpkaboo Large Size         1
Pumpkaboo Super Size         1
Gourgeist Average Size       1
Gourgeist Small Size         1
Gourgeist Large Size         1
Gourgeist Super Size         1
Bergmite                     1
Avalugg                      1
Noibat                       1
Noivern                      1
Xerneas                      1
Yveltal                      1
Zygarde Half Forme           1
Diancie                      1
Mega Diancie                 1
Hoopa Confined               1
Hoopa Unbound                1
Klefki                       1
Sliggoo                      1
Spritzee                     1
Goomy                        1
Aromatisse                   1
Swirlix                      1
Slurpuff                     1
Inkay                        1
Malamar                      1
Binacle                      1
Barbaracle                   1
Skrelp                       1
Dragalge                     1
Clauncher                    1
Clawitzer                    1
Helioptile                   1
Heliolisk                    1
Tyrunt                       1
Tyrantrum                    1
Amaura                       1
Aurorus                      1
Sylveon                      1
Hawlucha                     1
Dedenne                      1
Carbink                      1
Tornadus Incarnate Forme     1
Terrakion                    1
Leavanny                     1
Carracosta                   1
Archeops                     1
Trubbish                     1
Garbodor                     1
Zorua                        1
Zoroark                      1
Minccino                     1
Cinccino                     1
Gothita                      1
Gothorita                    1
Gothitelle                   1
Solosis                      1
Duosion                      1
Reuniclus                    1
Ducklett                     1
Swanna                       1
Vanillite                    1
Vanillish                    1
Vanilluxe                    1
Deerling                     1
Sawsbuck                     1
Emolga                       1
Archen                       1
Tirtouga                     1
Escavalier                   1
Cofagrigus                   1
Venipede                     1
Whirlipede                   1
Scolipede                    1
Cottonee                     1
Whimsicott                   1
Petilil                      1
Lilligant                    1
Basculin                     1
Sandile                      1
Krokorok                     1
Krookodile                   1
Darumaka                     1
Darmanitan Standard Mode     1
Darmanitan Zen Mode          1
Maractus                     1
Dwebble                      1
Crustle                      1
Scraggy                      1
Scrafty                      1
Sigilyph                     1
Yamask                       1
Karrablast                   1
Foongus                      1
Cobalion                     1
Cryogonal                    1
Accelgor                     1
Stunfisk                     1
Mienfoo                      1
Mienshao                     1
Druddigon                    1
Golett                       1
Golurk                       1
Pawniard                     1
Bisharp                      1
Bouffalant                   1
Rufflet                      1
Braviary                     1
Vullaby                      1
Mandibuzz                    1
Heatmor                      1
Durant                       1
Deino                        1
Zweilous                     1
Hydreigon                    1
Larvesta                     1
Volcarona                    1
Shelmet                      1
Beartic                      1
Amoonguss                    1
Cubchoo                      1
Frillish                     1
Jellicent                    1
Alomomola                    1
Joltik                       1
Galvantula                   1
Ferroseed                    1
Ferrothorn                   1
Klink                        1
Klang                        1
Klinklang                    1
Tynamo                       1
Eelektrik                    1
Eelektross                   1
Elgyem                       1
Beheeyem                     1
Litwick                      1
Lampent                      1
Chandelure                   1
Axew                         1
Fraxure                      1
Haxorus                      1
Clamperl                     1
Walrein                      1
Sealeo                       1
Horsea                       1
Goldeen                      1
Seaking                      1
Staryu                       1
Starmie                      1
Mr. Mime                     1
Scyther                      1
Jynx                         1
Electabuzz                   1
Magmar                       1
Pinsir                       1
Mega Pinsir                  1
Tauros                       1
Magikarp                     1
Gyarados                     1
Mega Gyarados                1
Lapras                       1
Ditto                        1
Eevee                        1
Vaporeon                     1
Jolteon                      1
Flareon                      1
Seadra                       1
Mega Kangaskhan              1
Omanyte                      1
Kangaskhan                   1
Mega Gengar                  1
Onix                         1
Drowzee                      1
Hypno                        1
Krabby                       1
Kingler                      1
Voltorb                      1
Electrode                    1
Exeggcute                    1
Exeggutor                    1
Cubone                       1
Marowak                      1
Hitmonlee                    1
Hitmonchan                   1
Lickitung                    1
Koffing                      1
Weezing                      1
Rhyhorn                      1
Rhydon                       1
Chansey                      1
Tangela                      1
Porygon                      1
Omastar                      1
Haunter                      1
Sentret                      1
Hoothoot                     1
Noctowl                      1
Ledyba                       1
Ledian                       1
Spinarak                     1
Ariados                      1
Crobat                       1
Chinchou                     1
Lanturn                      1
Pichu                        1
Cleffa                       1
Igglybuff                    1
Togepi                       1
Togetic                      1
Natu                         1
Xatu                         1
Mareep                       1
Flaaffy                      1
Ampharos                     1
Mega Ampharos                1
Bellossom                    1
Furret                       1
Feraligatr                   1
Kabuto                       1
Croconaw                     1
Kabutops                     1
Aerodactyl                   1
Mega Aerodactyl              1
Snorlax                      1
Articuno                     1
Zapdos                       1
Moltres                      1
Dratini                      1
Dragonair                    1
Dragonite                    1
Mewtwo                       1
Mega Mewtwo X                1
Mega Mewtwo Y                1
Mew                          1
Chikorita                    1
Bayleef                      1
Meganium                     1
Cyndaquil                    1
Quilava                      1
Typhlosion                   1
Totodile                     1
Gengar                       1
Gastly                       1
Azumarill                    1
Raticate                     1
Fearow                       1
Ekans                        1
Arbok                        1
Pikachu                      1
Raichu                       1
Sandshrew                    1
Sandslash                    1
Nidoran♀                     1
Nidorina                     1
Nidoqueen                    1
Nidoran♂                     1
Nidorino                     1
Nidoking                     1
Clefairy                     1
Clefable                     1
Vulpix                       1
Ninetales                    1
Jigglypuff                   1
Wigglytuff                   1
Zubat                        1
Golbat                       1
Spearow                      1
Rattata                      1
Gloom                        1
Mega Pidgeot                 1
Venusaur                     1
Mega Venusaur                1
Charmander                   1
Charmeleon                   1
Charizard                    1
Mega Charizard X             1
Mega Charizard Y             1
Squirtle                     1
Wartortle                    1
Blastoise                    1
Mega Blastoise               1
Caterpie                     1
Metapod                      1
Butterfree                   1
Weedle                       1
Kakuna                       1
Beedrill                     1
Mega Beedrill                1
Pidgey                       1
Pidgeotto                    1
Pidgeot                      1
Oddish                       1
Vileplume                    1
Cloyster                     1
Bellsprout                   1
Victreebel                   1
Tentacool                    1
Tentacruel                   1
Geodude                      1
Graveler                     1
Golem                        1
Ponyta                       1
Rapidash                     1
Slowpoke                     1
Slowbro                      1
Mega Slowbro                 1
Magnemite                    1
Magneton                     1
Farfetch'd                   1
Doduo                        1
Dodrio                       1
Seel                         1
Dewgong                      1
Grimer                       1
Muk                          1
Shellder                     1
Weepinbell                   1
Machamp                      1
Paras                        1
Machoke                      1
Parasect                     1
Venonat                      1
Venomoth                     1
Diglett                      1
Dugtrio                      1
Meowth                       1
Persian                      1
Psyduck                      1
Golduck                      1
Mankey                       1
Primeape                     1
Growlithe                    1
Arcanine                     1
Poliwag                      1
Poliwhirl                    1
Poliwrath                    1
Abra                         1
Kadabra                      1
Alakazam                     1
Mega Alakazam                1
Machop                       1
Marill                       1
Sudowoodo                    1
Spheal                       1
Delcatty                     1
Mega Sableye                 1
Mawile                       1
Mega Mawile                  1
Aron                         1
Lairon                       1
Aggron                       1
Mega Aggron                  1
Meditite                     1
Medicham                     1
Mega Medicham                1
Electrike                    1
Manectric                    1
Mega Manectric               1
Plusle                       1
Minun                        1
Volbeat                      1
Illumise                     1
Roselia                      1
Gulpin                       1
Swalot                       1
Carvanha                     1
Sableye                      1
Skitty                       1
Mega Sharpedo                1
Nosepass                     1
Pelipper                     1
Ralts                        1
Kirlia                       1
Gardevoir                    1

<span style = "font-family: Verdana; font-size: 20px">

Mỗi Pokémon cũng có tên riêng, một trong hai cột này đều có thể được dùng để làm primary key.

<span style = "font-family: Verdana; font-size: 20px">

##### **Type**
</span>

<span style = "font-family: Verdana; font-size: 20px">

Để thuận tiện cho việc phân tích, nếu Pokémon chỉ có một loại thì ta sẽ điền giá trị của `Type 1` vào `Type 2`.

In [88]:
describe_feature(data, 'Type 1')
describe_feature(data, 'Type 2')
data.loc[data['Type 2'] == "None", 'Type 2'] = data['Type 1']

- Type: object
- First rows:
0    Grass
1    Grass
2    Grass
3    Grass
4     Fire
Name: Type 1, dtype: object
- Last rows:
795       Rock
796       Rock
797    Psychic
798    Psychic
799       Fire
Name: Type 1, dtype: object
- Number of missing values: 0
object
- Number of distinct values: 18
- Unique value counts:
Type 1
Water       112
Normal       98
Grass        70
Bug          69
Psychic      57
Fire         52
Electric     44
Rock         44
Dragon       32
Ground       32
Ghost        32
Dark         31
Poison       28
Steel        27
Fighting     27
Ice          24
Fairy        17
Flying        4
Name: count, dtype: int64
- Unique values: ['Grass' 'Fire' 'Water' 'Bug' 'Normal' 'Poison' 'Electric' 'Ground'
 'Fairy' 'Fighting' 'Psychic' 'Rock' 'Ghost' 'Ice' 'Dragon' 'Dark' 'Steel'
 'Flying']
- Type: object
- First rows:
0    Poison
1    Poison
2    Poison
3    Poison
4      None
Name: Type 2, dtype: object
- Last rows:
795    Fairy
796    Fairy
797    Ghost
798     Dark
799    Water
Name: Type 2, dtype: object
- Number of missing values: 0
object
- Number of distinct values: 19
- Unique value counts:
Type 2
None        386
Flying       97
Ground       35
Poison       34
Psychic      33
Fighting     26
Grass        25
Fairy        23
Steel        22
Dark         20
Dragon       18
Ice          14
Rock         14
Water        14
Ghost        14
Fire         12
Electric      6
Normal        4
Bug           3
Name: count, dtype: int64
- Unique values: ['Poison' 'None' 'Flying' 'Dragon' 'Ground' 'Fairy' 'Grass' 'Fighting'
 'Psychic' 'Steel' 'Ice' 'Rock' 'Dark' 'Water' 'Electric' 'Fire' 'Ghost'
 'Bug' 'Normal']

<span style = "font-family: Verdana; font-size: 20px">

Thuộc tính của mỗi Pokémon được phân thành hai loại chính và phụ, tuy nhiên thứ tự của hai thuộc tính này không quan trọng.

<span style = "font-family: Verdana; font-size: 20px">

##### **Abilities**
</span>

In [89]:
for col in ['Abilities', 'HiddenAbility']:
    for abi in data[col]:
        print(abi)

['Overgrow']
['Overgrow']
['Overgrow']
['Thick Fat']
['Blaze']
['Blaze']
['Blaze']
['Tough Claws']
['Drought']
['Torrent']
['Torrent']
['Torrent']
['Mega Launcher']
['Shield Dust']
['Shed Skin']
['Compound Eyes']
['Shield Dust']
['Shed Skin']
['Swarm']
['Adaptability']
['Keen Eye', 'Tangled Feet']
['Keen Eye', 'Tangled Feet']
['Keen Eye', 'Tangled Feet']
['No Guard']
['Run Away', 'Guts']
['Run Away', 'Guts']
['Keen Eye']
['Keen Eye']
['Intimidate', 'Shed Skin']
['Intimidate', 'Shed Skin']
['Static']
['Static']
['Sand Veil']
['Sand Veil']
['Poison Point', 'Rivalry']
['Poison Point', 'Rivalry']
['Poison Point', 'Rivalry']
['Poison Point', 'Rivalry']
['Poison Point', 'Rivalry']
['Poison Point', 'Rivalry']
['Cute Charm', 'Magic Guard']
['Cute Charm', 'Magic Guard']
['Flash Fire']
['Flash Fire']
['Cute Charm', 'Competitive']
['Cute Charm', 'Competitive']
['Inner Focus']
['Inner Focus']
['Chlorophyll']
['Chlorophyll']
['Chlorophyll']
['Effect Spore', 'Dry Skin']
['Effect Spore', 'Dry Skin']
['Compound Eyes', 'Tinted Lens']
['Shield Dust', 'Tinted Lens']
['Sand Veil', 'Arena Trap']
['Sand Veil', 'Arena Trap']
['Pickup', 'Technician']
['Limber', 'Technician']
['Damp', 'Cloud Nine']
['Damp', 'Cloud Nine']
['Vital Spirit', 'Anger Point']
['Vital Spirit', 'Anger Point']
['Intimidate', 'Flash Fire']
['Intimidate', 'Flash Fire']
['Water Absorb', 'Damp']
['Water Absorb', 'Damp']
['Water Absorb', 'Damp']
['Synchronize', 'Inner Focus']
['Synchronize', 'Inner Focus']
['Synchronize', 'Inner Focus']
['Trace']
['Guts', 'No Guard']
['Guts', 'No Guard']
['Guts', 'No Guard']
['Chlorophyll']
['Chlorophyll']
['Chlorophyll']
['Clear Body', 'Liquid Ooze']
['Clear Body', 'Liquid Ooze']
['Rock Head', 'Sturdy']
['Rock Head', 'Sturdy']
['Rock Head', 'Sturdy']
['Run Away', 'Flash Fire']
['Run Away', 'Flash Fire']
['Oblivious', 'Own Tempo']
['Oblivious', 'Own Tempo']
['Shell Armor']
['Magnet Pull', 'Sturdy']
['Magnet Pull', 'Sturdy']
['Keen Eye', 'Inner Focus']
['Run Away', 'Early Bird']
['Run Away', 'Early Bird']
['Thick Fat', 'Hydration']
['Thick Fat', 'Hydration']
['Stench', 'Sticky Hold']
['Stench', 'Sticky Hold']
['Shell Armor', 'Skill Link']
['Shell Armor', 'Skill Link']
['Levitate']
['Levitate']
['Cursed Body']
['Shadow Tag']
['Rock Head', 'Sturdy']
['Insomnia', 'Forewarn']
['Insomnia', 'Forewarn']
['Hyper Cutter', 'Shell Armor']
['Hyper Cutter', 'Shell Armor']
['Soundproof', 'Static']
['Soundproof', 'Static']
['Chlorophyll']
['Chlorophyll']
['Rock Head', 'Lightning Rod']
['Rock Head', 'Lightning Rod']
['Limber', 'Reckless']
['Keen Eye', 'Iron Fist']
['Own Tempo', 'Oblivious']
['Levitate', 'Neutralizing Gas']
['Levitate', 'Neutralizing Gas']
['Lightning Rod', 'Rock Head']
['Lightning Rod', 'Rock Head']
['Natural Cure', 'Serene Grace']
['Chlorophyll', 'Leaf Guard']
['Early Bird', 'Scrappy']
['Parental Bond']
['Swift Swim', 'Sniper']
['Poison Point', 'Sniper']
['Swift Swim', 'Water Veil']
['Swift Swim', 'Water Veil']
['Illuminate', 'Natural Cure']
['Illuminate', 'Natural Cure']
['Soundproof', 'Filter']
['Swarm', 'Technician']
['Oblivious', 'Forewarn']
['Static']
['Flame Body']
['Hyper Cutter', 'Mold Breaker']
['Aerilate']
['Intimidate', 'Anger Point']
['Swift Swim']
['Intimidate']
['Mold Breaker']
['Water Absorb', 'Shell Armor']
['Limber']
['Run Away', 'Adaptability']
['Water Absorb']
['Volt Absorb']
['Flash Fire']
['Trace', 'Download']
['Swift Swim', 'Shell Armor']
['Swift Swim', 'Shell Armor']
['Swift Swim', 'Battle Armor']
['Swift Swim', 'Battle Armor']
['Rock Head', 'Pressure']
['Tough Claws']
['Immunity', 'Thick Fat']
['Pressure']
['Pressure']
['Pressure']
['Shed Skin']
['Shed Skin']
['Inner Focus']
['Pressure']
['Steadfast']
['Insomnia']
['Synchronize']
['Overgrow']
['Overgrow']
['Overgrow']
['Blaze']
['Blaze']
['Blaze']
['Torrent']
['Torrent']
['Torrent']
['Run Away', 'Keen Eye']
['Run Away', 'Keen Eye']
['Insomnia', 'Keen Eye']
['Insomnia', 'Keen Eye']
['Swarm', 'Early Bird']
['Swarm', 'Early Bird']
['Swarm', 'Insomnia']
['Swarm', 'Insomnia']
['Inner Focus']
['Volt Absorb', 'Illuminate']
['Volt Absorb', 'Illuminate']
['Static']
['Cute Charm', 'Magic Guard']
['Cute Charm', 'Competitive']
['Hustle', 'Serene Grace']
['Hustle', 'Serene Grace']
['Synchronize', 'Early Bird']
['Synchronize', 'Early Bird']
['Static']
['Static']
['Static']
['Mold Breaker']
['Chlorophyll']
['Thick Fat', 'Huge Power']
['Thick Fat', 'Huge Power']
['Sturdy', 'Rock Head']
['Water Absorb', 'Damp']
['Chlorophyll', 'Leaf Guard']
['Chlorophyll', 'Leaf Guard']
['Chlorophyll', 'Leaf Guard']
['Run Away', 'Pickup']
['Chlorophyll', 'Solar Power']
['Chlorophyll', 'Solar Power']
['Speed Boost', 'Compound Eyes']
['Damp', 'Water Absorb']
['Damp', 'Water Absorb']
['Synchronize']
['Synchronize']
['Insomnia', 'Super Luck']
['Oblivious', 'Own Tempo']
['Levitate']
['Levitate']
['Shadow Tag']
['Inner Focus', 'Early Bird']
['Sturdy']
['Sturdy']
['Serene Grace', 'Run Away']
['Hyper Cutter', 'Sand Veil']
['Rock Head', 'Sturdy']
['Sand Force']
['Intimidate', 'Run Away']
['Intimidate', 'Quick Feet']
['Poison Point', 'Swift Swim']
['Swarm', 'Technician']
['Technician']
['Sturdy', 'Gluttony']
['Swarm', 'Guts']
['Skill Link']
['Inner Focus', 'Keen Eye']
['Pickup', 'Quick Feet']
['Guts', 'Quick Feet']
['Magma Armor', 'Flame Body']
['Magma Armor', 'Flame Body']
['Oblivious', 'Snow Cloak']
['Oblivious', 'Snow Cloak']
['Hustle', 'Natural Cure']
['Hustle', 'Sniper']
['Suction Cups', 'Sniper']
['Vital Spirit', 'Hustle']
['Swift Swim', 'Water Absorb']
['Keen Eye', 'Sturdy']
['Early Bird', 'Flash Fire']
['Early Bird', 'Flash Fire']
['Solar Power']
['Swift Swim', 'Sniper']
['Pickup']
['Sturdy']
['Trace', 'Download']
['Intimidate', 'Frisk']
['Own Tempo', 'Technician']
['Guts', 'Steadfast']
['Intimidate', 'Technician']
['Oblivious', 'Forewarn']
['Static']
['Flame Body']
['Thick Fat', 'Scrappy']
['Natural Cure', 'Serene Grace']
['Pressure']
['Pressure']
['Pressure']
['Guts']
['Shed Skin']
['Sand Stream']
['Sand Stream']
['Pressure']
['Pressure']
['Natural Cure']
['Overgrow']
['Overgrow']
['Overgrow']
['Lightning Rod']
['Blaze']
['Blaze']
['Blaze']
['Speed Boost']
['Torrent']
['Torrent']
['Torrent']
['Swift Swim']
['Run Away', 'Quick Feet']
['Intimidate', 'Quick Feet']
['Pickup', 'Gluttony']
['Pickup', 'Gluttony']
['Shield Dust']
['Shed Skin']
['Swarm']
['Shed Skin']
['Shield Dust']
['Swift Swim', 'Rain Dish']
['Swift Swim', 'Rain Dish']
['Swift Swim', 'Rain Dish']
['Chlorophyll', 'Early Bird']
['Chlorophyll', 'Early Bird']
['Chlorophyll', 'Wind Rider']
['Guts']
['Guts']
['Keen Eye', 'Hydration']
['Keen Eye', 'Drizzle']
['Synchronize', 'Trace']
['Synchronize', 'Trace']
['Synchronize', 'Trace']
['Pixilate']
['Swift Swim']
['Intimidate']
['Effect Spore', 'Poison Heal']
['Effect Spore', 'Poison Heal']
['Truant']
['Vital Spirit']
['Truant']
['Compound Eyes']
['Speed Boost']
['Wonder Guard']
['Soundproof']
['Soundproof']
['Soundproof']
['Thick Fat', 'Guts']
['Thick Fat', 'Guts']
['Thick Fat', 'Huge Power']
['Sturdy', 'Magnet Pull']
['Cute Charm', 'Normalize']
['Cute Charm', 'Normalize']
['Keen Eye', 'Stall']
['Magic Bounce']
['Hyper Cutter', 'Intimidate']
['Huge Power']
['Sturdy', 'Rock Head']
['Sturdy', 'Rock Head']
['Sturdy', 'Rock Head']
['Filter']
['Pure Power']
['Pure Power']
['Pure Power']
['Static', 'Lightning Rod']
['Static', 'Lightning Rod']
['Intimidate']
['Plus']
['Minus']
['Illuminate', 'Swarm']
['Oblivious', 'Tinted Lens']
['Natural Cure', 'Poison Point']
['Liquid Ooze', 'Sticky Hold']
['Liquid Ooze', 'Sticky Hold']
['Rough Skin']
['Rough Skin']
['Strong Jaw']
['Water Veil', 'Oblivious']
['Water Veil', 'Oblivious']
['Oblivious', 'Simple']
['Magma Armor', 'Solid Rock']
['Sheer Force']
['White Smoke', 'Drought']
['Thick Fat', 'Own Tempo']
['Thick Fat', 'Own Tempo']
['Own Tempo', 'Tangled Feet']
['Hyper Cutter', 'Arena Trap']
['Levitate']
['Levitate']
['Sand Veil']
['Sand Veil']
['Natural Cure']
['Natural Cure']
['Pixilate']
['Immunity']
['Shed Skin']
['Levitate']
['Levitate']
['Oblivious', 'Anticipation']
['Oblivious', 'Anticipation']
['Hyper Cutter', 'Shell Armor']
['Hyper Cutter', 'Shell Armor']
['Levitate']
['Levitate']
['Suction Cups']
['Suction Cups']
['Battle Armor']
['Battle Armor']
['Swift Swim', 'Oblivious']
['Marvel Scale', 'Competitive']
['Forecast']
['Color Change']
['Insomnia', 'Frisk']
['Insomnia', 'Frisk']
['Prankster']
['Levitate']
['Pressure']
['Chlorophyll', 'Solar Power']
['Levitate']
['Pressure', 'Super Luck']
['Magic Bounce']
['Shadow Tag']
['Inner Focus', 'Ice Body']
['Inner Focus', 'Ice Body']
['Refrigerate']
['Thick Fat', 'Ice Body']
['Thick Fat', 'Ice Body']
['Thick Fat', 'Ice Body']
['Shell Armor']
['Swift Swim']
['Swift Swim']
['Swift Swim', 'Rock Head']
['Swift Swim']
['Rock Head']
['Rock Head']
['Intimidate']
['Aerilate']
['Clear Body']
['Clear Body']
['Clear Body']
['Tough Claws']
['Clear Body']
['Clear Body']
['Clear Body']
['Levitate']
['Levitate']
['Levitate']
['Levitate']
['Drizzle']
['Primordial Sea']
['Drought']
['Desolate Land']
['Air Lock']
['Delta Stream']
['Serene Grace']
['Pressure']
['Pressure']
['Pressure']
['Pressure']
['Overgrow']
['Overgrow']
['Overgrow']
['Blaze']
['Blaze']
['Blaze']
['Torrent']
['Torrent']
['Torrent']
['Keen Eye']
['Intimidate']
['Intimidate']
['Simple', 'Unaware']
['Simple', 'Unaware']
['Shed Skin']
['Swarm']
['Rivalry', 'Intimidate']
['Rivalry', 'Intimidate']
['Rivalry', 'Intimidate']
['Natural Cure', 'Poison Point']
['Natural Cure', 'Poison Point']
['Mold Breaker']
['Mold Breaker']
['Sturdy']
['Sturdy']
['Shed Skin']
['Anticipation']
['Anticipation']
['Anticipation']
['Swarm']
['Honey Gather']
['Pressure']
['Run Away', 'Pickup']
['Swift Swim']
['Swift Swim']
['Chlorophyll']
['Flower Gift']
['Sticky Hold', 'Storm Drain']
['Sticky Hold', 'Storm Drain']
['Technician', 'Pickup']
['Aftermath', 'Unburden']
['Aftermath', 'Unburden']
['Run Away', 'Klutz']
['Cute Charm', 'Klutz']
['Scrappy']
['Levitate']
['Insomnia', 'Super Luck']
['Limber', 'Own Tempo']
['Thick Fat', 'Own Tempo']
['Levitate']
['Stench', 'Aftermath']
['Stench', 'Aftermath']
['Levitate', 'Heatproof']
['Levitate', 'Heatproof']
['Sturdy', 'Rock Head']
['Soundproof', 'Filter']
['Natural Cure', 'Serene Grace']
['Keen Eye', 'Tangled Feet']
['Pressure']
['Sand Veil']
['Sand Veil']
['Sand Veil']
['Sand Force']
['Pickup', 'Thick Fat']
['Steadfast', 'Inner Focus']
['Steadfast', 'Inner Focus']
['Adaptability']
['Sand Stream']
['Sand Stream']
['Battle Armor', 'Sniper']
['Battle Armor', 'Sniper']
['Anticipation', 'Dry Skin']
['Anticipation', 'Dry Skin']
['Levitate']
['Swift Swim', 'Storm Drain']
['Swift Swim', 'Storm Drain']
['Swift Swim', 'Water Absorb']
['Snow Warning']
['Snow Warning']
['Snow Warning']
['Pressure']
['Magnet Pull', 'Sturdy']
['Own Tempo', 'Oblivious']
['Lightning Rod', 'Solid Rock']
['Chlorophyll', 'Leaf Guard']
['Motor Drive']
['Flame Body']
['Hustle', 'Serene Grace']
['Speed Boost', 'Tinted Lens']
['Leaf Guard']
['Snow Cloak']
['Hyper Cutter', 'Sand Veil']
['Oblivious', 'Snow Cloak']
['Adaptability', 'Download']
['Steadfast', 'Sharpness']
['Inner Focus']
['Sturdy', 'Magnet Pull']
['Pressure']
['Snow Cloak']
['Levitate']
['Levitate']
['Levitate']
['Levitate']
['Levitate']
['Levitate']
['Levitate']
['Levitate']
['Levitate']
['Pressure']
['Pressure']
['Flash Fire']
['Slow Start']
['Pressure']
['Levitate']
['Levitate']
['Hydration']
['Hydration']
['Bad Dreams']
['Natural Cure']
['Serene Grace']
['Multitype']
['Victory Star']
['Overgrow']
['Overgrow']
['Overgrow']
['Blaze']
['Blaze']
['Blaze']
['Torrent']
['Torrent']
['Torrent']
['Run Away', 'Keen Eye']
['Illuminate', 'Keen Eye']
['Vital Spirit', 'Pickup']
['Intimidate', 'Sand Rush']
['Intimidate', 'Sand Rush']
['Limber', 'Unburden']
['Limber', 'Unburden']
['Gluttony']
['Gluttony']
['Gluttony']
['Gluttony']
['Gluttony']
['Gluttony']
['Forewarn', 'Synchronize']
['Forewarn', 'Synchronize']
['Big Pecks', 'Super Luck']
['Big Pecks', 'Super Luck']
['Big Pecks', 'Super Luck']
['Lightning Rod', 'Motor Drive']
['Lightning Rod', 'Motor Drive']
['Sturdy', 'Weak Armor']
['Sturdy', 'Weak Armor']
['Sturdy', 'Sand Stream']
['Unaware', 'Klutz']
['Unaware', 'Klutz']
['Sand Rush', 'Sand Force']
['Sand Rush', 'Sand Force']
['Healer', 'Regenerator']
['Healer']
['Guts', 'Sheer Force']
['Guts', 'Sheer Force']
['Guts', 'Sheer Force']
['Swift Swim', 'Hydration']
['Swift Swim', 'Hydration']
['Swift Swim', 'Poison Touch']
['Guts', 'Inner Focus']
['Sturdy', 'Inner Focus']
['Swarm', 'Chlorophyll']
['Leaf Guard', 'Chlorophyll']
['Swarm', 'Chlorophyll']
['Poison Point', 'Swarm']
['Poison Point', 'Swarm']
['Poison Point', 'Swarm']
['Prankster', 'Infiltrator']
['Prankster', 'Infiltrator']
['Chlorophyll', 'Own Tempo']
['Chlorophyll', 'Own Tempo']
['Reckless', 'Adaptability']
['Intimidate', 'Moxie']
['Intimidate', 'Moxie']
['Intimidate', 'Moxie']
['Hustle']
['Sheer Force']
[]
['Water Absorb', 'Chlorophyll']
['Sturdy', 'Shell Armor']
['Sturdy', 'Shell Armor']
['Shed Skin', 'Moxie']
['Shed Skin', 'Moxie']
['Wonder Skin', 'Magic Guard']
['Mummy']
['Mummy']
['Solid Rock', 'Sturdy']
['Solid Rock', 'Sturdy']
['Defeatist']
['Defeatist']
['Stench', 'Sticky Hold']
['Stench', 'Weak Armor']
['Illusion']
['Illusion']
['Cute Charm', 'Technician']
['Cute Charm', 'Technician']
['Frisk', 'Competitive']
['Frisk', 'Competitive']
['Frisk', 'Competitive']
['Overcoat', 'Magic Guard']
['Overcoat', 'Magic Guard']
['Overcoat', 'Magic Guard']
['Keen Eye', 'Big Pecks']
['Keen Eye', 'Big Pecks']
['Ice Body', 'Snow Cloak']
['Ice Body', 'Snow Cloak']
['Ice Body', 'Snow Warning']
['Chlorophyll', 'Sap Sipper']
['Chlorophyll', 'Sap Sipper']
['Static']
['Swarm', 'Shed Skin']
['Swarm', 'Shell Armor']
['Effect Spore']
['Effect Spore']
['Water Absorb', 'Cursed Body']
['Water Absorb', 'Cursed Body']
['Healer', 'Hydration']
['Compound Eyes', 'Unnerve']
['Compound Eyes', 'Unnerve']
['Iron Barbs']
['Iron Barbs']
['Plus', 'Minus']
['Plus', 'Minus']
['Plus', 'Minus']
['Levitate']
['Levitate']
['Levitate']
['Telepathy', 'Synchronize']
['Telepathy', 'Synchronize']
['Flash Fire', 'Flame Body']
['Flash Fire', 'Flame Body']
['Flash Fire', 'Flame Body']
['Rivalry', 'Mold Breaker']
['Rivalry', 'Mold Breaker']
['Rivalry', 'Mold Breaker']
['Snow Cloak', 'Slush Rush']
['Snow Cloak', 'Slush Rush']
['Levitate']
['Hydration', 'Shell Armor']
['Hydration', 'Sticky Hold']
['Static', 'Limber']
['Inner Focus', 'Regenerator']
['Inner Focus', 'Regenerator']
['Rough Skin', 'Sheer Force']
['Iron Fist', 'Klutz']
['Iron Fist', 'Klutz']
['Defiant', 'Inner Focus']
['Defiant', 'Inner Focus']
['Reckless', 'Sap Sipper']
['Keen Eye', 'Sheer Force']
['Keen Eye', 'Sheer Force']
['Big Pecks', 'Overcoat']
['Big Pecks', 'Overcoat']
['Gluttony', 'Flash Fire']
['Swarm', 'Hustle']
['Hustle']
['Hustle']
['Levitate']
['Flame Body']
['Flame Body']
['Justified']
['Justified']
['Justified']
['Prankster']
['Regenerator']
['Prankster']
['Volt Absorb']
['Turboblaze']
['Teravolt']
['Sand Force']
['Intimidate']
['Pressure']
['Teravolt']
['Turboblaze']
['Justified']
['Justified']
['Serene Grace']
['Serene Grace']
['Download']
['Overgrow']
['Overgrow']
['Overgrow']
['Blaze']
['Blaze']
['Blaze']
['Torrent']
['Torrent']
['Torrent']
['Pickup', 'Cheek Pouch']
['Pickup', 'Cheek Pouch']
['Big Pecks']
['Flame Body']
['Flame Body']
['Shield Dust', 'Compound Eyes']
['Shed Skin']
['Shield Dust', 'Compound Eyes']
['Rivalry', 'Unnerve']
['Rivalry', 'Unnerve']
['Flower Veil']
['Flower Veil']
['Flower Veil']
['Sap Sipper']
['Sap Sipper']
['Iron Fist', 'Mold Breaker']
['Iron Fist', 'Mold Breaker']
['Fur Coat']
['Keen Eye', 'Infiltrator']
['Keen Eye', 'Infiltrator']
['Keen Eye', 'Infiltrator']
['No Guard']
['No Guard']
['Stance Change']
['Stance Change']
['Healer']
['Healer']
['Sweet Veil']
['Sweet Veil']
['Contrary', 'Suction Cups']
['Contrary', 'Suction Cups']
['Tough Claws', 'Sniper']
['Tough Claws', 'Sniper']
['Poison Point', 'Poison Touch']
['Poison Point', 'Poison Touch']
['Mega Launcher']
['Mega Launcher']
['Dry Skin', 'Sand Veil']
['Dry Skin', 'Sand Veil']
['Strong Jaw']
['Strong Jaw']
['Refrigerate']
['Refrigerate']
['Cute Charm']
['Limber', 'Unburden']
['Cheek Pouch', 'Pickup']
['Clear Body']
['Sap Sipper', 'Hydration']
['Sap Sipper', 'Hydration']
['Sap Sipper', 'Hydration']
['Prankster']
['Natural Cure', 'Frisk']
['Natural Cure', 'Frisk']
['Frisk']
['Frisk']
['Frisk']
['Frisk']
['Frisk']
['Frisk']
['Frisk']
['Frisk']
['Own Tempo', 'Ice Body']
['Own Tempo', 'Ice Body']
['Frisk', 'Infiltrator']
['Frisk', 'Infiltrator']
['Fairy Aura']
['Dark Aura']
['Aura Break', 'Power Construct']
['Clear Body']
['Magic Bounce']
['Magician']
['Magician']
['Water Absorb']
['Chlorophyll']
['Chlorophyll']
['Chlorophyll']
[]
['Solar Power']
['Solar Power']
['Solar Power']
[]
[]
['Rain Dish']
['Rain Dish']
['Rain Dish']
[]
['Run Away']
[]
['Tinted Lens']
['Run Away']
[]
['Sniper']
[]
['Big Pecks']
['Big Pecks']
['Big Pecks']
[]
['Hustle']
['Hustle']
['Sniper']
['Sniper']
['Unnerve']
['Unnerve']
['Lightning Rod']
['Lightning Rod']
['Sand Rush']
['Sand Rush']
['Hustle']
['Hustle']
['Sheer Force']
['Hustle']
['Hustle']
['Sheer Force']
['Friend Guard']
['Unaware']
['Drought']
['Drought']
['Friend Guard']
['Frisk']
['Infiltrator']
['Infiltrator']
['Run Away']
['Stench']
['Effect Spore']
['Damp']
['Damp']
['Run Away']
['Wonder Skin']
['Sand Force']
['Sand Force']
['Unnerve']
['Unnerve']
['Swift Swim']
['Swift Swim']
['Defiant']
['Defiant']
['Justified']
['Justified']
['Swift Swim']
['Swift Swim']
['Swift Swim']
['Magic Guard']
['Magic Guard']
['Magic Guard']
[]
['Steadfast']
['Steadfast']
['Steadfast']
['Gluttony']
['Gluttony']
['Gluttony']
['Rain Dish']
['Rain Dish']
['Sand Veil']
['Sand Veil']
['Sand Veil']
['Flame Body']
['Flame Body']
['Regenerator']
['Regenerator']
[]
['Analytic']
['Analytic']
['Defiant']
['Tangled Feet']
['Tangled Feet']
['Ice Body']
['Ice Body']
['Poison Touch']
['Poison Touch']
['Overcoat']
['Overcoat']
[]
[]
[]
[]
['Weak Armor']
['Inner Focus']
['Inner Focus']
['Sheer Force']
['Sheer Force']
['Aftermath']
['Aftermath']
['Harvest']
['Harvest']
['Battle Armor']
['Battle Armor']
['Unburden']
['Inner Focus']
['Cloud Nine']
['Stench']
['Stench']
['Reckless']
['Reckless']
['Healer']
['Regenerator']
['Inner Focus']
[]
['Damp']
['Damp']
['Lightning Rod']
['Lightning Rod']
['Analytic']
['Analytic']
['Technician']
['Steadfast']
['Dry Skin']
['Vital Spirit']
['Vital Spirit']
['Moxie']
[]
['Sheer Force']
['Rattled']
['Moxie']
[]
['Hydration']
['Imposter']
['Anticipation']
['Hydration']
['Quick Feet']
['Guts']
['Analytic']
['Weak Armor']
['Weak Armor']
['Weak Armor']
['Weak Armor']
['Unnerve']
[]
['Gluttony']
['Snow Cloak']
['Static']
['Flame Body']
['Marvel Scale']
['Marvel Scale']
['Multiscale']
['Unnerve']
[]
[]
[]
['Leaf Guard']
['Leaf Guard']
['Leaf Guard']
['Flash Fire']
['Flash Fire']
['Flash Fire']
['Sheer Force']
['Sheer Force']
['Sheer Force']
['Frisk']
['Frisk']
['Tinted Lens']
['Tinted Lens']
['Rattled']
['Iron Fist']
['Sniper']
['Sniper']
['Infiltrator']
['Water Absorb']
['Water Absorb']
['Lightning Rod']
['Friend Guard']
['Friend Guard']
['Super Luck']
['Super Luck']
['Magic Bounce']
['Magic Bounce']
['Plus']
['Plus']
['Plus']
[]
['Healer']
['Sap Sipper']
['Sap Sipper']
['Rattled']
['Drizzle']
['Infiltrator']
['Infiltrator']
['Infiltrator']
['Skill Link']
['Early Bird']
['Early Bird']
['Frisk']
['Unaware']
['Unaware']
['Magic Bounce']
['Inner Focus']
['Prankster']
['Regenerator']
[]
[]
['Telepathy']
['Sap Sipper']
['Overcoat']
['Overcoat']
['Rattled']
['Immunity']
['Sheer Force']
[]
['Rattled']
['Rattled']
['Intimidate']
['Light Metal']
[]
['Contrary']
['Moxie']
[]
['Pickpocket']
['Honey Gather']
['Unnerve']
['Weak Armor']
['Weak Armor']
['Thick Fat']
['Thick Fat']
['Regenerator']
['Moody']
['Moody']
['Insomnia']
['Water Veil']
['Weak Armor']
['Unnerve']
['Unnerve']
[]
['Damp']
['Sand Veil']
['Sand Veil']
['Analytic']
['Sap Sipper']
['Moody']
['Vital Spirit']
['Steadfast']
['Hydration']
['Vital Spirit']
['Vital Spirit']
['Sap Sipper']
['Healer']
['Inner Focus']
['Inner Focus']
['Inner Focus']
['Sand Veil']
[]
['Unnerve']
[]
['Multiscale']

<span style = "font-family: Verdana; font-size: 20px">

Thuộc tính này có chứa một hoặc nhiều thành phần, bao gồm cả các ký tự đặc biệt, cần phải được làm sạch và tách riêng.

In [90]:
data['Abilities'] = remove_first_last_letter(data['Abilities'], ',')
data['HiddenAbility'] = remove_first_last_letter(data['HiddenAbility'], ',')
data['Ability 1'] = get_first_element(data['Abilities'])
data['Ability 2'] = get_second_element(data['Abilities'])
data['HiddenAbility'] = get_first_element(data['HiddenAbility'])
data = data.drop('Abilities', axis=1)

In [91]:
describe_feature(data, 'Ability 1')

- Type: object
- First rows:
0     Overgrow
1     Overgrow
2     Overgrow
3    Thick Fat
4        Blaze
Name: Ability 1, dtype: object
- Last rows:
795      Clear Body
796    Magic Bounce
797        Magician
798        Magician
799    Water Absorb
Name: Ability 1, dtype: object
- Number of missing values: 0
object
- Number of distinct values: 149
- Unique value counts:
Ability 1
Levitate          39
Swift Swim        28
Chlorophyll       25
Pressure          23
Intimidate        22
Keen Eye          20
Sturdy            19
Overgrow          18
Torrent           18
Blaze             18
Swarm             16
Thick Fat         15
Run Away          14
Shed Skin         13
Poison Point      13
Frisk             13
Natural Cure      12
Cute Charm        12
Static            12
Oblivious         12
Guts              12
Inner Focus       11
Synchronize       11
Clear Body        10
Water Absorb      10
Rock Head         10
Hyper Cutter       9
Insomnia           9
Sand Veil          9
Pickup             8
Hustle             8
Rivalry            8
Soundproof         7
Gluttony           7
Flame Body         7
Limber             7
Flash Fire         7
Shield Dust        7
Big Pecks          6
Prankster          6
Effect Spore       6
Lightning Rod      6
Own Tempo          6
Stench             6
Anticipation       5
Vital Spirit       5
Tough Claws        5
Justified          5
Compound Eyes      5
Healer             5
Serene Grace       5
Sap Sipper         5
Iron Fist          4
Shell Armor        4
Plus               4
Battle Armor       4
Hydration          4
Snow Cloak         4
Speed Boost        4
Sand Stream        4
Damp               4
Illuminate         4
Steadfast          4
Volt Absorb        4
Mold Breaker       4
Adaptability       3
Ice Body           3
Trace              3
Shadow Tag         3
Early Bird         3
Refrigerate        3
Snow Warning       3
Mega Launcher      3
Strong Jaw         3
Rough Skin         3
Overcoat           3
Suction Cups       3
Pure Power         3
Sand Force         3
Magic Bounce       3
No Guard           3
Flower Veil        3
Magnet Pull        3
Magma Armor        3
Sweet Veil         2
Contrary           2
Teravolt           2
Dry Skin           2
Forewarn           2
Unaware            2
Sand Rush          2
Stance Change      2
Reckless           2
Iron Barbs         2
Turboblaze         2
Mummy              2
Solid Rock         2
Defeatist          2
Illusion           2
Defiant            2
Telepathy          2
Leaf Guard         2
Magician           2
Water Veil         2
Drought            2
Sheer Force        2
Truant             2
Pixilate           2
Technician         2
Immunity           2
Simple             2
Aerilate           2
Sticky Hold        2
Aftermath          2
Liquid Ooze        2
Cursed Body        1
Cheek Pouch        1
Parental Bond      1
Huge Power         1
Fur Coat           1
Fairy Aura         1
Dark Aura          1
Download           1
Skill Link         1
Solar Power        1
Regenerator        1
Aura Break         1
Wonder Guard       1
Scrappy            1
Minus              1
Motor Drive        1
Slow Start         1
Flower Gift        1
Bad Dreams         1
Multitype          1
Victory Star       1
Honey Gather       1
Delta Stream       1
Air Lock           1
Desolate Land      1
Primordial Sea     1
Drizzle            1
                   1
Wonder Skin        1
Color Change       1
Forecast           1
Marvel Scale       1
White Smoke        1
Filter             1
Name: count, dtype: int64
- Unique values: ['Overgrow' 'Thick Fat' 'Blaze' 'Tough Claws' 'Drought' 'Torrent'
 'Mega Launcher' 'Shield Dust' 'Shed Skin' 'Compound Eyes' 'Swarm'
 'Adaptability' 'Keen Eye' 'No Guard' 'Run Away' 'Intimidate' 'Static'
 'Sand Veil' 'Poison Point' 'Cute Charm' 'Flash Fire' 'Inner Focus'
 'Chlorophyll' 'Effect Spore' 'Pickup' 'Limber' 'Damp' 'Vital Spirit'
 'Water Absorb' 'Synchronize' 'Trace' 'Guts' 'Clear Body' 'Rock Head'
 'Oblivious' 'Shell Armor' 'Magnet Pull' 'Stench' 'Levitate' 'Cursed Body'
 'Shadow Tag' 'Insomnia' 'Hyper Cutter' 'Soundproof' 'Own Tempo'
 'Lightning Rod' 'Natural Cure' 'Early Bird' 'Parental Bond' 'Swift Swim'
 'Illuminate' 'Flame Body' 'Aerilate' 'Mold Breaker' 'Volt Absorb'
 'Immunity' 'Pressure' 'Steadfast' 'Hustle' 'Sturdy' 'Speed Boost'
 'Serene Grace' 'Sand Force' 'Technician' 'Skill Link' 'Magma Armor'
 'Suction Cups' 'Solar Power' 'Sand Stream' 'Pixilate' 'Truant'
 'Wonder Guard' 'Magic Bounce' 'Huge Power' 'Filter' 'Pure Power' 'Plus'
 'Minus' 'Liquid Ooze' 'Rough Skin' 'Strong Jaw' 'Water Veil'
 'Sheer Force' 'White Smoke' 'Battle Armor' 'Marvel Scale' 'Forecast'
 'Color Change' 'Prankster' 'Refrigerate' 'Drizzle' 'Primordial Sea'
 'Desolate Land' 'Air Lock' 'Delta Stream' 'Simple' 'Rivalry'
 'Anticipation' 'Honey Gather' 'Flower Gift' 'Sticky Hold' 'Aftermath'
 'Scrappy' 'Snow Warning' 'Motor Drive' 'Leaf Guard' 'Snow Cloak'
 'Slow Start' 'Hydration' 'Bad Dreams' 'Multitype' 'Victory Star'
 'Gluttony' 'Forewarn' 'Big Pecks' 'Unaware' 'Sand Rush' 'Healer'
 'Reckless' '' 'Wonder Skin' 'Mummy' 'Solid Rock' 'Defeatist' 'Illusion'
 'Frisk' 'Overcoat' 'Ice Body' 'Iron Barbs' 'Telepathy' 'Iron Fist'
 'Defiant' 'Justified' 'Regenerator' 'Turboblaze' 'Teravolt' 'Download'
 'Flower Veil' 'Sap Sipper' 'Fur Coat' 'Stance Change' 'Sweet Veil'
 'Contrary' 'Dry Skin' 'Cheek Pouch' 'Fairy Aura' 'Dark Aura' 'Aura Break'
 'Magician']

In [92]:
describe_feature(data, 'Ability 2')

- Type: object
- First rows:
0    None
1    None
2    None
3    None
4    None
Name: Ability 2, dtype: object
- Last rows:
795    None
796    None
797    None
798    None
799    None
Name: Ability 2, dtype: object
- Number of missing values: 0
object
- Number of distinct values: 112
- Unique value counts:
Ability 2
None                392
Shell Armor          11
Sturdy               11
Inner Focus          10
Sniper                9
Hydration             9
Own Tempo             9
Early Bird            9
Technician            8
Rock Head             8
Infiltrator           7
Keen Eye              7
Flash Fire            7
Ice Body              7
Competitive           7
Magic Guard           7
Super Luck            6
Serene Grace          6
Sticky Hold           6
Rivalry               6
Mold Breaker          6
Sheer Force           6
Klutz                 6
Quick Feet            5
Tangled Feet          5
Moxie                 5
Pickup                5
Frisk                 5
Snow Cloak            5
Flame Body            5
Oblivious             5
Unburden              5
Guts                  5
Leaf Guard            5
Water Absorb          4
Storm Drain           4
Synchronize           4
Intimidate            4
Unnerve               4
Chlorophyll           4
Swarm                 4
Sand Veil             4
Dry Skin              4
Damp                  4
Forewarn              4
Lightning Rod         4
Tinted Lens           4
Download              3
No Guard              3
Poison Point          3
Anger Point           3
Trace                 3
Weak Armor            3
Rain Dish             3
Regenerator           3
Arena Trap            3
Gluttony              3
Poison Touch          3
Natural Cure          3
Compound Eyes         3
Solar Power           3
Shed Skin             3
Huge Power            3
Sap Sipper            3
Minus                 3
Big Pecks             2
Aftermath             2
Liquid Ooze           2
Suction Cups          2
Cheek Pouch           2
Overcoat              2
Slush Rush            2
Motor Drive           2
Heatproof             2
Sand Rush             2
Sand Force            2
Cloud Nine            2
Skill Link            2
Cursed Body           2
Unaware               2
Solid Rock            2
Anticipation          2
Scrappy               2
Run Away              2
Water Veil            2
Hustle                2
Filter                2
Illuminate            2
Insomnia              2
Poison Heal           2
Magnet Pull           2
Normalize             2
Adaptability          2
Thick Fat             2
Static                2
Battle Armor          2
Neutralizing Gas      2
Limber                1
Pressure              1
Snow Warning          1
Reckless              1
Swift Swim            1
Iron Fist             1
Drought               1
Steadfast             1
Wind Rider            1
Sand Stream           1
Drizzle               1
Sharpness             1
Stall                 1
Simple                1
Power Construct       1
Name: count, dtype: int64
- Unique values: ['None' 'Tangled Feet' 'Guts' 'Shed Skin' 'Rivalry' 'Magic Guard'
 'Competitive' 'Dry Skin' 'Tinted Lens' 'Arena Trap' 'Technician'
 'Cloud Nine' 'Anger Point' 'Flash Fire' 'Damp' 'Inner Focus' 'No Guard'
 'Liquid Ooze' 'Sturdy' 'Own Tempo' 'Early Bird' 'Hydration' 'Sticky Hold'
 'Skill Link' 'Forewarn' 'Shell Armor' 'Static' 'Lightning Rod' 'Reckless'
 'Iron Fist' 'Oblivious' 'Neutralizing Gas' 'Rock Head' 'Serene Grace'
 'Leaf Guard' 'Scrappy' 'Sniper' 'Water Veil' 'Natural Cure' 'Filter'
 'Mold Breaker' 'Adaptability' 'Download' 'Battle Armor' 'Pressure'
 'Thick Fat' 'Keen Eye' 'Insomnia' 'Illuminate' 'Huge Power' 'Pickup'
 'Solar Power' 'Compound Eyes' 'Water Absorb' 'Super Luck' 'Run Away'
 'Sand Veil' 'Quick Feet' 'Swift Swim' 'Gluttony' 'Flame Body'
 'Snow Cloak' 'Hustle' 'Frisk' 'Steadfast' 'Rain Dish' 'Wind Rider'
 'Drizzle' 'Trace' 'Poison Heal' 'Magnet Pull' 'Normalize' 'Stall'
 'Intimidate' 'Swarm' 'Poison Point' 'Simple' 'Solid Rock' 'Drought'
 'Anticipation' 'Ice Body' 'Unaware' 'Storm Drain' 'Unburden' 'Klutz'
 'Aftermath' 'Heatproof' 'Sharpness' 'Sand Rush' 'Synchronize'
 'Motor Drive' 'Weak Armor' 'Sand Stream' 'Sand Force' 'Regenerator'
 'Sheer Force' 'Poison Touch' 'Chlorophyll' 'Infiltrator' 'Moxie'
 'Big Pecks' 'Snow Warning' 'Sap Sipper' 'Cursed Body' 'Unnerve' 'Minus'
 'Slush Rush' 'Limber' 'Overcoat' 'Cheek Pouch' 'Suction Cups'
 'Power Construct']

In [93]:
print(data['Ability 1'].unique())
print(data['Ability 2'].unique())
print(data['HiddenAbility'].unique())

['Overgrow' 'Thick Fat' 'Blaze' 'Tough Claws' 'Drought' 'Torrent'
 'Mega Launcher' 'Shield Dust' 'Shed Skin' 'Compound Eyes' 'Swarm'
 'Adaptability' 'Keen Eye' 'No Guard' 'Run Away' 'Intimidate' 'Static'
 'Sand Veil' 'Poison Point' 'Cute Charm' 'Flash Fire' 'Inner Focus'
 'Chlorophyll' 'Effect Spore' 'Pickup' 'Limber' 'Damp' 'Vital Spirit'
 'Water Absorb' 'Synchronize' 'Trace' 'Guts' 'Clear Body' 'Rock Head'
 'Oblivious' 'Shell Armor' 'Magnet Pull' 'Stench' 'Levitate' 'Cursed Body'
 'Shadow Tag' 'Insomnia' 'Hyper Cutter' 'Soundproof' 'Own Tempo'
 'Lightning Rod' 'Natural Cure' 'Early Bird' 'Parental Bond' 'Swift Swim'
 'Illuminate' 'Flame Body' 'Aerilate' 'Mold Breaker' 'Volt Absorb'
 'Immunity' 'Pressure' 'Steadfast' 'Hustle' 'Sturdy' 'Speed Boost'
 'Serene Grace' 'Sand Force' 'Technician' 'Skill Link' 'Magma Armor'
 'Suction Cups' 'Solar Power' 'Sand Stream' 'Pixilate' 'Truant'
 'Wonder Guard' 'Magic Bounce' 'Huge Power' 'Filter' 'Pure Power' 'Plus'
 'Minus' 'Liquid Ooze' 'Rough Skin' 'Strong Jaw' 'Water Veil'
 'Sheer Force' 'White Smoke' 'Battle Armor' 'Marvel Scale' 'Forecast'
 'Color Change' 'Prankster' 'Refrigerate' 'Drizzle' 'Primordial Sea'
 'Desolate Land' 'Air Lock' 'Delta Stream' 'Simple' 'Rivalry'
 'Anticipation' 'Honey Gather' 'Flower Gift' 'Sticky Hold' 'Aftermath'
 'Scrappy' 'Snow Warning' 'Motor Drive' 'Leaf Guard' 'Snow Cloak'
 'Slow Start' 'Hydration' 'Bad Dreams' 'Multitype' 'Victory Star'
 'Gluttony' 'Forewarn' 'Big Pecks' 'Unaware' 'Sand Rush' 'Healer'
 'Reckless' '' 'Wonder Skin' 'Mummy' 'Solid Rock' 'Defeatist' 'Illusion'
 'Frisk' 'Overcoat' 'Ice Body' 'Iron Barbs' 'Telepathy' 'Iron Fist'
 'Defiant' 'Justified' 'Regenerator' 'Turboblaze' 'Teravolt' 'Download'
 'Flower Veil' 'Sap Sipper' 'Fur Coat' 'Stance Change' 'Sweet Veil'
 'Contrary' 'Dry Skin' 'Cheek Pouch' 'Fairy Aura' 'Dark Aura' 'Aura Break'
 'Magician']
['None' 'Tangled Feet' 'Guts' 'Shed Skin' 'Rivalry' 'Magic Guard'
 'Competitive' 'Dry Skin' 'Tinted Lens' 'Arena Trap' 'Technician'
 'Cloud Nine' 'Anger Point' 'Flash Fire' 'Damp' 'Inner Focus' 'No Guard'
 'Liquid Ooze' 'Sturdy' 'Own Tempo' 'Early Bird' 'Hydration' 'Sticky Hold'
 'Skill Link' 'Forewarn' 'Shell Armor' 'Static' 'Lightning Rod' 'Reckless'
 'Iron Fist' 'Oblivious' 'Neutralizing Gas' 'Rock Head' 'Serene Grace'
 'Leaf Guard' 'Scrappy' 'Sniper' 'Water Veil' 'Natural Cure' 'Filter'
 'Mold Breaker' 'Adaptability' 'Download' 'Battle Armor' 'Pressure'
 'Thick Fat' 'Keen Eye' 'Insomnia' 'Illuminate' 'Huge Power' 'Pickup'
 'Solar Power' 'Compound Eyes' 'Water Absorb' 'Super Luck' 'Run Away'
 'Sand Veil' 'Quick Feet' 'Swift Swim' 'Gluttony' 'Flame Body'
 'Snow Cloak' 'Hustle' 'Frisk' 'Steadfast' 'Rain Dish' 'Wind Rider'
 'Drizzle' 'Trace' 'Poison Heal' 'Magnet Pull' 'Normalize' 'Stall'
 'Intimidate' 'Swarm' 'Poison Point' 'Simple' 'Solid Rock' 'Drought'
 'Anticipation' 'Ice Body' 'Unaware' 'Storm Drain' 'Unburden' 'Klutz'
 'Aftermath' 'Heatproof' 'Sharpness' 'Sand Rush' 'Synchronize'
 'Motor Drive' 'Weak Armor' 'Sand Stream' 'Sand Force' 'Regenerator'
 'Sheer Force' 'Poison Touch' 'Chlorophyll' 'Infiltrator' 'Moxie'
 'Big Pecks' 'Snow Warning' 'Sap Sipper' 'Cursed Body' 'Unnerve' 'Minus'
 'Slush Rush' 'Limber' 'Overcoat' 'Cheek Pouch' 'Suction Cups'
 'Power Construct']
['Chlorophyll' '' 'Solar Power' 'Rain Dish' 'Run Away' 'Tinted Lens'
 'Sniper' 'Big Pecks' 'Hustle' 'Unnerve' 'Lightning Rod' 'Sand Rush'
 'Sheer Force' 'Friend Guard' 'Unaware' 'Drought' 'Frisk' 'Infiltrator'
 'Stench' 'Effect Spore' 'Damp' 'Wonder Skin' 'Sand Force' 'Swift Swim'
 'Defiant' 'Justified' 'Magic Guard' 'Steadfast' 'Gluttony' 'Sand Veil'
 'Flame Body' 'Regenerator' 'Analytic' 'Tangled Feet' 'Ice Body'
 'Poison Touch' 'Overcoat' 'Weak Armor' 'Inner Focus' 'Aftermath'
 'Harvest' 'Battle Armor' 'Unburden' 'Cloud Nine' 'Reckless' 'Healer'
 'Technician' 'Dry Skin' 'Vital Spirit' 'Moxie' 'Rattled' 'Hydration'
 'Imposter' 'Anticipation' 'Quick Feet' 'Guts' 'Snow Cloak' 'Static'
 'Marvel Scale' 'Multiscale' 'Leaf Guard' 'Flash Fire' 'Iron Fist'
 'Water Absorb' 'Super Luck' 'Magic Bounce' 'Plus' 'Sap Sipper' 'Drizzle'
 'Skill Link' 'Early Bird' 'Prankster' 'Telepathy' 'Immunity' 'Intimidate'
 'Light Metal' 'Contrary' 'Pickpocket' 'Honey Gather' 'Thick Fat' 'Moody'
 'Insomnia' 'Water Veil' 'Speed Boost' 'Rivalry' 'Compound Eyes'
 'Own Tempo' 'Scrappy' 'Heavy Metal' 'Minus' 'Volt Absorb' 'Pressure'
 'Anger Point' 'Shell Armor' 'Toxic Boost' 'Adaptability' 'Storm Drain'
 'Cute Charm' 'Protean' 'Cursed Body' 'Oblivious' 'Sturdy' 'Competitive'
 'Soundproof' 'Flare Boost' 'Limber' 'Keen Eye' 'Rough Skin' 'Poison Heal'
 'Overgrow' 'Blaze' 'Torrent' 'Simple' 'Mold Breaker' 'Klutz' 'Zen Mode'
 'Shadow Tag' 'Serene Grace' 'Motor Drive' 'No Guard' 'Swarm' 'Clear Body'
 'White Smoke' 'Truant' 'Bulletproof' 'Magician' 'Huge Power' 'Gale Wings'
 'Symbiosis' 'Grass Pelt' 'Aroma Veil' 'Rock Head' 'Snow Warning'
 'Pixilate' 'Gooey']

<span style = "font-family: Verdana; font-size: 20px">

Thay thế các ô bị trống bằng `None`

In [94]:
data['Ability 1'] = data['Ability 1'].replace(['nan', ''], ['None', 'None'])
data['Ability 2'] = data['Ability 2'].replace(['nan', ''], ['None', 'None'])
data['HiddenAbility'] = data['HiddenAbility'].replace(['nan', ''], ['None', 'None'])
data['Ability 1'] = data['Ability 1'].fillna('None')
data['Ability 2'] = data['Ability 2'].fillna('None')
data['HiddenAbility'] = data['HiddenAbility'].fillna('None')

In [95]:
describe_feature(data, 'HiddenAbility')

- Type: object
- First rows:
0    Chlorophyll
1    Chlorophyll
2    Chlorophyll
3           None
4    Solar Power
Name: HiddenAbility, dtype: object
- Last rows:
795    None
796    None
797    None
798    None
799    None
Name: HiddenAbility, dtype: object
- Number of missing values: 0
object
- Number of distinct values: 135
- Unique value counts:
HiddenAbility
None             155
Sheer Force       17
Unnerve           15
Weak Armor        15
Telepathy         14
Infiltrator       14
Overcoat          14
Regenerator       13
Analytic          12
Rattled           11
Sand Force        11
Swift Swim        10
Damp              10
Hydration          9
Gluttony           9
Inner Focus        9
Insomnia           9
Moxie              8
Sap Sipper         8
Reckless           8
Speed Boost        8
Frisk              8
Rain Dish          8
Friend Guard       8
Run Away           8
Scrappy            8
Hustle             8
Vital Spirit       7
Mold Breaker       7
Shell Armor        7
Pickpocket         7
Unburden           7
Sand Veil          7
Water Veil         7
Iron Fist          7
Water Absorb       7
Defiant            7
Moody              7
Prankster          7
Leaf Guard         7
Sturdy             6
Chlorophyll        6
Lightning Rod      6
Heavy Metal        5
Solar Power        5
Thick Fat          5
Sniper             5
Contrary           5
Light Metal        5
Adaptability       5
Tinted Lens        5
Justified          5
Soundproof         5
Own Tempo          5
Steadfast          5
Keen Eye           5
Harvest            5
Technician         5
Swarm              4
Ice Body           4
Big Pecks          4
Cloud Nine         4
Pressure           4
Anger Point        4
Aftermath          4
Poison Touch       4
Protean            4
Skill Link         4
Rivalry            4
Magician           4
Plus               4
Quick Feet         4
Flame Body         4
Guts               4
No Guard           3
Cursed Body        3
Storm Drain        3
Competitive        3
Bulletproof        3
Gale Wings         3
Clear Body         3
Symbiosis          3
Rough Skin         3
Shadow Tag         3
Oblivious          3
Gooey              3
Unaware            3
Flash Fire         3
Magic Guard        3
Healer             3
Stench             3
Intimidate         3
Super Luck         3
Magic Bounce       3
Wonder Skin        3
Blaze              2
Marvel Scale       2
Simple             2
Multiscale         2
Zen Mode           2
Anticipation       2
Serene Grace       2
Sand Rush          2
Tangled Feet       2
Huge Power         2
Grass Pelt         2
Aroma Veil         2
Snow Warning       2
Torrent            2
Battle Armor       2
Overgrow           2
Limber             2
Flare Boost        2
Minus              2
Early Bird         2
Volt Absorb        2
Drought            2
Imposter           1
Pixilate           1
Rock Head          1
Honey Gather       1
Dry Skin           1
Toxic Boost        1
Immunity           1
White Smoke        1
Truant             1
Poison Heal        1
Cute Charm         1
Snow Cloak         1
Static             1
Motor Drive        1
Effect Spore       1
Drizzle            1
Klutz              1
Compound Eyes      1
Name: count, dtype: int64
- Unique values: ['Chlorophyll' 'None' 'Solar Power' 'Rain Dish' 'Run Away' 'Tinted Lens'
 'Sniper' 'Big Pecks' 'Hustle' 'Unnerve' 'Lightning Rod' 'Sand Rush'
 'Sheer Force' 'Friend Guard' 'Unaware' 'Drought' 'Frisk' 'Infiltrator'
 'Stench' 'Effect Spore' 'Damp' 'Wonder Skin' 'Sand Force' 'Swift Swim'
 'Defiant' 'Justified' 'Magic Guard' 'Steadfast' 'Gluttony' 'Sand Veil'
 'Flame Body' 'Regenerator' 'Analytic' 'Tangled Feet' 'Ice Body'
 'Poison Touch' 'Overcoat' 'Weak Armor' 'Inner Focus' 'Aftermath'
 'Harvest' 'Battle Armor' 'Unburden' 'Cloud Nine' 'Reckless' 'Healer'
 'Technician' 'Dry Skin' 'Vital Spirit' 'Moxie' 'Rattled' 'Hydration'
 'Imposter' 'Anticipation' 'Quick Feet' 'Guts' 'Snow Cloak' 'Static'
 'Marvel Scale' 'Multiscale' 'Leaf Guard' 'Flash Fire' 'Iron Fist'
 'Water Absorb' 'Super Luck' 'Magic Bounce' 'Plus' 'Sap Sipper' 'Drizzle'
 'Skill Link' 'Early Bird' 'Prankster' 'Telepathy' 'Immunity' 'Intimidate'
 'Light Metal' 'Contrary' 'Pickpocket' 'Honey Gather' 'Thick Fat' 'Moody'
 'Insomnia' 'Water Veil' 'Speed Boost' 'Rivalry' 'Compound Eyes'
 'Own Tempo' 'Scrappy' 'Heavy Metal' 'Minus' 'Volt Absorb' 'Pressure'
 'Anger Point' 'Shell Armor' 'Toxic Boost' 'Adaptability' 'Storm Drain'
 'Cute Charm' 'Protean' 'Cursed Body' 'Oblivious' 'Sturdy' 'Competitive'
 'Soundproof' 'Flare Boost' 'Limber' 'Keen Eye' 'Rough Skin' 'Poison Heal'
 'Overgrow' 'Blaze' 'Torrent' 'Simple' 'Mold Breaker' 'Klutz' 'Zen Mode'
 'Shadow Tag' 'Serene Grace' 'Motor Drive' 'No Guard' 'Swarm' 'Clear Body'
 'White Smoke' 'Truant' 'Bulletproof' 'Magician' 'Huge Power' 'Gale Wings'
 'Symbiosis' 'Grass Pelt' 'Aroma Veil' 'Rock Head' 'Snow Warning'
 'Pixilate' 'Gooey']

<span style = "font-family: Verdana; font-size: 20px">

##### **Generation**
</span>

In [96]:
describe_feature(data, 'Generation')

- Type: object
- First rows:
0    I
1    I
2    I
3    I
4    I
Name: Generation, dtype: object
- Last rows:
795    VI
796    VI
797    VI
798    VI
799    VI
Name: Generation, dtype: object
- Number of missing values: 0
object
- Number of distinct values: 6
- Unique value counts:
Generation
I      166
V      165
III    160
IV     121
II     106
VI      82
Name: count, dtype: int64
- Unique values: ['I' 'II' 'III' 'IV' 'V' 'VI']

In [97]:
data['Generation'] = data['Generation'].replace(['I', 'II', 'III', 'IV', 'V', 'VI'], [1, 2, 3, 4, 5, 6]).infer_objects(copy=False)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_14912\1242375916.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['Generation'] = data['Generation'].replace(['I', 'II', 'III', 'IV', 'V', 'VI'], [1, 2, 3, 4, 5, 6]).infer_objects(copy=False)

In [98]:
describe_feature(data, 'Generation')

- Type: int64
- First rows:
0    1
1    1
2    1
3    1
4    1
Name: Generation, dtype: int64
- Last rows:
795    6
796    6
797    6
798    6
799    6
Name: Generation, dtype: int64
- Number of missing values: 0
int64
- Number of distinct values: 6
- Unique value counts:
Generation
1    166
5    165
3    160
4    121
2    106
6     82
Name: count, dtype: int64
count    800.00000
mean       3.32375
std        1.66129
min        1.00000
25%        2.00000
50%        3.00000
75%        5.00000
max        6.00000
Name: Generation, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

##### **HP**
</span>

In [99]:
describe_feature(data, 'Hp')

- Type: float64
- First rows:
0    45.0
1    60.0
2    80.0
3    80.0
4    39.0
Name: Hp, dtype: float64
- Last rows:
795    50.0
796    50.0
797    80.0
798    80.0
799    80.0
Name: Hp, dtype: float64
- Number of missing values: 0
float64
- Number of distinct values: 94
- Unique value counts:
Hp
60.0     68
50.0     62
70.0     54
65.0     46
80.0     44
75.0     44
40.0     38
45.0     38
55.0     35
100.0    32
90.0     29
95.0     22
85.0     20
35.0     15
30.0     13
105.0    10
78.0      9
110.0     9
79.0      7
68.0      7
91.0      7
62.0      7
44.0      7
20.0      6
59.0      6
38.0      6
58.0      6
74.0      6
64.0      6
76.0      5
72.0      5
67.0      5
106.0     5
86.0      4
125.0     4
71.0      4
108.0     4
150.0     4
73.0      4
61.0      4
41.0      3
83.0      3
66.0      3
43.0      3
115.0     3
49.0      3
103.0     3
63.0      3
120.0     3
54.0      3
89.0      3
130.0     3
48.0      3
77.0      3
69.0      2
53.0      2
57.0      2
39.0      2
46.0      2
123.0     2
82.0      2
126.0     2
52.0      2
84.0      2
25.0      2
51.0      1
114.0     1
165.0     1
109.0     1
255.0     1
92.0      1
28.0      1
56.0      1
88.0      1
190.0     1
101.0     1
250.0     1
42.0      1
36.0      1
81.0      1
37.0      1
116.0     1
31.0      1
1.0       1
135.0     1
10.0      1
104.0     1
140.0     1
144.0     1
111.0     1
160.0     1
170.0     1
99.0      1
97.0      1
Name: count, dtype: int64
count    800.000000
mean      69.421250
std       25.542794
min        1.000000
25%       50.000000
50%       65.000000
75%       80.000000
max      255.000000
Name: Hp, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

##### **Attack**
</span>

In [100]:
describe_feature(data, 'Attack')

- Type: float64
- First rows:
0     49.0
1     62.0
2     82.0
3    100.0
4     52.0
Name: Attack, dtype: float64
- Last rows:
795    100.0
796    160.0
797    110.0
798    160.0
799    110.0
Name: Attack, dtype: float64
- Number of missing values: 0
float64
- Number of distinct values: 111
- Unique value counts:
Attack
100.0    41
65.0     39
50.0     37
80.0     36
90.0     32
85.0     32
75.0     32
60.0     32
70.0     31
55.0     30
45.0     26
95.0     26
40.0     21
120.0    21
30.0     20
105.0    18
110.0    17
130.0    15
125.0    14
35.0     13
150.0    10
48.0      9
115.0     9
20.0      8
52.0      7
66.0      7
25.0      7
92.0      7
140.0     7
72.0      7
82.0      6
63.0      6
135.0     6
84.0      5
53.0      5
73.0      5
64.0      5
160.0     5
83.0      4
78.0      4
69.0      4
77.0      4
145.0     4
62.0      4
76.0      4
58.0      4
59.0      3
38.0      3
68.0      3
165.0     3
49.0      3
180.0     3
47.0      3
123.0     3
10.0      3
98.0      3
104.0     3
89.0      3
103.0     3
117.0     3
56.0      3
81.0      3
109.0     2
61.0      2
86.0      2
124.0     2
112.0     2
94.0      2
93.0      2
170.0     2
87.0      2
131.0     2
155.0     2
51.0      2
41.0      2
134.0     2
57.0      2
5.0       2
67.0      2
128.0     1
107.0     1
129.0     1
36.0      1
22.0      1
74.0      1
147.0     1
102.0     1
44.0      1
108.0     1
54.0      1
121.0     1
27.0      1
97.0      1
23.0      1
15.0      1
136.0     1
43.0      1
42.0      1
29.0      1
91.0      1
79.0      1
71.0      1
164.0     1
88.0      1
24.0      1
185.0     1
46.0      1
190.0     1
106.0     1
132.0     1
33.0      1
Name: count, dtype: int64
count    800.000000
mean      79.157500
std       32.459393
min        5.000000
25%       55.000000
50%       75.000000
75%      100.000000
max      190.000000
Name: Attack, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

##### **Defense**
</span>

In [101]:
describe_feature(data, 'Defense')

- Type: float64
- First rows:
0     49.0
1     63.0
2     83.0
3    123.0
4     43.0
Name: Defense, dtype: float64
- Last rows:
795    150.0
796    110.0
797     60.0
798     60.0
799    120.0
Name: Defense, dtype: float64
- Number of missing values: 0
float64
- Number of distinct values: 103
- Unique value counts:
Defense
70.0     53
50.0     50
60.0     46
80.0     40
65.0     36
40.0     36
90.0     35
100.0    33
45.0     32
55.0     30
85.0     29
95.0     27
75.0     27
35.0     23
105.0    15
30.0     13
120.0    12
110.0    12
48.0     11
115.0    11
130.0    10
67.0      8
140.0     7
62.0      7
63.0      7
58.0      6
150.0     6
77.0      6
125.0     6
72.0      6
43.0      6
78.0      6
53.0      5
122.0     5
107.0     5
52.0      5
15.0      4
76.0      4
57.0      4
44.0      4
88.0      4
79.0      4
86.0      4
64.0      4
20.0      4
230.0     3
37.0      3
66.0      3
68.0      3
42.0      3
34.0      3
160.0     3
180.0     3
83.0      3
84.0      2
118.0     2
135.0     2
145.0     2
39.0      2
91.0      2
71.0      2
49.0      2
73.0      2
200.0     2
32.0      2
25.0      2
5.0       2
38.0      2
69.0      2
41.0      2
54.0      1
103.0     1
59.0      1
99.0      1
184.0     1
119.0     1
89.0      1
133.0     1
123.0     1
82.0      1
111.0     1
126.0     1
33.0      1
112.0     1
129.0     1
131.0     1
23.0      1
106.0     1
87.0      1
56.0      1
108.0     1
116.0     1
109.0     1
47.0      1
94.0      1
28.0      1
102.0     1
168.0     1
51.0      1
10.0      1
61.0      1
97.0      1
121.0     1
Name: count, dtype: int64
count    800.000000
mean      73.955000
std       31.092626
min        5.000000
25%       50.000000
50%       70.000000
75%       90.000000
max      230.000000
Name: Defense, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

##### **SpecialAttack**
</span>

In [102]:
describe_feature(data, 'SpecialAttack')

- Type: float64
- First rows:
0     65.0
1     80.0
2    100.0
3    122.0
4     60.0
Name: SpecialAttack, dtype: float64
- Last rows:
795    100.0
796    160.0
797    150.0
798    170.0
799    130.0
Name: SpecialAttack, dtype: float64
- Number of missing values: 0
float64
- Number of distinct values: 105
- Unique value counts:
SpecialAttack
60.0     51
40.0     49
65.0     44
50.0     38
55.0     35
45.0     33
70.0     30
35.0     29
100.0    28
95.0     28
85.0     26
80.0     25
30.0     24
90.0     22
105.0    20
75.0     18
110.0    16
125.0    14
120.0    14
25.0     11
130.0    11
115.0     9
20.0      8
150.0     8
44.0      8
83.0      8
58.0      7
135.0     7
81.0      6
61.0      6
63.0      5
140.0     5
74.0      5
62.0      5
73.0      4
92.0      4
97.0      4
69.0      4
54.0      4
53.0      4
15.0      4
109.0     4
145.0     4
77.0      3
57.0      3
37.0      3
180.0     3
98.0      3
72.0      3
10.0      3
48.0      3
170.0     3
59.0      3
56.0      3
79.0      3
87.0      2
154.0     2
43.0      2
24.0      2
68.0      2
67.0      2
42.0      2
103.0     2
112.0     2
129.0     2
32.0      2
27.0      2
99.0      2
49.0      2
165.0     2
131.0     2
47.0      2
76.0      2
86.0      2
160.0     2
114.0     2
94.0      2
46.0      2
71.0      2
36.0      2
31.0      1
159.0     1
106.0     1
128.0     1
91.0      1
122.0     1
51.0      1
39.0      1
107.0     1
111.0     1
175.0     1
93.0      1
104.0     1
108.0     1
116.0     1
132.0     1
23.0      1
38.0      1
41.0      1
64.0      1
33.0      1
194.0     1
78.0      1
29.0      1
88.0      1
Name: count, dtype: int64
count    800.000000
mean      72.963750
std       32.763956
min       10.000000
25%       49.750000
50%       65.000000
75%       95.000000
max      194.000000
Name: SpecialAttack, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

##### **SpecialDefense**
</span>

In [103]:
describe_feature(data, 'SpecialDefense')

- Type: float64
- First rows:
0     65.0
1     80.0
2    100.0
3    120.0
4     50.0
Name: SpecialDefense, dtype: float64
- Last rows:
795    150.0
796    110.0
797    130.0
798    130.0
799     90.0
Name: SpecialDefense, dtype: float64
- Number of missing values: 0
float64
- Number of distinct values: 92
- Unique value counts:
SpecialDefense
80.0     51
50.0     50
55.0     47
65.0     43
60.0     42
70.0     41
75.0     39
90.0     37
45.0     35
85.0     31
40.0     30
95.0     29
100.0    28
30.0     20
105.0    18
35.0     18
110.0    15
120.0    14
25.0     11
63.0     10
115.0    10
48.0      9
130.0     8
56.0      7
20.0      6
150.0     6
107.0     6
42.0      5
86.0      5
135.0     4
71.0      4
82.0      4
41.0      4
52.0      4
79.0      4
61.0      4
87.0      3
77.0      3
43.0      3
69.0      3
44.0      3
72.0      3
81.0      3
154.0     3
140.0     3
96.0      3
83.0      3
66.0      3
62.0      3
54.0      3
37.0      3
67.0      2
128.0     2
39.0      2
57.0      2
116.0     2
89.0      2
46.0      2
59.0      2
98.0      2
160.0     2
58.0      2
49.0      2
53.0      2
76.0      2
125.0     2
31.0      1
36.0      1
38.0      1
88.0      1
99.0      1
64.0      1
123.0     1
94.0      1
92.0      1
113.0     1
129.0     1
126.0     1
230.0     1
138.0     1
32.0      1
23.0      1
106.0     1
33.0      1
200.0     1
108.0     1
101.0     1
51.0      1
34.0      1
117.0     1
102.0     1
73.0      1
Name: count, dtype: int64
count    800.000000
mean      72.051250
std       27.902003
min       20.000000
25%       50.000000
50%       70.000000
75%       90.000000
max      230.000000
Name: SpecialDefense, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

##### **Speed**
</span>

In [104]:
describe_feature(data, 'Speed')

- Type: float64
- First rows:
0    45.0
1    60.0
2    80.0
3    80.0
4    65.0
Name: Speed, dtype: float64
- Last rows:
795     50.0
796    110.0
797     70.0
798     80.0
799     70.0
Name: Speed, dtype: float64
- Number of missing values: 0
float64
- Number of distinct values: 108
- Unique value counts:
Speed
50.0     46
60.0     43
65.0     36
70.0     36
30.0     35
80.0     34
40.0     32
90.0     32
55.0     30
100.0    30
45.0     29
95.0     27
85.0     27
35.0     22
110.0    16
75.0     16
20.0     15
105.0    12
115.0    11
25.0     10
15.0      9
58.0      8
108.0     7
101.0     7
68.0      6
42.0      6
130.0     6
71.0      6
48.0      6
120.0     5
36.0      5
91.0      5
150.0     5
64.0      5
56.0      5
97.0      5
86.0      5
43.0      5
92.0      4
57.0      4
32.0      4
23.0      4
66.0      4
28.0      4
67.0      4
78.0      4
81.0      4
72.0      4
99.0      4
38.0      3
52.0      3
145.0     3
84.0      3
74.0      3
112.0     3
29.0      3
104.0     3
41.0      3
76.0      3
10.0      3
98.0      3
125.0     3
44.0      3
51.0      3
83.0      3
46.0      3
109.0     2
69.0      2
73.0      2
111.0     2
116.0     2
106.0     2
59.0      2
77.0      2
135.0     2
47.0      2
31.0      2
93.0      2
5.0       2
61.0      2
63.0      2
121.0     2
33.0      2
102.0     2
62.0      1
140.0     1
126.0     1
89.0      1
87.0      1
49.0      1
118.0     1
128.0     1
54.0      1
122.0     1
79.0      1
103.0     1
127.0     1
22.0      1
160.0     1
180.0     1
88.0      1
114.0     1
34.0      1
39.0      1
24.0      1
82.0      1
113.0     1
123.0     1
Name: count, dtype: int64
count    800.00000
mean      68.40250
std       29.12698
min        5.00000
25%       45.00000
50%       65.00000
75%       90.00000
max      180.00000
Name: Speed, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

##### **TotalStats**
</span>

In [105]:
describe_feature(data, 'TotalStats')

- Type: float64
- First rows:
0    318.0
1    405.0
2    625.0
3    625.0
4    309.0
Name: TotalStats, dtype: float64
- Last rows:
795    700.0
796    700.0
797    680.0
798    680.0
799    600.0
Name: TotalStats, dtype: float64
- Number of missing values: 0
float64
- Number of distinct values: 196
- Unique value counts:
TotalStats
600.0    34
580.0    26
405.0    25
300.0    19
500.0    19
490.0    17
700.0    17
495.0    16
330.0    15
525.0    14
480.0    13
305.0    13
680.0    12
485.0    12
310.0    10
520.0    10
455.0    10
335.0     9
510.0     9
420.0     9
540.0     9
460.0     9
430.0     8
505.0     8
325.0     8
340.0     8
410.0     8
515.0     8
630.0     8
535.0     8
280.0     7
350.0     7
250.0     7
440.0     7
290.0     7
390.0     7
320.0     7
470.0     7
295.0     6
355.0     6
465.0     6
530.0     6
360.0     6
450.0     6
400.0     5
590.0     5
475.0     5
780.0     5
205.0     5
395.0     5
494.0     5
275.0     5
385.0     4
770.0     4
625.0     4
309.0     4
314.0     4
370.0     4
610.0     4
498.0     4
424.0     4
425.0     4
288.0     4
483.0     4
220.0     4
245.0     4
435.0     4
308.0     4
474.0     4
618.0     4
560.0     4
365.0     4
528.0     3
260.0     3
210.0     3
316.0     3
545.0     3
303.0     3
452.0     3
348.0     3
318.0     3
534.0     3
345.0     3
285.0     3
555.0     3
315.0     3
413.0     3
195.0     3
270.0     3
200.0     3
640.0     3
634.0     3
415.0     2
521.0     2
468.0     2
384.0     2
262.0     2
519.0     2
458.0     2
482.0     2
565.0     2
411.0     2
329.0     2
484.0     2
575.0     2
594.0     2
579.0     2
472.0     2
292.0     2
488.0     2
294.0     2
362.0     2
448.0     2
240.0     2
328.0     2
265.0     2
341.0     2
278.0     2
466.0     2
454.0     2
670.0     2
635.0     2
237.0     2
615.0     2
323.0     2
567.0     1
473.0     1
401.0     1
489.0     1
428.0     1
464.0     1
514.0     1
306.0     1
319.0     1
461.0     1
380.0     1
304.0     1
462.0     1
213.0     1
289.0     1
423.0     1
369.0     1
507.0     1
481.0     1
551.0     1
382.0     1
552.0     1
409.0     1
471.0     1
307.0     1
313.0     1
531.0     1
550.0     1
431.0     1
499.0     1
351.0     1
198.0     1
509.0     1
218.0     1
190.0     1
236.0     1
456.0     1
266.0     1
269.0     1
336.0     1
180.0     1
215.0     1
302.0     1
377.0     1
299.0     1
273.0     1
442.0     1
253.0     1
349.0     1
251.0     1
375.0     1
467.0     1
508.0     1
418.0     1
497.0     1
358.0     1
264.0     1
487.0     1
446.0     1
281.0     1
255.0     1
720.0     1
194.0     1
334.0     1
479.0     1
244.0     1
224.0     1
523.0     1
363.0     1
263.0     1
708.0     1
Name: count, dtype: int64
count    800.000000
mean     442.698750
std      126.867676
min      180.000000
25%      330.000000
50%      455.000000
75%      525.000000
max      780.000000
Name: TotalStats, dtype: float64

In [106]:
for i in range(data.shape[0]):
    total = data.loc[i, 'Hp'] + data.loc[i, 'Attack'] + data.loc[i, 'Defense'] + data.loc[i, 'SpecialAttack'] + data.loc[i, 'SpecialDefense'] + data.loc[i, 'Speed']
    if not data.at[i, 'TotalStats'] == total:
        print(data.at[i, 'Name'], data.at[i, 'TotalStats'],  total)

Venusaur 625.0 525.0
Charizard 634.0 534.0
Blastoise 630.0 530.0
Beedrill 495.0 395.0
Pidgeot 579.0 479.0
Pikachu 430.0 320.0
Alakazam 600.0 500.0
Gengar 600.0 500.0
Kangaskhan 590.0 490.0
Pinsir 600.0 500.0
Gyarados 640.0 540.0
Eevee 435.0 325.0
Aerodactyl 615.0 515.0
Mewtwo 780.0 680.0
Ampharos 610.0 510.0
Steelix 610.0 510.0
Scizor 600.0 500.0
Heracross 600.0 500.0
Houndoom 600.0 500.0
Tyranitar 700.0 600.0
Sceptile 630.0 530.0
Blaziken 630.0 530.0
Swampert 635.0 535.0
Gardevoir 618.0 518.0
Sableye 480.0 380.0
Mawile 480.0 380.0
Aggron 630.0 530.0
Medicham 510.0 410.0
Manectric 575.0 475.0
Sharpedo 560.0 460.0
Camerupt 560.0 460.0
Altaria 590.0 490.0
Banette 555.0 455.0
Absol 565.0 465.0
Glalie 580.0 480.0
Salamence 700.0 600.0
Metagross 700.0 600.0
Latias 700.0 600.0
Latios 700.0 600.0
Kyogre 770.0 670.0
Groudon 770.0 670.0
Rayquaza 780.0 680.0
Lopunny 580.0 480.0
Garchomp 700.0 600.0
Lucario 625.0 525.0
Abomasnow 594.0 494.0
Gallade 618.0 518.0
Rotom 520.0 440.0
Audino 545.0 445.0
Darmanitan Standard Mode 540.0 480.0
Kyurem 700.0 660.0
Greninja 640.0 530.0
Zygarde Half Forme 708.0 600.0
Diancie 700.0 600.0
Hoopa Confined 680.0 600.0

<span style = "font-family: Verdana; font-size: 20px">

Có vẻ như tổng điểm chỉ số của một số các Pokémon có dạng tiến hoá Mega bị lệch so với tổng chỉ số thực tế của chúng, cần phải tính lại cột này.

In [107]:
data['TotalStats'] = data['Hp'] + data['Attack'] + data['Defense'] + data['SpecialAttack'] + data['SpecialDefense'] + data['Speed']

<span style = "font-family: Verdana; font-size: 20px">

##### **Weight**
</span>

In [108]:
describe_feature(data, 'Weight')

- Type: float64
- First rows:
0      6.9
1     13.0
2    100.0
3    155.5
4      8.5
Name: Weight, dtype: float64
- Last rows:
795      8.8
796     27.8
797      9.0
798      9.0
799    195.0
Name: Weight, dtype: float64
- Number of missing values: 0
float64
- Number of distinct values: 421

- Unique value counts:
Weight
0.3      10
5.0       9
6.5       9
8.5       9
15.0      9
30.0      8
28.0      8
1.0       7
9.0       7
2.0       7
12.0      6
4.0       6
9.5       6
12.5      6
55.0      6
120.0     6
60.0      6
6.0       5
11.5      5
5.5       5
20.0      5
19.5      5
7.5       5
38.0      5
2.1       5
32.0      5
40.5      5
3.5       5
11.0      4
1.2       4
32.5      4
31.5      4
18.0      4
27.0      4
33.0      4
2.5       4
14.0      4
31.0      4
35.0      4
8.0       4
29.0      4
10.5      4
60.8      4
13.0      4
52.0      4
7.0       4
50.5      4
10.0      4
29.5      4
40.0      4
21.0      3
68.0      3
0.1       3
24.0      3
4.5       3
6.6       3
19.0      3
61.0      3
325.0     3
0.6       3
80.0      3
39.5      3
25.0      3
39.0      3
100.0     3
260.0     3
24.5      3
220.0     3
28.5      3
23.5      3
22.0      3
3.0       3
16.0      3
54.0      3
61.5      3
20.5      3
14.5      3
15.5      3
33.5      3
9.9       3
5.8       3
95.0      3
4.2       3
3.9       3
63.0      3
79.5      3
48.0      3
8.8       2
81.0      2
41.0      2
58.0      2
49.5      2
200.0     2
17.0      2
51.0      2
152.0     2
7.3       2
187.0     2
125.8     2
92.9      2
5.7       2
60.5      2
102.0     2
13.5      2
17.7      2
3.1       2
750.0     2
30.6      2
430.0     2
20.6      2
52.5      2
1.9       2
70.0      2
21.5      2
108.0     2
47.0      2
23.3      2
34.0      2
57.5      2
44.0      2
15.2      2
55.5      2
20.2      2
17.5      2
3.6       2
37.5      2
31.6      2
2.2       2
2.3       2
1.7       2
10.2      2
25.5      2
16.3      2
94.6      2
5.9       2
97.0      2
30.5      2
48.4      2
6.9       2
23.0      2
3.2       2
16.5      2
39.2      2
3.3       2
90.0      2
210.0     2
1.8       2
33.3      2
330.0     2
0.8       2
305.0     2
65.0      2
81.5      2
59.0      2
62.0      2
56.0      2
34.5      2
5.4       2
36.0      2
53.0      2
48.5      2
10.8      2
22.5      2
7.8       2
1.5       2
130.0     2
75.0      2
6.4       2
110.5     2
100.5     2
0.5       2
105.0     2
300.0     2
88.8      2
2.8       1
138.6     1
270.0     1
150.5     1
128.6     1
26.6      1
25.2      1
106.6     1
291.0     1
340.0     1
25.9      1
56.4      1
42.5      1
225.0     1
282.8     1
51.5      1
44.4      1
140.0     1
6.3       1
27.8      1
203.0     1
42.0      1
215.0     1
102.5     1
57.0      1
149.5     1
85.0      1
3.4       1
505.0     1
38.5      1
9.3       1
29.9      1
180.0     1
20.3      1
28.3      1
4.4       1
27.3      1
43.8      1
19.2      1
99.5      1
24.4      1
683.0     1
135.5     1
185.0     1
71.0      1
26.0      1
24.9      1
336.0     1
17.3      1
87.0      1
92.0      1
139.0     1
35.5      1
5.3       1
58.5      1
200.5     1
33.4      1
96.3      1
25.3      1
7.7       1
148.0     1
105.5     1
34.3      1
80.5      1
11.8      1
76.5      1
110.0     1
107.3     1
81.1      1
20.1      1
24.2      1
18.8      1
14.3      1
92.5      1
40.4      1
50.0      1
420.0     1
29.8      1
35.3      1
85.6      1
8.3       1
1.4       1
96.0      1
320.0     1
135.0     1
136.0     1
150.0     1
91.0      1
0.9       1
11.6      1
4.1       1
8.4       1
42.4      1
10.9      1
9.4       1
82.5      1
14.7      1
345.0     1
10.1      1
250.0     1
46.0      1
28.8      1
160.0     1
8.1       1
11.2      1
84.5      1
21.2      1
41.5      1
26.5      1
33.9      1
13.3      1
35.6      1
40.8      1
7.9       1
64.8      1
15.8      1
127.0     1
122.0     1
52.6      1
55.4      1
460.0     1
7.2       1
400.0     1
36.5      1
75.5      1
255.0     1
202.0     1
72.0      1
198.0     1
178.0     1
46.8      1
21.4      1
740.0     1
71.2      1
55.8      1
62.5      1
125.0     1
118.0     1
48.7      1
79.0      1
235.0     1
5.2       1
8.6       1
56.5      1
12.4      1
155.0     1
76.6      1
19.6      1
18.6      1
19.9      1
45.5      1
18.5      1
2.9       1
101.1     1
85.5      1
90.5      1
155.5     1
70.5      1
78.5      1
88.4      1
50.2      1
44.5      1
40.6      1
54.5      1
34.6      1
115.0     1
65.5      1
49.8      1
85.2      1
45.0      1
66.6      1
10.4      1
75.6      1
32.4      1
132.5     1
216.0     1
199.0     1
21.6      1
256.5     1
8.7       1
23.4      1
22.6      1
150.6     1
87.6      1
350.2     1
16.8      1
102.6     1
49.0      1
162.0     1
7.4       1
68.2      1
60.4      1
23.8      1
42.1      1
112.6     1
52.2      1
950.0     1
6.2       1
310.0     1
1.1       1
392.0     1
206.5     1
999.7     1
352.0     1
95.2      1
205.0     1
175.0     1
230.0     1
942.9     1
550.0     1
202.5     1
32.8      1
23.6      1
154.0     1
59.6      1
253.8     1
86.4      1
84.0      1
130.5     1
46.5      1
19.8      1
2.6       1
168.0     1
28.4      1
37.0      1
13.6      1
81.9      1
7.6       1
55.2      1
32.6      1
161.0     1
360.0     1
395.0     1
40.2      1
10.3      1
20.8      1
130.3     1
398.0     1
320.5     1
80.4      1
71.5      1
15.3      1
82.0      1
51.3      1
77.4      1
40.3      1
195.0     1
Name: count, dtype: int64
count    800.00000
mean      63.93250
std      107.99052
min        0.10000
25%        9.80000
50%       29.95000
75%       65.77500
max      999.70000
Name: Weight, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

##### **Height**
</span>

In [109]:
describe_feature(data, 'Height')

- Type: float64
- First rows:
0    0.7
1    1.0
2    2.0
3    2.4
4    0.6
Name: Height, dtype: float64
- Last rows:
795    0.7
796    1.1
797    0.5
798    0.5
799    1.7
Name: Height, dtype: float64
- Number of missing values: 0
float64
- Number of distinct values: 51
- Unique value counts:
Height
0.6     68
0.5     61
1.0     59
0.4     56
0.3     51
1.2     48
1.5     47
0.8     44
1.1     38
0.7     35
1.4     33
0.9     32
1.3     31
1.7     30
1.6     26
2.0     21
1.8     19
1.9     16
0.2     14
2.1      9
2.2      9
2.5      8
3.0      4
2.3      4
4.5      3
2.7      3
0.1      2
3.2      2
5.0      2
3.5      2
6.5      2
2.4      2
5.2      1
4.2      1
8.8      1
2.9      1
2.8      1
2.6      1
3.3      1
3.7      1
5.4      1
3.8      1
10.8     1
7.0      1
4.0      1
9.8      1
9.2      1
6.2      1
10.5     1
14.5     1
5.8      1
Name: count, dtype: int64
count    800.000000
mean       1.222875
std        1.181041
min        0.100000
25%        0.600000
50%        1.000000
75%        1.500000
max       14.500000
Name: Height, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

##### **GenderProbM**
</span>

In [110]:
describe_feature(data, 'GenderProbM')

- Type: float64
- First rows:
0    0.875
1    0.875
2    0.875
3    0.875
4    0.875
Name: GenderProbM, dtype: float64
- Last rows:
795   -1.0
796   -1.0
797   -1.0
798   -1.0
799   -1.0
Name: GenderProbM, dtype: float64
- Number of missing values: 0
float64
- Number of distinct values: 8
- Unique value counts:
GenderProbM
 0.500    495
 0.875    110
-1.000     99
 0.000     28
 1.000     24
 0.250     22
 0.750     20
 0.125      2
Name: count, dtype: int64
count    800.000000
mean       0.361875
std        0.546765
min       -1.000000
25%        0.500000
50%        0.500000
75%        0.500000
max        1.000000
Name: GenderProbM, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

GenderProbM cho biết tỷ lệ giống đực của Pokémon, giá trị `-1` biểu thị cho các Pokémon không có giới tính như các Pokémon huyền thoại hay thần thoại. Để khoảng giá trị của cột này liên tục từ 0 đến 1, ta sẽ thay thế các giá trị `-1` này bằng `0.5` và thêm một cột để thể hiện rằng Pokémon đó có giới tính hay không.

In [111]:
data['NoGender'] = 0
data.loc[data['GenderProbM'] == -1, 'NoGender'] = 1
data['GenderProbM'] = data['GenderProbM'].replace([-1], [0.5]).astype('float64')
describe_feature(data, 'GenderProbM')
describe_feature(data, 'NoGender')

- Type: float64
- First rows:
0    0.875
1    0.875
2    0.875
3    0.875
4    0.875
Name: GenderProbM, dtype: float64
- Last rows:
795    0.5
796    0.5
797    0.5
798    0.5
799    0.5
Name: GenderProbM, dtype: float64
- Number of missing values: 0
float64
- Number of distinct values: 7
- Unique value counts:
GenderProbM
0.500    594
0.875    110
0.000     28
1.000     24
0.250     22
0.750     20
0.125      2
Name: count, dtype: int64
count    800.000000
mean       0.547500
std        0.192377
min        0.000000
25%        0.500000
50%        0.500000
75%        0.500000
max        1.000000
Name: GenderProbM, dtype: float64
- Type: int64
- First rows:
0    0
1    0
2    0
3    0
4    0
Name: NoGender, dtype: int64
- Last rows:
795    1
796    1
797    1
798    1
799    1
Name: NoGender, dtype: int64
- Number of missing values: 0
int64
- Number of distinct values: 2
- Unique value counts:
NoGender
0    701
1     99
Name: count, dtype: int64
count    800.000000
mean       0.123750
std        0.329502
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max        1.000000
Name: NoGender, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

##### **Category**
</span>

In [112]:
describe_feature(data, 'Category')

- Type: object
- First rows:
0      Seed Pokémon
1      Seed Pokémon
2      Seed Pokémon
3      Seed Pokémon
4    Lizard Pokémon
Name: Category, dtype: object
- Last rows:
795       Jewel Pokémon
796       Jewel Pokémon
797    Mischief Pokémon
798    Mischief Pokémon
799       Steam Pokémon
Name: Category, dtype: object
- Number of missing values: 0
object
- Number of distinct values: 524
- Unique value counts:
Category
Dragon Pokémon           9
Pumpkin Pokémon          8
Flame Pokémon            7
Mushroom Pokémon         6
Bagworm Pokémon          6
Mouse Pokémon            6
Plasma Pokémon           6
Fox Pokémon              5
Balloon Pokémon          5
Seed Pokémon             5
Bat Pokémon              4
Poison Pin Pokémon       4
Mud Fish Pokémon         4
Iron Armor Pokémon       4
Eon Pokémon              4
Fairy Pokémon            4
Psi Pokémon              4
Drill Pokémon            4
Tadpole Pokémon          4
DNA Pokémon              4
Shellfish Pokémon        4
Cocoon Pokémon           4
Meditate Pokémon         3
Superpower Pokémon       3
Muscular Pokémon         3
Boundary Pokémon         3
Frost Tree Pokémon       3
Brutal Pokémon           3
Light Pokémon            3
Pincer Pokémon           3
EleFish Pokémon          3
Gear Pokémon             3
Volcano Pokémon          3
Vibration Pokémon        3
Bivalve Pokémon          3
Genetic Pokémon          3
Continent Pokémon        3
Cottonweed Pokémon       3
Flower Pokémon           3
Dark Pokémon             3
Jewel Pokémon            3
Tiny Bird Pokémon        3
Bird Pokémon             3
Armor Pokémon            3
Electric Pokémon         3
Rabbit Pokémon           3
Darkness Pokémon         3
Mole Pokémon             3
Virtual Pokémon          3
Sun Pokémon              3
Big Jaw Pokémon          3
Disaster Pokémon         2
Face Pokémon             2
Iceberg Pokémon          2
Sky High Pokémon         2
Marionette Pokémon       2
Whiskers Pokémon         2
Clay Doll Pokémon        2
Sea Basin Pokémon        2
Playful Pokémon          2
Deceiver Pokémon         2
Meteorite Pokémon        2
Embrace Pokémon          2
Jet Pokémon              2
Kite Pokémon             2
Wood Gecko Pokémon       2
Forest Pokémon           2
Blaze Pokémon            2
Bite Pokémon             2
Water Bird Pokémon       2
Emotion Pokémon          2
Ninja Pokémon            2
Humming Pokémon          2
Compass Pokémon          2
Starling Pokémon         2
Discharge Pokémon        2
Cheering Pokémon         2
Firefly Pokémon          2
Eruption Pokémon         2
Manipulate Pokémon       2
Cactus Pokémon           2
Penguin Pokémon          2
Fresh Snow Pokémon       2
Cricket Pokémon          2
Scatterdust Pokémon      2
Martial Arts Pokémon     2
Automaton Pokémon        2
Cyclone Pokémon          2
Bolt Strike Pokémon      2
Abundance Pokémon        2
Colt Pokémon             2
Melody Pokémon           2
Spiny Armor Pokémon      2
Bubble Frog Pokémon      2
Digging Pokémon          2
Single Bloom Pokémon     2
Cerebral Pokémon         2
Mount Pokémon            2
Constraint Pokémon       2
Sword Pokémon            2
Royal Sword Pokémon      2
Mock Kelp Pokémon        2
Generator Pokémon        2
Tundra Pokémon           2
Soft Tissue Pokémon      2
Sound Wave Pokémon       2
Mischief Pokémon         2
Axe Jaw Pokémon          2
Floating Pokémon         2
Head Butt Pokémon        2
Blade Pokémon            2
Shield Pokémon           2
Sea Weasel Pokémon       2
Sea Slug Pokémon         2
Skunk Pokémon            2
Cave Pokémon             2
Mach Pokémon             2
Aura Pokémon             2
Toxic Mouth Pokémon      2
Thunderbolt Pokémon      2
Sharp Claw Pokémon       2
Renegade Pokémon         2
Season Pokémon           2
Gratitude Pokémon        2
Grass Snake Pokémon      2
Fire Pig Pokémon         2
Ember Pokémon            2
Hearing Pokémon          2
Hostile Pokémon          2
Desert Croc Pokémon      2
Blazing Pokémon          2
Prototurtle Pokémon      2
First Bird Pokémon       2
Lava Pokémon             2
Iron Leg Pokémon         2
Single Horn Pokémon      2
Lightning Pokémon        2
Licking Pokémon          2
Poison Gas Pokémon       2
Parent Pokémon           2
Goldfish Pokémon         2
Star Shape Pokémon       2
Stag Beetle Pokémon      2
Fish Pokémon             2
Atrocious Pokémon        2
Spiral Pokémon           2
Water Fish Pokémon       2
Fossil Pokémon           2
Leaf Pokémon             2
Scout Pokémon            2
Owl Pokémon              2
Five Star Pokémon        2
Happiness Pokémon        2
Mystic Pokémon           2
Wool Pokémon             2
Egg Pokémon              2
Ball Pokémon             2
Hypnosis Pokémon         2
Shadow Pokémon           2
Worm Pokémon             2
Butterfly Pokémon        2
Poison Bee Pokémon       2
Weed Pokémon             2
Poison Moth Pokémon      2
Duck Pokémon             2
Pig Monkey Pokémon       2
Puppy Pokémon            2
Flycatcher Pokémon       2
Jellyfish Pokémon        2
Rock Pokémon             2
Fire Horse Pokémon       2
Hermit Crab Pokémon      2
Magnet Pokémon           2
Sea Lion Pokémon         2
Sludge Pokémon           2
Gas Pokémon              2
Long Tail Pokémon        2
Vine Pokémon             2
Royal Pokémon            2
Iron Snake Pokémon       2
Tiny Swallow Pokémon     1
Hoodlum Pokémon          1
Tricky Fox Pokémon       1
Trash Heap Pokémon       1
Trash Bag Pokémon        1
Kiss Pokémon             1
Live Coal Pokémon        1
Coffin Pokémon           1
Spirit Pokémon           1
Avianoid Pokémon         1
Shedding Pokémon         1
Chinchilla Pokémon       1
Stone Home Pokémon       1
Rock Inn Pokémon         1
Rock Snake Pokémon       1
Zen Charm Pokémon        1
Intimidation Pokémon     1
Milk Cow Pokémon         1
River Crab Pokémon       1
Illusion Fox Pokémon     1
Scarf Pokémon            1
Bulb Pokémon             1
Fixation Pokémon         1
Thorn Pod Pokémon        1
Thorn Seed Pokémon       1
EleSpider Pokémon        1
Attaching Pokémon        1
Caring Pokémon           1
Scuffle Pokémon          1
Cavalry Pokémon          1
Clamping Pokémon         1
Sky Squirrel Pokémon     1
Handstand Pokémon        1
Snowstorm Pokémon        1
Icy Snow Pokémon         1
White Bird Pokémon       1
Multiplying Pokémon      1
Mitosis Pokémon          1
Cell Pokémon             1
Astral Body Pokémon      1
Flowering Pokémon        1
Windveiled Pokémon       1
Twin Bird Pokémon        1
Loyal Dog Pokémon        1
Spray Pokémon            1
Coconut Pokémon          1
High Temp Pokémon        1
Thorn Monkey Pokémon     1
Grass Monkey Pokémon     1
Cruel Pokémon            1
Devious Pokémon          1
Big-Hearted Pokémon      1
Lookout Pokémon          1
Dream Eater Pokémon      1
Formidable Pokémon       1
Discipline Pokémon       1
Sea Otter Pokémon        1
Mega Fire Pig Pokémon    1
Lonely Pokémon           1
Regal Pokémon            1
Bone Keeper Pokémon      1
Victory Pokémon          1
Geyser Pokémon           1
Drowsing Pokémon         1
Cotton Puff Pokémon      1
Thunder Pokémon          1
Megapede Pokémon         1
Curlipede Pokémon        1
Centipede Pokémon        1
Nurturing Pokémon        1
Leaf-Wrapped Pokémon     1
Sewing Pokémon           1
Karate Pokémon           1
Judo Pokémon             1
Aurora Pokémon           1
Tiny Pigeon Pokémon      1
Subterrene Pokémon       1
Courting Pokémon         1
Compressed Pokémon       1
Ore Pokémon              1
Mantle Pokémon           1
Electrified Pokémon      1
Proud Pokémon            1
Wild Pigeon Pokémon      1
Triple Bird Pokémon      1
Wild Duck Pokémon        1
Kicking Pokémon          1
Perfume Pokémon          1
Snake Pokémon            1
Collective Pokémon       1
Two-Handed Pokémon       1
Overturning Pokémon      1
Revolving Pokémon        1
Meringue Pokémon         1
Cotton Candy Pokémon     1
Fragrance Pokémon        1
Cobra Pokémon            1
Scale Pokémon            1
Swine Pokémon            1
Insect Pokémon           1
Restraint Pokémon        1
Poodle Pokémon           1
Daunting Pokémon         1
Coral Pokémon            1
Garden Pokémon           1
Scratch Cat Pokémon      1
Water Gun Pokémon        1
Howitzer Pokémon         1
Beak Pokémon             1
Royal Heir Pokémon       1
Tiny Turtle Pokémon      1
Order Pokémon            1
Destruction Pokémon      1
Life Pokémon             1
Turtle Pokémon           1
Ice Chunk Pokémon        1
Hibernator Pokémon       1
Elder Tree Pokémon       1
Stump Pokémon            1
Key Ring Pokémon         1
Mold Pokémon             1
Hairy Bug Pokémon        1
Antenna Pokémon          1
Wrestling Pokémon        1
Intertwining Pokémon     1
Pig Pokémon              1
Despot Pokémon           1
Lion Cub Pokémon         1
Classy Cat Pokémon       1
Candle Pokémon           1
Trap Pokémon             1
Diapered Pokémon         1
Valiant Pokémon          1
Eaglet Pokémon           1
Bash Buffalo Pokémon     1
Sword Blade Pokémon      1
Sharp Blade Pokémon      1
Dopey Pokémon            1
Big Horn Pokémon         1
Shell Out Pokémon        1
Scorching Pokémon        1
Snail Pokémon            1
Crystallizing Pokémon    1
Freezing Pokémon         1
Chill Pokémon            1
Painter Pokémon          1
Tusk Pokémon             1
Luring Pokémon           1
Lamp Pokémon             1
Bone Vulture Pokémon     1
Anteater Pokémon         1
Iron Ant Pokémon         1
Irate Pokémon            1
Tiny Robin Pokémon       1
Delivery Pokémon         1
Fly Scorpion Pokémon     1
Spiny Nut Pokémon        1
Paleozoic Pokémon        1
Legendary Pokémon        1
Armor Bird Pokémon       1
Land Snake Pokémon       1
Long Nose Pokémon        1
Deep Black Pokémon       1
Vast White Pokémon       1
Megaton Pokémon          1
Long Neck Pokémon        1
Grassland Pokémon        1
Cavern Pokémon           1
Iron Will Pokémon        1
Torch Pokémon            1
Alpha Pokémon            1
Pitch-Black Pokémon      1
Swallow Pokémon          1
Rogue Pokémon            1
Color Swap Pokémon       1
Weather Pokémon          1
Tender Pokémon           1
Plate Pokémon            1
Old Shrimp Pokémon       1
Barnacle Pokémon         1
Sea Lily Pokémon         1
Fire Mouse Pokémon       1
Ruffian Pokémon          1
Herb Pokémon             1
Tiny Raccoon Pokémon     1
Long Body Pokémon        1
Fang Snake Pokémon       1
Cat Ferret Pokémon       1
Rushing Pokémon          1
Cotton Bird Pokémon      1
Scarecrow Pokémon        1
Water Weed Pokémon       1
Puppet Pokémon           1
Requiem Pokémon          1
Seafaring Pokémon        1
Deep Sea Pokémon         1
Lizard Pokémon           1
Iron Claw Pokémon        1
Iron Ball Pokémon        1
Endurance Pokémon        1
Rock Head Pokémon        1
Rendezvous Pokémon       1
Longevity Pokémon        1
South Sea Pokémon        1
Ice Break Pokémon        1
Beckon Pokémon           1
Ball Roll Pokémon        1
Clap Pokémon             1
New Species Pokémon      1
Snow Hat Pokémon         1
Bright Pokémon           1
Moonlight Pokémon        1
Wind Chime Pokémon       1
Fruit Pokémon            1
String Spit Pokémon      1
Ant Pit Pokémon          1
Spot Panda Pokémon       1
Lazy Pokémon             1
Arm Thrust Pokémon       1
Guts Pokémon             1
Loud Noise Pokémon       1
Big Voice Pokémon        1
Whisper Pokémon          1
Shed Pokémon             1
Frog Pokémon             1
Trainee Pokémon          1
Wild Monkey Pokémon      1
Long Leg Pokémon         1
Slacker Pokémon          1
Eyeball Pokémon          1
Pond Skater Pokémon      1
Wily Pokémon             1
Clear Wing Pokémon       1
Feeling Pokémon          1
Wicked Pokémon           1
Seagull Pokémon          1
Polka Dot Pokémon        1
Imitation Pokémon        1
Kitten Pokémon           1
Prim Pokémon             1
Bounce Pokémon           1
Coal Pokémon             1
Angler Pokémon           1
Numb Pokémon             1
Float Whale Pokémon      1
Ball Whale Pokémon       1
Tiny Mouse Pokémon       1
Savage Pokémon           1
Poison Bag Pokémon       1
Stomach Pokémon          1
Thorn Pokémon            1
Spike Ball Pokémon       1
Jolly Pokémon            1
Carefree Pokémon         1
Acorn Pokémon            1
Aqua Mouse Pokémon       1
Aqua Rabbit Pokémon      1
Rock Peak Pokémon        1
Freeze Pokémon           1
Iron Pokémon             1
Heavyweight Pokémon      1
Magnet Area Pokémon      1
Diving Pokémon           1
Neon Pokémon             1
Wing Fish Pokémon        1
Bug Catcher Pokémon      1
Rainbow Pokémon          1
Ogre Scorpion Pokémon    1
Scorpion Pokémon         1
Hippo Pokémon            1
Mime Pokémon             1
Time Travel Pokémon      1
Emanation Pokémon        1
Big Eater Pokémon        1
Mysterious Pokémon       1
Barrier Pokémon          1
Land Shark Pokémon       1
Forbidden Pokémon        1
Music Note Pokémon       1
Little Bear Pokémon      1
Blast Pokémon            1
Jubilee Pokémon          1
Ogre Darner Pokémon      1
Sea Drifter Pokémon      1
Lunar Pokémon            1
Punching Pokémon         1
Colossal Pokémon         1
Lava Dome Pokémon        1
Spatial Pokémon          1
Temporal Pokémon         1
Willpower Pokémon        1
Knowledge Pokémon        1
Rock Skin Pokémon        1
Snow Land Pokémon        1
Gripper Pokémon          1
Hard Shell Pokémon       1
Twin Tusk Pokémon        1
Fang Scorpion Pokémon    1
Spikes Pokémon           1
Verdant Pokémon          1
Playhouse Pokémon        1
Bonsai Pokémon           1
Sleeping Pokémon         1
Emperor Pokémon          1
Gleam Eyes Pokémon       1
Spark Pokémon            1
Flash Pokémon            1
Chick Pokémon            1
Beaver Pokémon           1
Plump Mouse Pokémon      1
Predator Pokémon         1
Transport Pokémon        1
Transform Pokémon        1
Bronze Bell Pokémon      1
Evolution Pokémon        1
Chimp Pokémon            1
Grove Pokémon            1
Tiny Leaf Pokémon        1
Bubble Jet Pokémon       1
Wish Pokémon             1
Young Fowl Pokémon       1
Screech Pokémon          1
Bud Pokémon              1
Bouquet Pokémon          1
Symbol Pokémon           1
Wild Bull Pokémon        1
Bronze Pokémon           1
Mantis Pokémon           1
Bell Pokémon             1
Tiger Cat Pokémon        1
Catty Pokémon            1
Big Boss Pokémon         1
Magical Pokémon          1
Human Shape Pokémon      1
Blimp Pokémon            1
Spitfire Pokémon         1
Blossom Pokémon          1
Cherry Pokémon           1
Patient Pokémon          1
EleSquirrel Pokémon      1
Beehive Pokémon          1
Tiny Bee Pokémon         1
Moth Pokémon             1
Steam Pokémon            1
Name: count, dtype: int64
- Unique values: ['Seed Pokémon' 'Lizard Pokémon' 'Flame Pokémon' 'Tiny Turtle Pokémon'
 'Turtle Pokémon' 'Shellfish Pokémon' 'Worm Pokémon' 'Cocoon Pokémon'
 'Butterfly Pokémon' 'Hairy Bug Pokémon' 'Poison Bee Pokémon'
 'Tiny Bird Pokémon' 'Bird Pokémon' 'Mouse Pokémon' 'Beak Pokémon'
 'Snake Pokémon' 'Cobra Pokémon' 'Poison Pin Pokémon' 'Drill Pokémon'
 'Fairy Pokémon' 'Fox Pokémon' 'Balloon Pokémon' 'Bat Pokémon'
 'Weed Pokémon' 'Flower Pokémon' 'Mushroom Pokémon' 'Insect Pokémon'
 'Poison Moth Pokémon' 'Mole Pokémon' 'Scratch Cat Pokémon'
 'Classy Cat Pokémon' 'Duck Pokémon' 'Pig Monkey Pokémon' 'Puppy Pokémon'
 'Legendary Pokémon' 'Tadpole Pokémon' 'Psi Pokémon' 'Superpower Pokémon'
 'Flycatcher Pokémon' 'Jellyfish Pokémon' 'Rock Pokémon' 'Megaton Pokémon'
 'Fire Horse Pokémon' 'Dopey Pokémon' 'Hermit Crab Pokémon'
 'Magnet Pokémon' 'Wild Duck Pokémon' 'Twin Bird Pokémon'
 'Triple Bird Pokémon' 'Sea Lion Pokémon' 'Sludge Pokémon'
 'Bivalve Pokémon' 'Gas Pokémon' 'Shadow Pokémon' 'Rock Snake Pokémon'
 'Hypnosis Pokémon' 'River Crab Pokémon' 'Pincer Pokémon' 'Ball Pokémon'
 'Egg Pokémon' 'Coconut Pokémon' 'Lonely Pokémon' 'Bone Keeper Pokémon'
 'Kicking Pokémon' 'Punching Pokémon' 'Licking Pokémon'
 'Poison Gas Pokémon' 'Spikes Pokémon' 'Vine Pokémon' 'Parent Pokémon'
 'Dragon Pokémon' 'Goldfish Pokémon' 'Star Shape Pokémon'
 'Mysterious Pokémon' 'Barrier Pokémon' 'Mantis Pokémon'
 'Human Shape Pokémon' 'Electric Pokémon' 'Spitfire Pokémon'
 'Stag Beetle Pokémon' 'Wild Bull Pokémon' 'Fish Pokémon'
 'Atrocious Pokémon' 'Transport Pokémon' 'Transform Pokémon'
 'Evolution Pokémon' 'Bubble Jet Pokémon' 'Lightning Pokémon'
 'Virtual Pokémon' 'Spiral Pokémon' 'Fossil Pokémon' 'Sleeping Pokémon'
 'Freeze Pokémon' 'Genetic Pokémon' 'New Species Pokémon' 'Leaf Pokémon'
 'Herb Pokémon' 'Fire Mouse Pokémon' 'Volcano Pokémon' 'Big Jaw Pokémon'
 'Scout Pokémon' 'Long Body Pokémon' 'Owl Pokémon' 'Five Star Pokémon'
 'String Spit Pokémon' 'Long Leg Pokémon' 'Angler Pokémon' 'Light Pokémon'
 'Tiny Mouse Pokémon' 'Spike Ball Pokémon' 'Happiness Pokémon'
 'Mystic Pokémon' 'Wool Pokémon' 'Aqua Mouse Pokémon'
 'Aqua Rabbit Pokémon' 'Imitation Pokémon' 'Frog Pokémon'
 'Cottonweed Pokémon' 'Long Tail Pokémon' 'Sun Pokémon'
 'Clear Wing Pokémon' 'Water Fish Pokémon' 'Moonlight Pokémon'
 'Darkness Pokémon' 'Royal Pokémon' 'Screech Pokémon' 'Symbol Pokémon'
 'Patient Pokémon' 'Long Neck Pokémon' 'Bagworm Pokémon'
 'Land Snake Pokémon' 'Fly Scorpion Pokémon' 'Iron Snake Pokémon'
 'Mold Pokémon' 'Single Horn Pokémon' 'Sharp Claw Pokémon'
 'Little Bear Pokémon' 'Hibernator Pokémon' 'Lava Pokémon' 'Pig Pokémon'
 'Swine Pokémon' 'Coral Pokémon' 'Jet Pokémon' 'Delivery Pokémon'
 'Kite Pokémon' 'Armor Bird Pokémon' 'Dark Pokémon' 'Long Nose Pokémon'
 'Armor Pokémon' 'Big Horn Pokémon' 'Painter Pokémon' 'Scuffle Pokémon'
 'Handstand Pokémon' 'Kiss Pokémon' 'Live Coal Pokémon' 'Milk Cow Pokémon'
 'Thunder Pokémon' 'Aurora Pokémon' 'Rock Skin Pokémon'
 'Hard Shell Pokémon' 'Diving Pokémon' 'Rainbow Pokémon'
 'Time Travel Pokémon' 'Wood Gecko Pokémon' 'Forest Pokémon'
 'Chick Pokémon' 'Young Fowl Pokémon' 'Blaze Pokémon' 'Mud Fish Pokémon'
 'Bite Pokémon' 'Tiny Raccoon Pokémon' 'Rushing Pokémon'
 'Water Weed Pokémon' 'Jolly Pokémon' 'Carefree Pokémon' 'Acorn Pokémon'
 'Wily Pokémon' 'Wicked Pokémon' 'Tiny Swallow Pokémon' 'Swallow Pokémon'
 'Seagull Pokémon' 'Water Bird Pokémon' 'Feeling Pokémon'
 'Emotion Pokémon' 'Embrace Pokémon' 'Pond Skater Pokémon'
 'Eyeball Pokémon' 'Slacker Pokémon' 'Wild Monkey Pokémon' 'Lazy Pokémon'
 'Trainee Pokémon' 'Ninja Pokémon' 'Shed Pokémon' 'Whisper Pokémon'
 'Big Voice Pokémon' 'Loud Noise Pokémon' 'Guts Pokémon'
 'Arm Thrust Pokémon' 'Polka Dot Pokémon' 'Compass Pokémon'
 'Kitten Pokémon' 'Prim Pokémon' 'Deceiver Pokémon' 'Iron Armor Pokémon'
 'Meditate Pokémon' 'Discharge Pokémon' 'Cheering Pokémon'
 'Firefly Pokémon' 'Thorn Pokémon' 'Stomach Pokémon' 'Poison Bag Pokémon'
 'Savage Pokémon' 'Brutal Pokémon' 'Ball Whale Pokémon'
 'Float Whale Pokémon' 'Numb Pokémon' 'Eruption Pokémon' 'Coal Pokémon'
 'Bounce Pokémon' 'Manipulate Pokémon' 'Spot Panda Pokémon'
 'Ant Pit Pokémon' 'Vibration Pokémon' 'Cactus Pokémon'
 'Scarecrow Pokémon' 'Cotton Bird Pokémon' 'Humming Pokémon'
 'Cat Ferret Pokémon' 'Fang Snake Pokémon' 'Meteorite Pokémon'
 'Whiskers Pokémon' 'Ruffian Pokémon' 'Rogue Pokémon' 'Clay Doll Pokémon'
 'Sea Lily Pokémon' 'Barnacle Pokémon' 'Old Shrimp Pokémon'
 'Plate Pokémon' 'Tender Pokémon' 'Weather Pokémon' 'Color Swap Pokémon'
 'Puppet Pokémon' 'Marionette Pokémon' 'Requiem Pokémon' 'Beckon Pokémon'
 'Fruit Pokémon' 'Wind Chime Pokémon' 'Disaster Pokémon' 'Bright Pokémon'
 'Snow Hat Pokémon' 'Face Pokémon' 'Clap Pokémon' 'Ball Roll Pokémon'
 'Ice Break Pokémon' 'Deep Sea Pokémon' 'South Sea Pokémon'
 'Longevity Pokémon' 'Rendezvous Pokémon' 'Rock Head Pokémon'
 'Endurance Pokémon' 'Iron Ball Pokémon' 'Iron Claw Pokémon'
 'Iron Leg Pokémon' 'Rock Peak Pokémon' 'Iceberg Pokémon' 'Iron Pokémon'
 'Eon Pokémon' 'Sea Basin Pokémon' 'Continent Pokémon' 'Sky High Pokémon'
 'Wish Pokémon' 'DNA Pokémon' 'Tiny Leaf Pokémon' 'Grove Pokémon'
 'Chimp Pokémon' 'Playful Pokémon' 'Penguin Pokémon' 'Emperor Pokémon'
 'Starling Pokémon' 'Predator Pokémon' 'Plump Mouse Pokémon'
 'Beaver Pokémon' 'Cricket Pokémon' 'Flash Pokémon' 'Spark Pokémon'

<span style = "font-family: Verdana; font-size: 20px">

##### **CatchRate**
</span>

In [113]:
describe_feature(data, 'CatchRate')

- Type: int64
- First rows:
0    45
1    45
2    45
3    45
4    45
Name: CatchRate, dtype: int64
- Last rows:
795    3
796    3
797    3
798    3
799    3
Name: CatchRate, dtype: int64
- Number of missing values: 0
int64
- Number of distinct values: 33
- Unique value counts:
CatchRate
45     260
3       72
190     70
255     65
75      60
120     54
60      51
90      37
30      20
200     18
225     14
25      11
180     10
50       8
150      8
235      6
100      5
140      4
127      4
65       3
125      3
55       3
170      2
130      2
220      2
70       1
205      1
155      1
145      1
35       1
15       1
160      1
80       1
Name: count, dtype: int64
count    800.000000
mean      94.755000
std       75.716899
min        3.000000
25%       45.000000
50%       60.000000
75%      140.000000
max      255.000000
Name: CatchRate, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

##### **EggCycles**
</span>

In [114]:
describe_feature(data, 'EggCycles')

- Type: int64
- First rows:
0    20
1    20
2    20
3    20
4    20
Name: EggCycles, dtype: int64
- Last rows:
795     25
796     25
797    120
798    120
799    120
Name: EggCycles, dtype: int64
- Number of missing values: 0
int64
- Number of distinct values: 10
- Unique value counts:
EggCycles
20     449
15     112
25      61
120     53
40      43
30      26
10      21
80      17
35      15
5        3
Name: count, dtype: int64
count    800.000000
mean      28.943750
std       26.414489
min        5.000000
25%       20.000000
50%       20.000000
75%       25.000000
max      120.000000
Name: EggCycles, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

##### **EggGroup**
</span>

In [115]:
describe_feature(data, 'EggGroup')

- Type: object
- First rows:
0     ['Monster' 'Grass']
1     ['Monster' 'Grass']
2     ['Monster' 'Grass']
3     ['Monster' 'Grass']
4    ['Monster' 'Dragon']
Name: EggGroup, dtype: object
- Last rows:
795    []
796    []
797    []
798    []
799    []
Name: EggGroup, dtype: object
- Number of missing values: 0
object
- Number of distinct values: 59
- Unique value counts:
EggGroup
['Field']                     141
[]                             94
['Bug']                        60
['Amorphous']                  50
['Mineral']                    46
['Human-Like']                 39
['Flying']                     36
['Monster']                    21
['Monster' 'Dragon']           20
['Grass']                      19
['Fairy']                      17
['Water 1' 'Field']            17
['Monster' 'Water 1']          16
['Water 3']                    14
['Monster' 'Grass']            14
['Water 1']                    14
['Monster' 'Field']            14
['Field' 'Human-Like']         13
['Water 2']                    12
['Water 1' 'Water 3']          11
['Field' 'Fairy']              10
['Dragon']                     10
['Water 1' 'Dragon']           10
['Fairy' 'Grass']               9
['Human-Like' 'Amorphous']      6
['Water 1' 'Water 2']           6
['Field' 'Grass']               6
['Fairy' 'Mineral']             5
['Field' 'Dragon']              5
['Flying' 'Dragon']             5
['Water 1' 'Fairy']             4
['Water 1' 'Flying']            4
['Water 1' 'Grass']             3
['Bug' 'Mineral']               3
['Water 2' 'Dragon']            3
['Water 1' 'Amorphous']         3
['Bug' 'Dragon']                3
['Grass' 'Mineral']             2
['Grass' 'Amorphous']           2
['Flying' 'Water 3']            2
['Mineral' 'Amorphous']         2
['Grass' 'Fairy']               2
['Field' 'Flying']              2
['Bug' 'Water 3']               2
['Monster' 'Mineral']           2
['Water 2' 'Water 1']           2
['Grass' 'Human-Like']          2
['Bug' 'Grass']                 2
['Field' 'Water 2']             2
['Bug' 'Human-Like']            2
['Water 1' 'Bug']               2
['Flying' 'Fairy']              2
['Fairy' 'Amorphous']           1
['Dragon' 'Flying']             1
['Mineral' 'Bug']               1
['Flying' 'Field']              1
['Dragon' 'Monster']            1
['Flying' 'Human-Like']         1
['Ditto']                       1
Name: count, dtype: int64
- Unique values: ["['Monster' 'Grass']" "['Monster' 'Dragon']" "['Monster' 'Water 1']"
 "['Bug']" "['Flying']" "['Field']" "['Field' 'Dragon']"
 "['Field' 'Fairy']" "['Monster' 'Field']" '[]' "['Fairy']" "['Grass']"
 "['Bug' 'Grass']" "['Water 1' 'Field']" "['Water 1']" "['Human-Like']"
 "['Water 3']" "['Mineral']" "['Flying' 'Field']" "['Amorphous']"
 "['Monster']" "['Water 1' 'Dragon']" "['Water 2']" "['Water 2' 'Dragon']"
 "['Ditto']" "['Water 1' 'Water 3']" "['Flying' 'Dragon']"
 "['Flying' 'Fairy']" "['Water 1' 'Fairy']" "['Fairy' 'Grass']"
 "['Water 1' 'Water 2']" "['Water 1' 'Grass']" "['Field' 'Grass']"
 "['Water 1' 'Flying']" "['Human-Like' 'Amorphous']" "['Water 1' 'Bug']"
 "['Bug' 'Mineral']" "['Mineral' 'Bug']" "['Bug' 'Human-Like']"
 "['Field' 'Water 2']" "['Field' 'Human-Like']" "['Bug' 'Dragon']"
 "['Grass' 'Human-Like']" "['Dragon' 'Flying']" "['Water 2' 'Water 1']"
 "['Fairy' 'Amorphous']" "['Fairy' 'Mineral']" "['Dragon']"
 "['Water 1' 'Amorphous']" "['Bug' 'Water 3']" "['Field' 'Flying']"
 "['Grass' 'Fairy']" "['Mineral' 'Amorphous']" "['Flying' 'Water 3']"
 "['Grass' 'Mineral']" "['Dragon' 'Monster']" "['Flying' 'Human-Like']"
 "['Grass' 'Amorphous']" "['Monster' 'Mineral']"]

<span style = "font-family: Verdana; font-size: 20px">

Cột này sẽ được xử lý giống như với `Type`. Hơn nữa, có một số Pokémon không có nhóm trứng (Pokémon không thể phối giống, hoặc nhóm trứng không được phát hiện), ô trống này sẽ được thay thế bằng giá trị khác.

In [116]:
data['EggGroup'] = data['EggGroup'].str.rstrip(r'\"')
data['EggGroup'] = data['EggGroup'].str.lstrip(r'\"')
data['EggGroup'] = remove_first_last_letter(data['EggGroup'], '')
data['EggGroup1'] = get_first_element(data['EggGroup'])
data['EggGroup2'] = get_second_element(data['EggGroup'])
data.loc[data['EggGroup1'] == '', 'EggGroup1'] = 'No Eggs Discovered'
data.loc[data['EggGroup2'] == 'None', 'EggGroup2'] = 'No Eggs Discovered'

describe_feature(data, 'EggGroup1')
describe_feature(data, 'EggGroup2')
data = data.drop('EggGroup', axis=1)

- Type: object
- First rows:
0    Monster
1    Monster
2    Monster
3    Monster
4    Monster
Name: EggGroup1, dtype: object
- Last rows:
795    No Eggs Discovered
796    No Eggs Discovered
797    No Eggs Discovered
798    No Eggs Discovered
799    No Eggs Discovered
Name: EggGroup1, dtype: object
- Number of missing values: 0
object
- Number of distinct values: 15
- Unique value counts:
EggGroup1
Field                 179
No Eggs Discovered     94
Monster                87
Water 1                74
Bug                    72
Amorphous              50
Mineral                49
Flying                 47
Human-Like             45
Fairy                  32
Grass                  27
Water 2                17
Water 3                14
Dragon                 12
Ditto                   1
Name: count, dtype: int64
- Unique values: ['Monster' 'Bug' 'Flying' 'Field' 'No Eggs Discovered' 'Fairy' 'Grass'
 'Water 1' 'Human-Like' 'Water 3' 'Mineral' 'Amorphous' 'Water 2' 'Ditto'
 'Dragon']
- Type: object
- First rows:
0     Grass
1     Grass
2     Grass
3     Grass
4    Dragon
Name: EggGroup2, dtype: object
- Last rows:
795    No Eggs Discovered
796    No Eggs Discovered
797    No Eggs Discovered
798    No Eggs Discovered
799    No Eggs Discovered
Name: EggGroup2, dtype: object
- Number of missing values: 0
object
- Number of distinct values: 14
- Unique value counts:
EggGroup2
No Eggs Discovered    574
Dragon                 46
Grass                  34
Field                  32
Water 1                18
Fairy                  18
Human-Like             18
Water 3                15
Amorphous              14
Mineral                12
Water 2                 8
Flying                  7
Bug                     3
Monster                 1
Name: count, dtype: int64
- Unique values: ['Grass' 'Dragon' 'Water 1' 'No Eggs Discovered' 'Fairy' 'Field' 'Water 3'
 'Water 2' 'Flying' 'Amorphous' 'Bug' 'Mineral' 'Human-Like' 'Monster']

<span style = "font-family: Verdana; font-size: 20px">

##### **Leveling Rate**
</span>

In [117]:
describe_feature(data, 'LevelingRate')

- Type: object
- First rows:
0    Medium Slow
1    Medium Slow
2    Medium Slow
3    Medium Slow
4    Medium Slow
Name: LevelingRate, dtype: object
- Last rows:
795    Slow
796    Slow
797    Slow
798    Slow
799    Slow
Name: LevelingRate, dtype: object
- Number of missing values: 0
object
- Number of distinct values: 6
- Unique value counts:
LevelingRate
Medium Fast    320
Medium Slow    205
Slow           182
Fast            56
Erratic         23
Fluctuating     14
Name: count, dtype: int64
- Unique values: ['Medium Slow' 'Medium Fast' 'Fast' 'Slow' 'Fluctuating' 'Erratic']

<span style = "font-family: Verdana; font-size: 20px">

##### **Base Frienship**
</span>

In [118]:
describe_feature(data, 'BaseFriendship')

- Type: int64
- First rows:
0    70
1    70
2    70
3    70
4    70
Name: BaseFriendship, dtype: int64
- Last rows:
795     70
796      0
797    100
798    100
799    100
Name: BaseFriendship, dtype: int64
- Number of missing values: 0
int64
- Number of distinct values: 6
- Unique value counts:
BaseFriendship
70     649
35      80
0       33
100     17
140     11
90      10
Name: count, dtype: int64
count    800.000000
mean      65.462500
std       19.900531
min        0.000000
25%       70.000000
50%       70.000000
75%       70.000000
max      140.000000
Name: BaseFriendship, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

##### **IsLegendary**
</span>

In [119]:
describe_feature(data, 'IsLegendary')

- Type: int64
- First rows:
0    0
1    0
2    0
3    0
4    0
Name: IsLegendary, dtype: int64
- Last rows:
795    0
796    0
797    0
798    0
799    0
Name: IsLegendary, dtype: int64
- Number of missing values: 0
int64
- Number of distinct values: 2
- Unique value counts:
IsLegendary
0    749
1     51
Name: count, dtype: int64
count    800.00000
mean       0.06375
std        0.24446
min        0.00000
25%        0.00000
50%        0.00000
75%        0.00000
max        1.00000
Name: IsLegendary, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

##### **IsMythical**
</span>

In [120]:
describe_feature(data, 'IsMythical')

- Type: int64
- First rows:
0    0
1    0
2    0
3    0
4    0
Name: IsMythical, dtype: int64
- Last rows:
795    1
796    1
797    1
798    1
799    1
Name: IsMythical, dtype: int64
- Number of missing values: 0
int64
- Number of distinct values: 2
- Unique value counts:
IsMythical
0    776
1     24
Name: count, dtype: int64
count    800.000000
mean       0.030000
std        0.170694
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max        1.000000
Name: IsMythical, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

##### **IsUltraBeast**
</span>

In [121]:
describe_feature(data, 'IsUltraBeast')

- Type: int64
- First rows:
0    0
1    0
2    0
3    0
4    0
Name: IsUltraBeast, dtype: int64
- Last rows:
795    0
796    0
797    0
798    0
799    0
Name: IsUltraBeast, dtype: int64
- Number of missing values: 0
int64
- Number of distinct values: 1
- Unique value counts:
IsUltraBeast
0    800
Name: count, dtype: int64
count    800.0
mean       0.0
std        0.0
min        0.0
25%        0.0
50%        0.0
75%        0.0
max        0.0
Name: IsUltraBeast, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

Có vẻ là không có Pokémon siêu thú nào trong bộ dữ liệu này, nên cột này có thể bị loại bỏ.

In [122]:
data = data.drop('IsUltraBeast', axis=1)

<span style = "font-family: Verdana; font-size: 20px">

##### **HasMega**
</span>

In [123]:
describe_feature(data, 'HasMega')

- Type: int64
- First rows:
0    0
1    0
2    1
3    1
4    0
Name: HasMega, dtype: int64
- Last rows:
795    1
796    1
797    0
798    0
799    0
Name: HasMega, dtype: int64
- Number of missing values: 0
int64
- Number of distinct values: 2
- Unique value counts:
HasMega
0    696
1    104
Name: count, dtype: int64
count    800.000000
mean       0.130000
std        0.336514
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max        1.000000
Name: HasMega, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

Thêm một cột để biểu thị Pokémon đó có ở trong dạng tiến hoá Mega hay không.

In [124]:
data['IsMega'] = 0
data.loc[data['Name'].str.startswith('Mega ', na=False), 'IsMega'] = 1

In [125]:
describe_feature(data, 'IsMega')

- Type: int64
- First rows:
0    0
1    0
2    0
3    1
4    0
Name: IsMega, dtype: int64
- Last rows:
795    0
796    1
797    0
798    0
799    0
Name: IsMega, dtype: int64
- Number of missing values: 0
int64
- Number of distinct values: 2
- Unique value counts:
IsMega
0    752
1     48
Name: count, dtype: int64
count    800.000000
mean       0.060000
std        0.237635
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max        1.000000
Name: IsMega, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

##### **EvoStage**
</span>

In [126]:
describe_feature(data, 'EvoStage')

- Type: int64
- First rows:
0    1
1    2
2    3
3    3
4    1
Name: EvoStage, dtype: int64
- Last rows:
795    1
796    1
797    1
798    1
799    1
Name: EvoStage, dtype: int64
- Number of missing values: 0
int64
- Number of distinct values: 3
- Unique value counts:
EvoStage
1    403
2    287
3    110
Name: count, dtype: int64
count    800.000000
mean       1.633750
std        0.712563
min        1.000000
25%        1.000000
50%        1.000000
75%        2.000000
max        3.000000
Name: EvoStage, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

Cột này cho biết bậc tiến hoá hiện tại của mỗi Pokémon, giá trị có thể có là `1` (cho bậc tiến hoá đầu tiên), lần lượt là `2` và `3`. Pokémon không có tiến hoá sẽ có giá trị là `1`. Vấn đề có thể có là EvoStage có giá trị lớn hơn TotalEvoStages.

In [127]:
data.loc[data['EvoStage'] > data['TotalEvoStages']]

,ID,Name,Type 1,Type 2,HiddenAbility,Generation,Hp,Attack,Defense,SpecialAttack,SpecialDefense,Speed,TotalStats,Weight,Height,GenderProbM,Category,CatchRate,EggCycles,LevelingRate,BaseFriendship,IsLegendary,IsMythical,HasMega,EvoStage,TotalEvoStages,PreevoName,DamageFromNormal,DamageFromFighting,DamageFromFlying,DamageFromPoison,DamageFromGround,DamageFromRock,DamageFromBug,DamageFromGhost,DamageFromSteel,DamageFromFire,DamageFromWater,DamageFromGrass,DamageFromElectric,DamageFromPsychic,DamageFromIce,DamageFromDragon,DamageFromDark,DamageFromFairy,Ability 1,Ability 2,NoGender,EggGroup1,EggGroup2,IsMega
316,317,Shedinja,Bug,Ghost,None,3,1.0,90.0,45.0,30.0,30.0,40.0,236.0,1.2,0.8,0.5,Shed Pokémon,45,15,Erratic,70,0,0,0,3,2,Ninjask,0.0,0.0,2.0,0.5,0.5,2.0,0.5,2.0,1.0,2.0,1.0,0.5,1.0,1.0,1.0,1.0,2.0,1.0,Wonder Guard,None,1,Mineral,Bug,0

In [128]:
data.loc[data['EvoStage'] > data['TotalEvoStages'], 'EvoStage'] = data['TotalEvoStages']
data.loc[data['EvoStage'] > data['TotalEvoStages']]

Empty DataFrame
Columns: [ID, Name, Type 1, Type 2, HiddenAbility, Generation, Hp, Attack, Defense, SpecialAttack, SpecialDefense, Speed, TotalStats, Weight, Height, GenderProbM, Category, CatchRate, EggCycles, LevelingRate, BaseFriendship, IsLegendary, IsMythical, HasMega, EvoStage, TotalEvoStages, PreevoName, DamageFromNormal, DamageFromFighting, DamageFromFlying, DamageFromPoison, DamageFromGround, DamageFromRock, DamageFromBug, DamageFromGhost, DamageFromSteel, DamageFromFire, DamageFromWater, DamageFromGrass, DamageFromElectric, DamageFromPsychic, DamageFromIce, DamageFromDragon, DamageFromDark, DamageFromFairy, Ability 1, Ability 2, NoGender, EggGroup1, EggGroup2, IsMega]
Index: []

<span style = "font-family: Verdana; font-size: 20px">

##### **TotalEvoStages**
</span>

In [129]:
describe_feature(data, 'TotalEvoStages')

- Type: int64
- First rows:
0    3
1    3
2    3
3    3
4    3
Name: TotalEvoStages, dtype: int64
- Last rows:
795    1
796    1
797    1
798    1
799    1
Name: TotalEvoStages, dtype: int64
- Number of missing values: 0
int64
- Number of distinct values: 3
- Unique value counts:
TotalEvoStages
2    370
3    286
1    144
Name: count, dtype: int64
count    800.000000
mean       2.177500
std        0.711777
min        1.000000
25%        2.000000
50%        2.000000
75%        3.000000
max        3.000000
Name: TotalEvoStages, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

##### **PreevoName**
</span>

In [130]:
describe_feature(data, 'PreevoName')

- Type: object
- First rows:
0    No Preevolution
1          Bulbasaur
2            Ivysaur
3           Venusaur
4    No Preevolution
Name: PreevoName, dtype: object
- Last rows:
795    No Preevolution
796            Diancie
797    No Preevolution
798    No Preevolution
799    No Preevolution
Name: PreevoName, dtype: object
- Number of missing values: 0
object
- Number of distinct values: 393
- Unique value counts:
PreevoName
No Preevolution           387
Eevee                       8
Tyrogue                     3
Mewtwo                      2
Wurmple                     2
Kirlia                      2
Poliwhirl                   2
Gloom                       2
Darumaka                    2
Espurr                      2
Doublade                    2
Slowpoke                    2
Snorunt                     2
Clamperl                    2
Charizard                   2
Dewott                      1
Pansear                     1
Magneton                    1
Sneasel                     1
Abomasnow                   1
Snover                      1
Finneon                     1
Croagunk                    1
Pansage                     1
Hippopotas                  1
Skorupi                     1
Lucario                     1
Riolu                       1
Garchomp                    1
Gabite                      1
Gible                       1
Bronzor                     1
Stunky                      1
Panpour                     1
Lickitung                   1
Rhydon                      1
Oshawott                    1
Lillipup                    1
Pignite                     1
Patrat                      1
Tepig                       1
Servine                     1
Snivy                       1
Dusclops                    1
Nosepass                    1
Gallade                     1
Herdier                     1
Tangela                     1
Porygon2                    1
Purrloin                    1
Piloswine                   1
Glameow                     1
Yanma                       1
Togetic                     1
Magmar                      1
Electabuzz                  1
Gligar                      1
Buneary                     1
Murkrow                     1
Metang                      1
Chimchar                    1
Grotle                      1
Turtwig                     1
Rayquaza                    1
Groudon                     1
Kyogre                      1
Latios                      1
Latias                      1
Metagross                   1
Beldum                      1
Piplup                      1
Salamence                   1
Shelgon                     1
Bagon                       1
Sealeo                      1
Spheal                      1
Glalie                      1
Absol                       1
Chingling                   1
Duskull                     1
Monferno                    1
Prinplup                    1
Misdreavus                  1
Burmy Trash Cloak           1
Lopunny                     1
Pidove                      1
Drifloon                    1
Aipom                       1
Shellos West Sea            1
Cherubi                     1
Buizel                      1
Combee                      1
Burmy                       1
Burmy Sandy Cloak           1
Starly                      1
Burmy Plant Cloak           1
Shieldon                    1
Cranidos                    1
Roselia                     1
Luxio                       1
Shinx                       1
Kricketot                   1
Bidoof                      1
Staravia                    1
Munna                       1
Drilbur                     1
Tranquill                   1
Quilladin                   1
Spewpa                      1
Scatterbug                  1
Fletchinder                 1
Fletchling                  1
Bunnelby                    1
Frogadier                   1
Froakie                     1
Braixen                     1
Fennekin                    1
Chespin                     1
Flabébé                     1
Larvesta                    1
Zweilous                    1
Deino                       1
Vullaby                     1
Rufflet                     1
Pawniard                    1
Golett                      1
Mienfoo                     1
Shelmet                     1
Litleo                      1
Floette                     1
Fraxure                     1
Amaura                      1
Noibat                      1
Bergmite                    1
Pumpkaboo Super Size        1
Pumpkaboo Large Size        1
Pumpkaboo Small Size        1
Pumpkaboo Average Size      1
Phantump                    1
Sliggoo                     1
Goomy                       1
Tyrunt                      1
Skiddo                      1
Helioptile                  1
Clauncher                   1
Skrelp                      1
Binacle                     1
Inkay                       1
Swirlix                     1
Spritzee                    1
Honedge                     1
Pancham                     1
Cubchoo                     1
Axew                        1
Blitzle                     1
Swadloon                    1
Yamask                      1
Scraggy                     1
Dwebble                     1
Krokorok                    1
Sandile                     1
Petilil                     1
Cottonee                    1
Whirlipede                  1
Venipede                    1
Sewaddle                    1
Archen                      1
Palpitoad                   1
Tympole                     1
Gurdurr                     1
Timburr                     1
Audino                      1
Shuppet                     1
Woobat                      1
Boldore                     1
Roggenrola                  1
Tirtouga                    1
Trubbish                    1
Lampent                     1
Foongus                     1
Litwick                     1
Elgyem                      1
Eelektrik                   1
Tynamo                      1
Klang                       1
Klink                       1
Ferroseed                   1
Joltik                      1
Frillish                    1
Karrablast                  1
Zorua                       1
Deerling Spring Form        1
Vanillish                   1
Vanillite                   1
Ducklett                    1
Duosion                     1
Solosis                     1
Gothorita                   1
Gothita                     1
Minccino                    1
Banette                     1
Corphish                    1
Feebas                      1
Haunter                     1
Happiny                     1
Rhyhorn                     1
Koffing                     1
Cubone                      1
Exeggcute                   1
Voltorb                     1
Krabby                      1
Drowzee                     1
Gengar                      1
Gastly                      1
Horsea                      1
Shellder                    1
Grimer                      1
Seel                        1
Doduo                       1
Magnemite                   1
Slowbro                     1
Ponyta                      1
Graveler                    1
Geodude                     1
Kangaskhan                  1
Goldeen                     1
Weepinbell                  1
Munchlax                    1
Sentret                     1
Croconaw                    1
Totodile                    1
Quilava                     1
Cyndaquil                   1
Bayleef                     1
Chikorita                   1
Dragonair                   1
Dratini                     1
Aerodactyl                  1
Staryu                      1
Kabuto                      1
Omanyte                     1
Gyarados                    1
Magikarp                    1
Pinsir                      1
Magby                       1
Elekid                      1
Smoochum                    1
Mime Jr.                    1
Tentacool                   1
Bellsprout                  1
Ledyba                      1
Kakuna                      1
Pikachu                     1
Pichu                       1
Ekans                       1
Spearow                     1
Rattata                     1
Pidgeot                     1
Pidgeotto                   1
Pidgey                      1
Beedrill                    1
Weedle                      1
Nidoran♀                    1
Metapod                     1
Caterpie                    1
Blastoise                   1
Wartortle                   1
Squirtle                    1
Charmeleon                  1
Charmander                  1
Venusaur                    1
Ivysaur                     1
Sandshrew                   1
Nidorina                    1
Machoke                     1
Diglett                     1
Machop                      1
Alakazam                    1
Kadabra                     1
Abra                        1
Poliwag                     1
Growlithe                   1
Mankey                      1
Psyduck                     1
Meowth                      1
Venonat                     1
Nidoran♂                    1
Paras                       1
Oddish                      1
Zubat                       1
Jigglypuff                  1
Igglybuff                   1
Vulpix                      1
Clefairy                    1
Cleffa                      1
Nidorino                    1
Hoothoot                    1
Spinarak                    1
Anorith                     1
Slakoth                     1
Mawile                      1
Sableye                     1
Skitty                      1
Makuhita                    1
Loudred                     1
Whismur                     1
Ninjask                     1
Nincada                     1
Vigoroth                    1
Shroomish                   1
Lairon                      1
Surskit                     1
Gardevoir                   1
Ralts                       1
Wingull                     1
Taillow                     1
Nuzleaf                     1
Seedot                      1
Lombre                      1
Lotad                       1
Aron                        1
Aggron                      1
Silcoon                     1
Spoink                      1
Lileep                      1
Baltoy                      1
Bulbasaur                   1
Barboach                    1
Altaria                     1
Swablu                      1
Cacnea                      1
Vibrava                     1
Trapinch                    1
Camerupt                    1
Meditite                    1
Numel                       1
Wailmer                     1
Sharpedo                    1
Carvanha                    1
Gulpin                      1
Budew                       1
Manectric                   1
Electrike                   1
Medicham                    1
Cascoon                     1
Zigzagoon                   1
Golbat                      1
Skiploom                    1
Scizor                      1
Scyther                     1
Snubbull                    1
Steelix                     1
Onix                        1
Pineco                      1
Wynaut                      1
Wooper                      1
Sunkern                     1
Hoppip                      1
Teddiursa                   1
Bonsly                      1
Marill                      1
Azurill                     1
Ampharos                    1
Flaaffy                     1
Mareep                      1
Natu                        1
Togepi                      1
Chinchou                    1
Heracross                   1
Slugma                      1
Poochyena                   1
Tyranitar                   1
Swampert                    1
Marshtomp                   1
Mudkip                      1
Blaziken                    1
Combusken                   1
Torchic                     1
Sceptile                    1
Grovyle                     1
Treecko                     1
Pupitar                     1
Swinub                      1
Larvitar                    1
Chansey                     1
Porygon                     1
Phanpy                      1
Seadra                      1
Houndoom                    1
Houndour                    1
Mantyke                     1
Remoraid                    1
Diancie                     1
Name: count, dtype: int64
- Unique values: ['No Preevolution' 'Bulbasaur' 'Ivysaur' 'Venusaur' 'Charmander'
 'Charmeleon' 'Charizard' 'Squirtle' 'Wartortle' 'Blastoise' 'Caterpie'
 'Metapod' 'Weedle' 'Kakuna' 'Beedrill' 'Pidgey' 'Pidgeotto' 'Pidgeot'
 'Rattata' 'Spearow' 'Ekans' 'Pichu' 'Pikachu' 'Sandshrew' 'Nidoran♀'
 'Nidorina' 'Nidoran♂' 'Nidorino' 'Cleffa' 'Clefairy' 'Vulpix' 'Igglybuff'
 'Jigglypuff' 'Zubat' 'Oddish' 'Gloom' 'Paras' 'Venonat' 'Diglett'
 'Meowth' 'Psyduck' 'Mankey' 'Growlithe' 'Poliwag' 'Poliwhirl' 'Abra'
 'Kadabra' 'Alakazam' 'Machop' 'Machoke' 'Bellsprout' 'Weepinbell'
 'Tentacool' 'Geodude' 'Graveler' 'Ponyta' 'Slowpoke' 'Slowbro'
 'Magnemite' 'Doduo' 'Seel' 'Grimer' 'Shellder' 'Gastly' 'Haunter'
 'Gengar' 'Drowzee' 'Krabby' 'Voltorb' 'Exeggcute' 'Cubone' 'Tyrogue'
 'Koffing' 'Rhyhorn' 'Happiny' 'Kangaskhan' 'Horsea' 'Goldeen' 'Staryu'
 'Mime Jr.' 'Smoochum' 'Elekid' 'Magby' 'Pinsir' 'Magikarp' 'Gyarados'
 'Eevee' 'Omanyte' 'Kabuto' 'Aerodactyl' 'Munchlax' 'Dratini' 'Dragonair'
 'Mewtwo' 'Chikorita' 'Bayleef' 'Cyndaquil' 'Quilava' 'Totodile'
 'Croconaw' 'Sentret' 'Hoothoot' 'Ledyba' 'Spinarak' 'Golbat' 'Chinchou'
 'Togepi' 'Natu' 'Mareep' 'Flaaffy' 'Ampharos' 'Azurill' 'Marill' 'Bonsly'
 'Hoppip' 'Skiploom' 'Sunkern' 'Wooper' 'Wynaut' 'Pineco' 'Onix' 'Steelix'
 'Snubbull' 'Scyther' 'Scizor' 'Heracross' 'Teddiursa' 'Slugma' 'Swinub'
 'Remoraid' 'Mantyke' 'Houndour' 'Houndoom' 'Seadra' 'Phanpy' 'Porygon'
 'Chansey' 'Larvitar' 'Pupitar' 'Tyranitar' 'Treecko' 'Grovyle' 'Sceptile'
 'Torchic' 'Combusken' 'Blaziken' 'Mudkip' 'Marshtomp' 'Swampert'
 'Poochyena' 'Zigzagoon' 'Wurmple' 'Silcoon' 'Cascoon' 'Lotad' 'Lombre'
 'Seedot' 'Nuzleaf' 'Taillow' 'Wingull' 'Ralts' 'Kirlia' 'Gardevoir'
 'Surskit' 'Shroomish' 'Slakoth' 'Vigoroth' 'Nincada' 'Ninjask' 'Whismur'
 'Loudred' 'Makuhita' 'Skitty' 'Sableye' 'Mawile' 'Aron' 'Lairon' 'Aggron'
 'Meditite' 'Medicham' 'Electrike' 'Manectric' 'Budew' 'Gulpin' 'Carvanha'
 'Sharpedo' 'Wailmer' 'Numel' 'Camerupt' 'Spoink' 'Trapinch' 'Vibrava'
 'Cacnea' 'Swablu' 'Altaria' 'Barboach' 'Corphish' 'Baltoy' 'Lileep'
 'Anorith' 'Feebas' 'Shuppet' 'Banette' 'Duskull' 'Chingling' 'Absol'
 'Snorunt' 'Glalie' 'Spheal' 'Sealeo' 'Clamperl' 'Bagon' 'Shelgon'
 'Salamence' 'Beldum' 'Metang' 'Metagross' 'Latias' 'Latios' 'Kyogre'
 'Groudon' 'Rayquaza' 'Turtwig' 'Grotle' 'Chimchar' 'Monferno' 'Piplup'
 'Prinplup' 'Starly' 'Staravia' 'Bidoof' 'Kricketot' 'Shinx' 'Luxio'
 'Roselia' 'Cranidos' 'Shieldon' 'Burmy Plant Cloak' 'Burmy Sandy Cloak'
 'Burmy Trash Cloak' 'Burmy' 'Combee' 'Buizel' 'Cherubi'
 'Shellos West Sea' 'Aipom' 'Drifloon' 'Buneary' 'Lopunny' 'Misdreavus'
 'Murkrow' 'Glameow' 'Stunky' 'Bronzor' 'Gible' 'Gabite' 'Garchomp'
 'Riolu' 'Lucario' 'Hippopotas' 'Skorupi' 'Croagunk' 'Finneon' 'Snover'
 'Abomasnow' 'Sneasel' 'Magneton' 'Lickitung' 'Rhydon' 'Tangela'
 'Electabuzz' 'Magmar' 'Togetic' 'Yanma' 'Gligar' 'Piloswine' 'Porygon2'
 'Gallade' 'Nosepass' 'Dusclops' 'Snivy' 'Servine' 'Tepig' 'Pignite'
 'Oshawott' 'Dewott' 'Patrat' 'Lillipup' 'Herdier' 'Purrloin' 'Pansage'
 'Pansear' 'Panpour' 'Munna' 'Pidove' 'Tranquill' 'Blitzle' 'Roggenrola'
 'Boldore' 'Woobat' 'Drilbur' 'Audino' 'Timburr' 'Gurdurr' 'Tympole'
 'Palpitoad' 'Sewaddle' 'Swadloon' 'Venipede' 'Whirlipede' 'Cottonee'
 'Petilil' 'Sandile' 'Krokorok' 'Darumaka' 'Dwebble' 'Scraggy' 'Yamask'
 'Tirtouga' 'Archen' 'Trubbish' 'Zorua' 'Minccino' 'Gothita' 'Gothorita'
 'Solosis' 'Duosion' 'Ducklett' 'Vanillite' 'Vanillish'
 'Deerling Spring Form' 'Karrablast' 'Foongus' 'Frillish' 'Joltik'
 'Ferroseed' 'Klink' 'Klang' 'Tynamo' 'Eelektrik' 'Elgyem' 'Litwick'
 'Lampent' 'Axew' 'Fraxure' 'Cubchoo' 'Shelmet' 'Mienfoo' 'Golett'
 'Pawniard' 'Rufflet' 'Vullaby' 'Deino' 'Zweilous' 'Larvesta' 'Chespin'
 'Quilladin' 'Fennekin' 'Braixen' 'Froakie' 'Frogadier' 'Bunnelby'
 'Fletchling' 'Fletchinder' 'Scatterbug' 'Spewpa' 'Litleo' 'Flabébé'
 'Floette' 'Skiddo' 'Pancham' 'Espurr' 'Honedge' 'Doublade' 'Spritzee'
 'Swirlix' 'Inkay' 'Binacle' 'Skrelp' 'Clauncher' 'Helioptile' 'Tyrunt'
 'Amaura' 'Goomy' 'Sliggoo' 'Phantump' 'Pumpkaboo Average Size'
 'Pumpkaboo Small Size' 'Pumpkaboo Large Size' 'Pumpkaboo Super Size'
 'Bergmite' 'Noibat' 'Diancie']

<span style = "font-family: Verdana; font-size: 20px">

##### **DamageFromNormal**
</span>

In [131]:
describe_feature(data, 'DamageFromNormal')

- Type: float64
- First rows:
0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
Name: DamageFromNormal, dtype: float64
- Last rows:
795    0.5
796    0.5
797    0.0
798    1.0
799    1.0
Name: DamageFromNormal, dtype: float64
- Number of missing values: 0
float64
- Number of distinct values: 4
- Unique value counts:
DamageFromNormal
1.00    657
0.50     91
0.00     46
0.25      6
Name: count, dtype: int64
count    800.000000
mean       0.880000
std        0.275411
min        0.000000
25%        1.000000
50%        1.000000
75%        1.000000
max        1.000000
Name: DamageFromNormal, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

##### **DamageFromFighting**
</span>

In [132]:
describe_feature(data, 'DamageFromFighting')

- Type: float64
- First rows:
0    0.5
1    0.5
2    0.5
3    0.5
4    1.0
Name: DamageFromFighting, dtype: float64
- Last rows:
795    1.0
796    1.0
797    0.0
798    1.0
799    1.0
Name: DamageFromFighting, dtype: float64
- Number of missing values: 0
float64
- Number of distinct values: 7
- Unique value counts:
DamageFromFighting
1.00    321
0.50    192
2.00    182
0.00     46
0.25     44
4.00     14
1.50      1
Name: count, dtype: int64
count    800.000000
mean       1.061875
std        0.728412
min        0.000000
25%        0.500000
50%        1.000000
75%        1.000000
max        4.000000
Name: DamageFromFighting, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

##### **DamageFromFlying**
</span>

In [133]:
describe_feature(data, 'DamageFromFlying')

- Type: float64
- First rows:
0    2.0
1    2.0
2    2.0
3    2.0
4    1.0
Name: DamageFromFlying, dtype: float64
- Last rows:
795    0.5
796    0.5
797    1.0
798    1.0
799    1.0
Name: DamageFromFlying, dtype: float64
- Number of missing values: 0
float64
- Number of distinct values: 5
- Unique value counts:
DamageFromFlying
1.00    489
2.00    175
0.50    116
4.00     11
0.25      9
Name: count, dtype: int64
count    800.000000
mean       1.179062
std        0.594522
min        0.250000
25%        1.000000
50%        1.000000
75%        1.000000
max        4.000000
Name: DamageFromFlying, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

##### **DamageFromPoison**
</span>

In [134]:
describe_feature(data, 'DamageFromPoison')

- Type: float64
- First rows:
0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
Name: DamageFromPoison, dtype: float64
- Last rows:
795    1.0
796    1.0
797    0.5
798    1.0
799    1.0
Name: DamageFromPoison, dtype: float64
- Number of missing values: 0
float64
- Number of distinct values: 6
- Unique value counts:
DamageFromPoison
1.00    482
0.50    155
2.00     95
0.00     49
0.25     17
4.00      2
Name: count, dtype: int64
count    800.000000
mean       0.952187
std        0.510814
min        0.000000
25%        0.500000
50%        1.000000
75%        1.000000
max        4.000000
Name: DamageFromPoison, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

##### **DamageFromGround**
</span>

In [135]:
describe_feature(data, 'DamageFromGround')

- Type: float64
- First rows:
0    1.0
1    1.0
2    1.0
3    1.0
4    2.0
Name: DamageFromGround, dtype: float64
- Last rows:
795    2.0
796    2.0
797    1.0
798    1.0
799    2.0
Name: DamageFromGround, dtype: float64
- Number of missing values: 0
float64
- Number of distinct values: 7
- Unique value counts:
DamageFromGround
1.00    400
2.00    190
0.00    104
0.50     87
4.00     12
0.25      6
1.50      1
Name: count, dtype: int64
count    800.000000
mean       1.093125
std        0.725399
min        0.000000
25%        1.000000
50%        1.000000
75%        2.000000
max        4.000000
Name: DamageFromGround, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

##### **DamageFromRock**
</span>

In [136]:
describe_feature(data, 'DamageFromRock')

- Type: float64
- First rows:
0    1.0
1    1.0
2    1.0
3    1.0
4    2.0
Name: DamageFromRock, dtype: float64
- Last rows:
795    1.0
796    1.0
797    1.0
798    1.0
799    2.0
Name: DamageFromRock, dtype: float64
- Number of missing values: 0
float64
- Number of distinct values: 5
- Unique value counts:
DamageFromRock
1.00    449
2.00    196
0.50    126
4.00     24
0.25      5
Name: count, dtype: int64
count    800.000000
mean       1.251562
std        0.703723
min        0.250000
25%        1.000000
50%        1.000000
75%        2.000000
max        4.000000
Name: DamageFromRock, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

##### **DamageFromBug**
</span>

In [137]:
describe_feature(data, 'DamageFromBug')

- Type: float64
- First rows:
0    1.0
1    1.0
2    1.0
3    1.0
4    0.5
Name: DamageFromBug, dtype: float64
- Last rows:
795    0.5
796    0.5
797    1.0
798    4.0
799    0.5
Name: DamageFromBug, dtype: float64
- Number of missing values: 0
float64
- Number of distinct values: 5
- Unique value counts:
DamageFromBug
1.00    370
0.50    248
2.00    132
0.25     41
4.00      9
Name: count, dtype: int64
count    800.000000
mean       1.005313
std        0.610750
min        0.250000
25%        0.500000
50%        1.000000
75%        1.000000
max        4.000000
Name: DamageFromBug, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

##### **DamageFromGhost**
</span>

In [138]:
describe_feature(data, 'DamageFromGhost')

- Type: float64
- First rows:
0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
Name: DamageFromGhost, dtype: float64
- Last rows:
795    1.0
796    1.0
797    4.0
798    1.0
799    1.0
Name: DamageFromGhost, dtype: float64
- Number of missing values: 0
float64
- Number of distinct values: 5
- Unique value counts:
DamageFromGhost
1.0    527
2.0    126
0.0    102
0.5     44
4.0      1
Name: count, dtype: int64
count    800.00000
mean       1.00625
std        0.55709
min        0.00000
25%        1.00000
50%        1.00000
75%        1.00000
max        4.00000
Name: DamageFromGhost, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

##### **DamageFromSteel**
</span>

In [139]:
describe_feature(data, 'DamageFromSteel')

- Type: float64
- First rows:
0    1.0
1    1.0
2    1.0
3    1.0
4    0.5
Name: DamageFromSteel, dtype: float64
- Last rows:
795    4.00
796    4.00
797    1.00
798    1.00
799    0.25
Name: DamageFromSteel, dtype: float64
- Number of missing values: 0
float64
- Number of distinct values: 5
- Unique value counts:
DamageFromSteel
1.00    450
0.50    239
2.00     96
0.25     10
4.00      5
Name: count, dtype: int64
count    800.00000
mean       0.98000
std        0.50783
min        0.25000
25%        0.50000
50%        1.00000
75%        1.00000
max        4.00000
Name: DamageFromSteel, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

##### **DamageFromFire**
</span>

In [140]:
describe_feature(data, 'DamageFromFire')

- Type: float64
- First rows:
0    2.0
1    2.0
2    2.0
3    1.0
4    0.5
Name: DamageFromFire, dtype: float64
- Last rows:
795    0.50
796    0.50
797    1.00
798    1.00
799    0.25
Name: DamageFromFire, dtype: float64
- Number of missing values: 0
float64
- Number of distinct values: 6
- Unique value counts:
DamageFromFire
1.00    353
0.50    228
2.00    182
0.25     18
4.00     18
1.50      1
Name: count, dtype: int64
count    800.000000
mean       1.136250
std        0.704468
min        0.250000
25%        0.500000
50%        1.000000
75%        1.625000
max        4.000000
Name: DamageFromFire, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

##### **DamageFromWater**
</span>

In [141]:
describe_feature(data, 'DamageFromWater')

- Type: float64
- First rows:
0    0.5
1    0.5
2    0.5
3    0.5
4    2.0
Name: DamageFromWater, dtype: float64
- Last rows:
795    2.0
796    2.0
797    1.0
798    1.0
799    1.0
Name: DamageFromWater, dtype: float64
- Number of missing values: 0
float64
- Number of distinct values: 5
- Unique value counts:
DamageFromWater
1.00    430
0.50    224
2.00    126
4.00     14
0.25      6
Name: count, dtype: int64
count    800.000000
mean       1.064375
std        0.620932
min        0.250000
25%        0.500000
50%        1.000000
75%        1.000000
max        4.000000
Name: DamageFromWater, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

##### **DamageFromGrass**
</span>

In [142]:
describe_feature(data, 'DamageFromGrass')

- Type: float64
- First rows:
0    0.25
1    0.25
2    0.25
3    0.25
4    0.50
Name: DamageFromGrass, dtype: float64
- Last rows:
795    2.0
796    2.0
797    1.0
798    1.0
799    1.0
Name: DamageFromGrass, dtype: float64
- Number of missing values: 0
float64
- Number of distinct values: 5
- Unique value counts:
DamageFromGrass
1.00    298
0.50    255
2.00    130
0.25     88
4.00     29
Name: count, dtype: int64
count    800.000000
mean       1.029375
std        0.793875
min        0.250000
25%        0.500000
50%        1.000000
75%        1.000000
max        4.000000
Name: DamageFromGrass, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

##### **DamageFromElectric**
</span>

In [143]:
describe_feature(data, 'DamageFromElectric')

- Type: float64
- First rows:
0    0.5
1    0.5
2    0.5
3    0.5
4    1.0
Name: DamageFromElectric, dtype: float64
- Last rows:
795    1.0
796    1.0
797    1.0
798    1.0
799    2.0
Name: DamageFromElectric, dtype: float64
- Number of missing values: 0
float64
- Number of distinct values: 6
- Unique value counts:
DamageFromElectric
1.00    397
2.00    172
0.50    152
0.00     68
4.00      8
0.25      3
Name: count, dtype: int64
count    800.000000
mean       1.062188
std        0.660521
min        0.000000
25%        0.500000
50%        1.000000
75%        1.000000
max        4.000000
Name: DamageFromElectric, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

##### **DamageFromPsychic**
</span>

In [144]:
describe_feature(data, 'DamageFromPsychic')

- Type: float64
- First rows:
0    2.0
1    2.0
2    2.0
3    2.0
4    1.0
Name: DamageFromPsychic, dtype: float64
- Last rows:
795    1.0
796    1.0
797    0.5
798    0.0
799    1.0
Name: DamageFromPsychic, dtype: float64
- Number of missing values: 0
float64
- Number of distinct values: 6
- Unique value counts:
DamageFromPsychic
1.00    534
0.50    111
2.00     96
0.00     50
0.25      7
4.00      2
Name: count, dtype: int64
count    800.000000
mean       0.989062
std        0.494768
min        0.000000
25%        1.000000
50%        1.000000
75%        1.000000
max        4.000000
Name: DamageFromPsychic, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

##### **DamageFromIce**
</span>

In [145]:
describe_feature(data, 'DamageFromIce')

- Type: float64
- First rows:
0    2.0
1    2.0
2    2.0
3    1.0
4    0.5
Name: DamageFromIce, dtype: float64
- Last rows:
795    1.00
796    1.00
797    1.00
798    1.00
799    0.25
Name: DamageFromIce, dtype: float64
- Number of missing values: 0
float64
- Number of distinct values: 5
- Unique value counts:
DamageFromIce
1.00    351
2.00    208
0.50    206
4.00     26
0.25      9
Name: count, dtype: int64
count    800.000000
mean       1.220312
std        0.758541
min        0.250000
25%        0.500000
50%        1.000000
75%        2.000000
max        4.000000
Name: DamageFromIce, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

##### **DamageFromDragon**
</span>

In [146]:
describe_feature(data, 'DamageFromDragon')

- Type: float64
- First rows:
0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
Name: DamageFromDragon, dtype: float64
- Last rows:
795    0.0
796    0.0
797    1.0
798    1.0
799    1.0
Name: DamageFromDragon, dtype: float64
- Number of missing values: 0
float64
- Number of distinct values: 4
- Unique value counts:
DamageFromDragon
1.0    667
2.0     48
0.5     45
0.0     40
Name: count, dtype: int64
count    800.000000
mean       0.981875
std        0.351978
min        0.000000
25%        1.000000
50%        1.000000
75%        1.000000
max        2.000000
Name: DamageFromDragon, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

##### **DamageFromDark**
</span>

In [147]:
describe_feature(data, 'DamageFromDark')

- Type: float64
- First rows:
0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
Name: DamageFromDark, dtype: float64
- Last rows:
795    0.5
796    0.5
797    4.0
798    1.0
799    1.0
Name: DamageFromDark, dtype: float64
- Number of missing values: 0
float64
- Number of distinct values: 5
- Unique value counts:
DamageFromDark
1.00    561
0.50    119
2.00    116
0.25      3
4.00      1
Name: count, dtype: int64
count    800.000000
mean       1.071562
std        0.436651
min        0.250000
25%        1.000000
50%        1.000000
75%        1.000000
max        4.000000
Name: DamageFromDark, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

##### **DamageFromFairy**
</span>

In [148]:
describe_feature(data, 'DamageFromFairy')

- Type: float64
- First rows:
0    0.5
1    0.5
2    0.5
3    0.5
4    0.5
Name: DamageFromFairy, dtype: float64
- Last rows:
795    1.0
796    1.0
797    1.0
798    2.0
799    0.5
Name: DamageFromFairy, dtype: float64
- Number of missing values: 0
float64
- Number of distinct values: 5
- Unique value counts:
DamageFromFairy
1.00    527
0.50    149
2.00    117
4.00      6
0.25      1
Name: count, dtype: int64
count    800.000000
mean       1.074688
std        0.505724
min        0.250000
25%        1.000000
50%        1.000000
75%        1.000000
max        4.000000
Name: DamageFromFairy, dtype: float64

<span style = "font-family: Verdana; font-size: 20px">

#### **II. Combat dataset**
</span>

In [149]:
print("Combat dataset")
print(f"Number of rows: {combats.shape[0]}, number of columns: {combats.shape[1]}")
print(f"Column names: {combats.columns}")
print(f"Number of missing values: {combats.isna().sum().sum()}")

Combat dataset
Number of rows: 50000, number of columns: 3
Column names: Index(['First_pokemon', 'Second_pokemon', 'Winner'], dtype='object')
Number of missing values: 0

In [150]:
# Tổng số trận thắng của mỗi Pokémon
total_wins = combats['Winner'].value_counts()
# Số trận thắng của mỗi Pokémon
number_of_wins = combats.groupby('Winner').count()

countByFirst = combats.groupby('Second_pokemon').count() # Hai kiểu group cho ra cùng kết quả
countBySecond = combats.groupby('First_pokemon').count()
print("Looking at the dimensions of our dataframes")
print("Count by first winner shape: " + str(countByFirst.shape))
print("Count by second winner shape: " + str(countBySecond.shape))
print("Total wins shape : " + str(total_wins.shape))

Looking at the dimensions of our dataframes
Count by first winner shape: (784, 2)
Count by second winner shape: (784, 2)
Total wins shape : (783,)

<span style = "font-family: Verdana; font-size: 20px">

Có thể thấy số chiều của dataframe tổng trận thắng không giống với số chiều của hai dataframe đếm số trận thắng theo từng Pokémon. 

Điều này cho thấy có một Pokémon chưa từng thắng trận nào trong dữ liệu.

In [151]:
locate_losing_pokemon = np.setdiff1d(countByFirst.index.values, number_of_wins.index.values)-1
losing_pokemon = data.iloc[locate_losing_pokemon[0],]
losing_pokemon

ID                                   231
Name                             Shuckle
Type 1                               Bug
Type 2                              Rock
HiddenAbility                   Contrary
Generation                             2
Hp                                  20.0
Attack                              10.0
Defense                            230.0
SpecialAttack                       10.0
SpecialDefense                     230.0
Speed                                5.0
TotalStats                         505.0
Weight                              20.5
Height                               0.6
GenderProbM                          0.5
Category                    Mold Pokémon
CatchRate                            190
EggCycles                             20
LevelingRate                 Medium Slow
BaseFriendship                        70
IsLegendary                            0
IsMythical                             0
HasMega                                0
EvoStage                               1
TotalEvoStages                         1
PreevoName               No Preevolution
DamageFromNormal                     0.5
DamageFromFighting                   1.0
DamageFromFlying                     1.0
DamageFromPoison                     0.5
DamageFromGround                     1.0
DamageFromRock                       2.0
DamageFromBug                        1.0
DamageFromGhost                      1.0
DamageFromSteel                      2.0
DamageFromFire                       1.0
DamageFromWater                      2.0
DamageFromGrass                      1.0
DamageFromElectric                   1.0
DamageFromPsychic                    1.0
DamageFromIce                        1.0
DamageFromDragon                     1.0
DamageFromDark                       1.0
DamageFromFairy                      1.0
Ability 1                         Sturdy
Ability 2                       Gluttony
NoGender                               0
EggGroup1                            Bug
EggGroup2             No Eggs Discovered
IsMega                                 0
Name: 230, dtype: object

<span style = "font-family: Verdana; font-size: 20px">

Tội nghiệp Shuckle 🙁 Tuy chỉ số phòng thủ khá ấn tượng, cao nhất trong số các Pokémon, nhưng các chỉ số khác lại cực kỳ thấp so với mặt bằng chung.

<span style = "font-family: Verdana; font-size: 20px">

Có tồn tại Pokémon chưa từng thắng trận nào, vậy chắc cũng phải có Pokémon nào chưa từng tham gia trận nào chứ?

In [152]:
pokemon_not_in_combat = data[~data['ID'].astype(int).isin(number_of_wins.index)]
pokemon_not_in_combat

,ID,Name,Type 1,Type 2,HiddenAbility,Generation,Hp,Attack,Defense,SpecialAttack,SpecialDefense,Speed,TotalStats,Weight,Height,GenderProbM,Category,CatchRate,EggCycles,LevelingRate,BaseFriendship,IsLegendary,IsMythical,HasMega,EvoStage,TotalEvoStages,PreevoName,DamageFromNormal,DamageFromFighting,DamageFromFlying,DamageFromPoison,DamageFromGround,DamageFromRock,DamageFromBug,DamageFromGhost,DamageFromSteel,DamageFromFire,DamageFromWater,DamageFromGrass,DamageFromElectric,DamageFromPsychic,DamageFromIce,DamageFromDragon,DamageFromDark,DamageFromFairy,Ability 1,Ability 2,NoGender,EggGroup1,EggGroup2,IsMega
11,12,Blastoise,Water,Water,Rain Dish,1,79.0,83.0,100.0,85.0,105.0,78.0,530.0,85.5,1.6,0.875,Shellfish Pokémon,45,20,Medium Slow,70,0,0,1,3,3,Wartortle,1.0,1.00,1.00,1.0,1.0,1.0,1.0,1.0,0.50,0.5,0.5,2.00,2.0,1.0,0.5,1.0,1.0,1.0,Torrent,None,0,Monster,Water 1,0
32,33,Sandshrew,Ground,Ground,Sand Rush,1,50.0,75.0,85.0,20.0,30.0,40.0,300.0,12.0,0.6,0.500,Mouse Pokémon,255,20,Medium Fast,70,0,0,0,1,2,No Preevolution,1.0,1.00,1.00,0.5,1.0,0.5,1.0,1.0,1.00,1.0,2.0,2.00,0.0,1.0,2.0,1.0,1.0,1.0,Sand Veil,None,0,Field,No Eggs Discovered,0
45,46,Wigglytuff,Normal,Fairy,Frisk,1,140.0,70.0,45.0,85.0,50.0,45.0,435.0,12.0,1.0,0.250,Balloon Pokémon,50,10,Fast,70,0,0,0,3,3,Jigglypuff,1.0,1.00,1.00,2.0,1.0,1.0,0.5,0.0,2.00,1.0,1.0,1.00,1.0,1.0,1.0,0.0,0.5,1.0,Cute Charm,Competitive,0,Fairy,No Eggs Discovered,0
65,66,Poliwag,Water,Water,Swift Swim,1,40.0,50.0,40.0,40.0,40.0,90.0,300.0,12.4,0.6,0.500,Tadpole Pokémon,255,20,Medium Slow,70,0,0,0,1,3,No Preevolution,1.0,1.00,1.00,1.0,1.0,1.0,1.0,1.0,0.50,0.5,0.5,2.00,2.0,1.0,0.5,1.0,1.0,1.0,Water Absorb,Damp,0,Water 1,No Eggs Discovered,0
77,78,Victreebel,Grass,Poison,Gluttony,1,80.0,105.0,65.0,100.0,70.0,70.0,490.0,15.5,1.7,0.500,Flycatcher Pokémon,45,20,Medium Slow,70,0,0,0,3,3,Weepinbell,1.0,0.50,2.00,1.0,1.0,1.0,1.0,1.0,1.00,2.0,0.5,0.25,0.5,2.0,2.0,1.0,1.0,0.5,Chlorophyll,None,0,Grass,No Eggs Discovered,0
89,90,Magneton,Electric,Steel,Analytic,1,50.0,60.0,95.0,120.0,70.0,70.0,465.0,60.0,1.0,0.500,Magnet Pokémon,60,20,Medium Fast,70,0,0,0,2,3,Magnemite,0.5,2.00,0.25,0.0,4.0,0.5,0.5,1.0,0.25,2.0,1.0,0.50,0.5,0.5,0.5,0.5,1.0,0.5,Magnet Pull,Sturdy,1,Mineral,No Eggs Discovered,0
143,144,Ditto,Normal,Normal,Imposter,1,48.0,48.0,48.0,48.0,48.0,48.0,288.0,4.0,0.3,0.500,Transform Pokémon,35,20,Medium Fast,70,0,0,0,1,1,No Preevolution,1.0,2.00,1.00,1.0,1.0,1.0,1.0,0.0,1.00,1.0,1.0,1.00,1.0,1.0,1.0,1.0,1.0,1.0,Limber,None,1,Ditto,No Eggs Discovered,0
182,183,Ariados,Bug,Poison,Sniper,2,70.0,90.0,70.0,60.0,70.0,40.0,400.0,33.5,1.1,0.500,Long Leg Pokémon,90,15,Fast,70,0,0,0,2,2,Spinarak,1.0,0.25,2.00,0.5,1.0,2.0,0.5,1.0,1.00,2.0,1.0,0.25,1.0,2.0,1.0,1.0,1.0,0.5,Swarm,Insomnia,0,Bug,No Eggs Discovered,0
230,231,Shuckle,Bug,Rock,Contrary,2,20.0,10.0,230.0,10.0,230.0,5.0,505.0,20.5,0.6,0.500,Mold Pokémon,190,20,Medium Slow,70,0,0,0,1,1,No Preevolution,0.5,1.00,1.00,0.5,1.0,2.0,1.0,1.0,2.00,1.0,2.0,1.00,1.0,1.0,1.0,1.0,1.0,1.0,Sturdy,Gluttony,0,Bug,No Eggs Discovered,0
235,236,Ursaring,Normal,Normal,Unnerve,2,90.0,130.0,75.0,75.0,75.0,55.0,500.0,125.8,1.8,0.500,Hibernator Pokémon,60,20,Medium Fast,70,0,0,0,2,3,Teddiursa,1.0,2.00,1.00,1.0,1.0,1.0,1.0,0.0,1.00,1.0,1.0,1.00,1.0,1.0,1.0,1.0,1.0,1.0,Guts,Quick Feet,0,Field,No Eggs Discovered,0
321,322,Hariyama,Fighting,Fighting,Sheer Force,3,144.0,120.0,60.0,40.0,60.0,50.0,474.0,253.8,2.3,0.750,Arm Thrust Pokémon,200,20,Fluctuating,70,0,0,0,2,2,Makuhita,1.0,1.00,2.00,1.0,1.0,0.5,0.5,1.0,1.00,1.0,1.0,1.00,1.0,2.0,1.0,1.0,0.5,2.0,Thick Fat,Guts,0,Human-Like,No Eggs Discovered,0
418,419,Mega Latias,Dragon,Psychic,None,3,80.0,100.0,120.0,140.0,150.0,110.0,700.0,52.0,1.8,0.000,Eon Pokémon,3,120,Slow,90,1,0,1,1,1,Latias,1.0,0.50,1.00,1.0,0.0,1.0,2.0,2.0,1.00,0.5,0.5,0.50,0.5,0.5,2.0,2.0,2.0,2.0,Levitate,None,0,No Eggs Discovered,No Eggs Discovered,1
478,479,Honchkrow,Dark,Flying,Moxie,4,100.0,125.0,52.0,105.0,52.0,71.0,505.0,27.3,0.9,0.500,Big Boss Pokémon,30,20,Medium Slow,35,0,0,0,2,2,Murkrow,1.0,1.00,1.00,1.0,0.0,2.0,1.0,0.5,1.00,1.0,1.0,0.50,2.0,0.0,2.0,1.0,0.5,2.0,Insomnia,Super Luck,0,Flying,No Eggs Discovered,0
555,556,Servine,Grass,Grass,Contrary,5,60.0,60.0,75.0,60.0,75.0,83.0,413.0,16.0,0.8,0.875,Grass Snake Pokémon,45,20,Medium Slow,70,0,0,0,2,3,Snivy,1.0,1.00,2.00,2.0,0.5,1.0,2.0,1.0,1.00,2.0,0.5,0.50,0.5,1.0,2.0,1.0,1.0,1.0,Overgrow,None,0,Field,Grass,0
617,618,Maractus,Grass,Grass,Storm Drain,5,75.0,86.0,67.0,106.0,67.0,60.0,461.0,28.0,1.0,0.500,Cactus Pokémon,255,20,Medium Fast,70,0,0,0,1,1,No Preevolution,1.0,1.00,2.00,2.0,0.5,1.0,2.0,1.0,1.00,2.0,0.5,0.50,0.5,1.0,2.0,1.0,1.0,1.0,Water Absorb,Chlorophyll,0,Grass,No Eggs Discovered,0
654,655,Jellicent,Water,Ghost,Damp,5,100.0,60.0,70.0,85.0,105.0,60.0,480.0,135.0,2.2,0.500,Floating Pokémon,60,20,Medium Fast,70,0,0,0,2,2,Frillish,0.0,0.00,1.00,0.5,1.0,1.0,0.5,2.0,0.50,0.5,0.5,2.00,2.0,1.0,0.5,1.0,2.0,1.0,Water Absorb,Cursed Body,0,Amorphous,No Eggs Discovered,0
781,782,Pumpkaboo Small Size,Ghost,Grass,Insomnia,6,44.0,66.0,70.0,44.0,55.0,56.0,335.0,3.5,0.3,0.500,Pumpkin Pokémon,120,20,Medium Fast,70,0,0,1,1,2,No Preevolution,0.0,0.00,2.00,1.0,0.5,1.0,1.0,2.0,1.00,2.0,0.5,0.50,0.5,1.0,2.0,1.0,2.0,1.0,Frisk,None,0,Amorphous,No Eggs Discovered,0

<span style = "font-family: Verdana; font-size: 20px">

Vậy linh cảm trước đó là đúng, thực sự có Pokémon chưa từng tham gia trận nào.

<span style = "font-family: Verdana; font-size: 20px">

Tính toán tỷ lệ thắng `WinRate`, tổng trận tham gia `TotalFights` và trận thắng `FightsWon` cho mỗi Pokémon, sẽ rất hữu ích cho giai đoạn trực quan hoá sắp tới, có thể coi là một phần của feature engineering luôn.
</span>

In [153]:
number_of_wins = number_of_wins.sort_index()
number_of_wins.rename(columns={'First_pokemon': 'FightsWon'}, inplace=True)
number_of_wins = number_of_wins.drop('Second_pokemon', axis = 1)
number_of_wins['TotalFights'] = countByFirst.Winner + countBySecond.Winner

In [154]:
number_of_wins.info()

<class 'pandas.core.frame.DataFrame'>
Index: 783 entries, 1 to 800
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   FightsWon    783 non-null    int64
 1   TotalFights  783 non-null    int64
dtypes: int64(2)
memory usage: 18.4 KB

In [155]:
data['ID'] = data['ID'].astype(int) # Chuyển ID sang int để merge với number_of_wins

In [156]:
data = pd.merge(data, number_of_wins, left_on='ID', right_index = True, how='left')

<span style = "font-family: Verdana; font-size: 20px">

Xử lý định dạng và missing value cho các cột mới được thêm.

In [157]:
data['FightsWon'] = data['FightsWon'].fillna(0).astype(int)
data['TotalFights'] = data['TotalFights'].fillna(0).astype(int)
data['WinPercentage'] = (data['FightsWon']/data['TotalFights']).round(6)
data['WinPercentage'] = data['WinPercentage'].fillna(0.0)

In [158]:
with open('data/modified/viz_pokemon.csv', 'w', encoding = 'utf-8') as f:
    data.to_csv(f, index=False)